:- encoding(utf8).

% Arquivo gerado automaticamente por tools/generate_abilities_items_db.js
% ability_entry(Ability, Generation, IsMainSeries, ShortEffect, Effect).
ability_entry(adaptability, generation_iv, true, 'Increases the same-type attack bonus from 1.5× to 2×.', 'This Pokémon inflicts twice as much damage with moves whose types match its own, rather than the usual same-type attack bonus of 1.5×.').
ability_entry(aerilate, generation_vi, true, 'Turns the bearer''s normal moves into flying moves and strengthens them to 1.3× their power.', 'Turns the bearer''s normal-type moves into flying-type moves. Moves changed by this ability have 1.3× their power.').
ability_entry(aftermath, generation_iv, true, 'Damages the attacker for 1/4 its max HP when knocked out by a contact move.', 'When this Pokémon is knocked out by a move that makes contact, the move''s user takes 1/4 its maximum HP in damage.').
ability_entry(air_lock, generation_iii, true, 'Negates all effects of weather, but does not prevent the weather itself.', 'While this Pokémon is in battle, weather can still be in play, but will not have any of its effects. This ability functions identically to cloud nine.').
ability_entry(analytic, generation_v, true, 'Strengthens moves to 1.3× their power when moving last.', 'This Pokémon''s moves have 1.3× their power when it moves last in a turn. future sight and doom desire are unaffected.').
ability_entry(anger_point, generation_iv, true, 'Raises Attack to the maximum of six stages upon receiving a critical hit.', 'Whenever this Pokémon receives a critical hit, its Attack rises to the maximum of 6 stages. This ability will still take effect if the critical hit is received by a substitute.').
ability_entry(anger_shell, generation_ix, true, 'When the Pokémon''s HP drops below half, Anger Shell lowers its Defense and Special Defense but its Attack, Special Attack and Speed are raised.', 'When an attack causes its HP to drop to half or less, the Pokémon gets angry. This lowers its Defense and Sp. Def stats but boosts its Attack, Sp. Atk, and Speed stats.').
ability_entry(anticipation, generation_iv, true, 'Notifies all trainers upon entering battle if an opponent has a super-effective move, self destruct, explosion, or a one-hit KO move.', 'When this Pokémon enters battle, if one of its opponents has a move that is super effective against it, self destruct, explosion, or a one-hit knockout move, all participating trainers are notified. The move itself is not revealed; only that there is such a move. Moves that inflict typeless damage, such as future sight, and moves of variable type, such as hidden power, count as their listed types. counter, metal burst, mirror coat, and one-hit KO moves to which this Pokémon is immune do not trigger this ability.').
ability_entry(arena_trap, generation_iii, true, 'Prevents opponents from fleeing or switching out. Eluded by flying-types and Pokémon in the air.', 'While this Pokémon is in battle, opposing Pokémon cannot flee or switch out. flying-type Pokémon and Pokémon in the air, e.g. due to levitate or magnet rise, are unaffected. Pokémon with run away can still flee. Pokémon can still switch out with the use of a move or item. Overworld: If the lead Pokémon has this ability, the wild encounter rate is doubled.').
ability_entry(armor_tail, generation_ix, true, 'Prevents the opponent from using any moves that have priority, such as Quick Attack.', 'The mysterious tail covering the Pokémon’s head makes opponents unable to use priority moves against the Pokémon or its allies.').
ability_entry(aroma_veil, generation_vi, true, 'Protects allies against moves that affect their mental state.', 'Protects allies against moves that affect their mental state.').
ability_entry(as_one_glastrier, generation_viii, true, 'This Ability combines the effects of both Calyrex''s Unnerve Ability and Glastrier''s Chilling Neigh Ability.', 'This Ability combines the effects of both Calyrex''s Unnerve Ability and Glastrier''s Chilling Neigh Ability.').
ability_entry(as_one_spectrier, generation_viii, true, 'This Ability combines the effects of both Calyrex''s Unnerve Ability and Spectrier''s Grim Neigh Ability.', 'This Ability combines the effects of both Calyrex''s Unnerve Ability and Spectrier''s Grim Neigh Ability.').
ability_entry(aura_break, generation_vi, true, 'Makes dark aura and fairy aura weaken moves of their respective types.', 'While this Pokémon is on the field, dark aura and fairy aura weaken moves of their respective types to 2/3 their power, rather than strengthening them.').
ability_entry(bad_dreams, generation_iv, true, 'Damages sleeping opponents for 1/8 their max HP after each turn.', 'Opposing Pokémon take 1/8 of their maximum HP in damage after each turn while they are asleep.').
ability_entry(ball_fetch, generation_viii, true, 'If the Pokémon is not holding an item, it will fetch the Poké Ball from the first failed throw of the battle.', 'At any time after the first Poké Ball is thrown and fails to catch a Pokémon, at the end of a turn, if a Pokémon with Ball Fetch is on the field and not holding another item, it will pick up the same type of ball as the first one thrown.').
ability_entry(battery, generation_vii, true, 'Ally Pokémon''s moves have their power increased to 1.3×.', 'Ally Pokémon''s moves have their power increased to 1.3×.').
ability_entry(battle_armor, generation_iii, true, 'Protects against critical hits.', 'Moves cannot score critical hits against this Pokémon. This ability functions identically to shell armor.').
ability_entry(battle_bond, generation_vii, true, 'Transforms this Pokémon into Ash-Greninja after fainting an opponent. Water Shuriken''s power is 20 and always hits three times.', 'Transforms this Pokémon into Ash-Greninja after fainting an opponent. Water Shuriken''s power is 20 and always hits three times. This ability cannot be copied or replaced. This ability only takes effect for Greninja.').
ability_entry(beads_of_ruin, generation_ix, true, 'Lowers Special Defense of all Pokémon except itself.', 'The power of the Pokémon’s ruinous beads lowers the Sp. Def stats of all Pokémon except itself.').
ability_entry(beast_boost, generation_vii, true, 'Raises this Pokémon''s highest stat by one stage when it faints another Pokémon.', 'Raises this Pokémon''s highest stat by one stage when it faints another Pokémon.').
ability_entry(berserk, generation_vii, true, 'Raises this Pokémon''s Special Attack by one stage every time its HP drops below half.', 'Whenever this Pokémon takes damage from a move that causes its HP to drop below 50%, its Special Attack rises by one stage.').
ability_entry(big_pecks, generation_v, true, 'Protects against Defense drops.', 'This Pokémon''s Defense cannot be lowered by other Pokémon. This Pokémon can still be passed negative Defense modifiers through heart swap or guard swap.').
ability_entry(blaze, generation_iii, true, 'Strengthens fire moves to inflict 1.5× damage at 1/3 max HP or less.', 'When this Pokémon has 1/3 or less of its HP remaining, its fire-type moves inflict 1.5× as much regular damage.').
ability_entry(bulletproof, generation_vi, true, 'Protects against bullet, ball, and bomb-based moves.', 'Protects against bullet, ball, and bomb-based moves.').
ability_entry(cheek_pouch, generation_vi, true, 'Restores HP upon eating a Berry, in addition to the Berry''s effect.', 'Restores HP upon eating a Berry, in addition to the Berry''s effect.').
ability_entry(chilling_neigh, generation_viii, true, 'Boosts Attack after knocking out a Pokémon.', 'When the Pokémon knocks out a target, it utters a chilling neigh, which boosts its Attack stat.').
ability_entry(chlorophyll, generation_iii, true, 'Doubles Speed during strong sunlight.', 'This Pokémon''s Speed is doubled during strong sunlight. This bonus does not count as a stat modifier.').
ability_entry(clear_body, generation_iii, true, 'Prevents stats from being lowered by other Pokémon.', 'This Pokémon cannot have its stats lowered by other Pokémon. This ability does not prevent any stat losses other than stat modifiers, such as the Speed cut from paralysis. This Pokémon can still be passed negative stat modifiers through guard swap, heart swap, or power swap. This ability functions identically to white smoke in battle.').
ability_entry(cloud_nine, generation_iii, true, 'Negates all effects of weather, but does not prevent the weather itself.', 'While this Pokémon is in battle, weather can still be in play, but will not have any of its effects. This ability functions identically to air lock.').
ability_entry(color_change, generation_iii, true, 'Changes type to match when hit by a damaging move.', 'Whenever this Pokémon takes damage from a move, the Pokémon''s type changes to match the move. If the Pokémon has two types, both are overridden. The Pokémon must directly take damage; for example, moves blocked by a substitute will not trigger this ability, nor will moves that deal damage indirectly, such as spikes. This ability takes effect on only the last hit of a multiple-hit attack. In Pokémon Colosseum and XD: Gale of Darkness, this ability does not take effect on Shadow-type moves.').
ability_entry(comatose, generation_vii, true, 'This Pokémon always acts as though it were Asleep.', 'This Pokémon always acts as though it were Asleep. It cannot be given another status ailment; it''s unaffected by yawn; it can use sleep talk; and so on.').
ability_entry(commander, generation_ix, true, 'Goes inside the mouth of an ally Dondozo if one is on the field.', 'When the Pokémon enters a battle, it goes inside the mouth of an ally Dondozo if one is on the field. The Pokémon then issues commands from there.').
ability_entry(competitive, generation_vi, true, 'Raises Special Attack by two stages upon having any stat lowered.', 'Raises Special Attack by two stages upon having any stat lowered.').
ability_entry(compound_eyes, generation_iii, true, 'Increases moves'' accuracy to 1.3×.', 'This Pokémon''s moves have 1.3× their accuracy. This ability has no effect on the one-hit KO moves (fissure, guillotine, horn drill, and sheer cold). Overworld: If the first Pokémon in the party has this ability, the chance of a wild Pokémon holding a particular item is raised from 50%, 5%, or 1% to 60%, 20%, or 5%, respectively.').
ability_entry(contrary, generation_v, true, 'Inverts stat changes.', 'Whenever this Pokémon''s stats would be raised, they are instead lowered by the same amount, and vice versa.').
ability_entry(corrosion, generation_vii, true, 'This Pokémon can inflict poison on Poison and Steel Pokémon.', 'This Pokémon''s moves and item ignore the usual immunity of Poison and Steel Pokémon when attempting to inflict poison.').
ability_entry(costar, generation_ix, true, 'Copies ally''s stat changes on entering battle.', 'When the Pokémon enters a battle, it copies an ally’s stat changes.').
ability_entry(cotton_down, generation_viii, true, 'When Ignores moves and abilities that draw in moves.', 'When the Pokémon is hit by an attack, it scatters cotton fluff around and lowers the Speed stats of all Pokémon except itself.').
ability_entry(cud_chew, generation_ix, true, 'Causes the Pokémon to reuse an already consumed Berry at the end of the next turn.', 'When the Pokémon eats a Berry, it will regurgitate that Berry at the end of the next turn and eat it one more time.').
ability_entry(curious_medicine, generation_viii, true, 'Resets all stat changes upon entering battlefield.', 'When the Pokémon enters a battle, it scatters medicine from its shell, which removes all stat changes from allies.').
ability_entry(cursed_body, generation_v, true, 'Has a 30% chance of Disabling any move that hits the Pokémon.', 'Moves that hit this Pokémon have a 30% chance of being Disabled afterward.').
ability_entry(cute_charm, generation_iii, true, 'Has a 30% chance of infatuating attacking Pokémon on contact.', 'Whenever a move makes contact with this Pokémon, the move''s user has a 30% chance of being infatuated. Overworld: If the first Pokémon in the party has this ability, any wild Pokémon whose species can be either gender has a 2/3 chance of being set to the opposite gender, and a 1/3 chance of having a random gender as usual.').
ability_entry(damp, generation_iii, true, 'Prevents self destruct, explosion, and aftermath from working while the Pokémon is in battle.', 'While this Pokémon is in battle, self destruct and explosion will fail and aftermath will not take effect.').
ability_entry(dancer, generation_vii, true, 'Whenever another Pokémon uses a dance move, this Pokémon will use the same move immediately afterwards.', 'Whenever another Pokémon uses a dance move, this Pokémon will use the same move immediately afterwards.').
ability_entry(dark_aura, generation_vi, true, 'Strengthens dark moves to 1.33× their power for all friendly and opposing Pokémon.', 'Strengthens dark moves for all friendly and opposing Pokémon.').
ability_entry(dauntless_shield, generation_viii, true, 'Boosts Defense in battle.', 'Boosts the Pokémon’s Defense stat the first time the Pokémon enters a battle.').
ability_entry(dazzling, generation_vii, true, 'Opposing Pokémon cannot use priority attacks.', 'When an opposing Pokémon attempts to use a move that targets this Pokémon or an ally, and that move has priority, it will fail.').
ability_entry(defeatist, generation_v, true, 'Halves Attack and Special Attack at 50% max HP or less.', 'This Pokémon''s Attack and Special Attack are halved when it has half its HP or less.').
ability_entry(defiant, generation_v, true, 'Raises Attack two stages upon having any stat lowered.', 'When any of this Pokémon''s stats are lowered, its Attack rises by two stages. If multiple stats are lowered at once, this ability takes effect with each stat lowered.').
ability_entry(delta_stream, generation_vi, true, 'Creates a mysterious air current, which cannot be replaced and causes moves to never be super effective against Flying Pokémon.', 'When this Pokémon enters battle or gains this ability, the weather becomes a mysterious air current. A mysterious air current causes moves to not be super effective against Flying; they do neutral damage instead. anticipation and stealth rock are not affected. The mysterious air current ends when this Pokémon leaves battle or loses this ability, or when this ability is nullified. The weather cannot otherwise be changed except by the effects of desolate land and primordial sea. air lock and cloud nine will prevent the effect of a mysterious air current, but will not allow the weather to be changed.').
ability_entry(desolate_land, generation_vi, true, 'Creates extremely harsh sunlight, which has all the properties of Sunny Day, cannot be replaced, and causes damaging Water moves to fail.', 'When this Pokémon enters battle or gains this ability, the weather becomes extremely harsh sunlight. Extremely harsh sunlight has all the properties of sunny day and also causes damaging Water moves to fail. Extremely harsh sunlight ends when this Pokémon leaves battle or loses this ability, or when this ability is nullified. The weather cannot otherwise be changed except by the effects of delta stream and primordial sea. air lock and cloud nine will prevent the effects of extremely harsh sunlight, including allowing Water moves to work, but will not allow the weather to be changed.').
ability_entry(disguise, generation_vii, true, 'Prevents the first instance of battle damage.', 'If this Pokémon is in its Disguised Form and takes damage from a move, it switches to its Busted Form and the damage is prevented. Other effects are not prevented. This ability cannot be copied or replaced. This ability only takes effect for Mimikyu.').
ability_entry(download, generation_iv, true, 'Raises the attack stat corresponding to the opponents'' weaker defense one stage upon entering battle.', 'When this Pokémon enters battle, its Attack or Special Attack, whichever corresponds to its opponents'' weaker total defensive stat, rises one stage. In the event of a tie, Special Attack is raised. This ability also takes effect when acquired during a battle.').
ability_entry(dragons_maw, generation_viii, true, 'Powers up Dragon-type moves.', 'Increases the power of Dragon-type moves used by this Pokémon by 50%.').
ability_entry(drizzle, generation_iii, true, 'Summons rain that lasts indefinitely upon entering battle.', 'The weather changes to rain when this Pokémon enters battle and does not end unless replaced by another weather condition. If multiple Pokémon with this ability, drought, sand stream, or snow warning are sent out at the same time, the abilities will activate in order of Speed, respecting trick room. Each ability''s weather will cancel the previous weather, and only the weather summoned by the slowest of the Pokémon will stay.').
ability_entry(drought, generation_iii, true, 'Summons strong sunlight that lasts indefinitely upon entering battle.', 'The weather changes to strong sunlight when this Pokémon enters battle and does not end unless cancelled by another weather condition. If multiple Pokémon with this ability, drizzle, sand stream, or snow warning are sent out at the same time, the abilities will activate in order of Speed, respecting trick room. Each ability''s weather will cancel the previous weather, and only the weather summoned by the slowest of the Pokémon will stay.').
ability_entry(dry_skin, generation_iv, true, 'Causes 1/8 max HP in damage each turn during strong sunlight, but heals for 1/8 max HP during rain. Increases damage from fire moves to 1.25×, but absorbs water moves, healing for 1/4 max HP.', 'This Pokémon takes 1/8 of its maximum HP in damage after each turn during strong sunlight, but it heals for 1/8 of its HP each turn during rain. This Pokémon takes 1.25× as much damage from fire-type moves, but whenever a water move hits it, it heals for 1/4 its maximum HP instead.').
ability_entry(early_bird, generation_iii, true, 'Makes sleep pass twice as quickly.', 'This Pokémon''s remaining sleep turn count falls by 2 rather than 1. If this Pokémon''s sleep counter is at 1, it will fall to 0 and then the Pokémon will wake up.').
ability_entry(earth_eater, generation_ix, true, 'Restores HP when hit by a Ground-type move.', 'If hit by a Ground-type move, the Pokémon has its HP restored instead of taking damage.').
ability_entry(effect_spore, generation_iii, true, 'Has a 30% chance of inflcting either paralysis, poison, or sleep on attacking Pokémon on contact.', 'Whenever a move makes contact with this Pokémon, the move''s user has a 30% chance of being paralyzed, poisoned, or put to sleep, chosen at random. Nothing is done to compensate if the move''s user is immune to one of these ailments; there is simply a lower chance that the move''s user will be affected.').
ability_entry(electric_surge, generation_vii, true, 'When this Pokémon enters battle, it changes the terrain to Electric Terrain.', 'When this Pokémon enters battle, it changes the terrain to electric terrain.').
ability_entry(electromorphosis, generation_ix, true, 'When hit by an attack, the power of the next Electric-type move it uses is doubled.', 'The Pokémon becomes charged when it takes damage, boosting the power of the next Electric-type move the Pokémon uses.').
ability_entry(embody_aspect, generation_ix, true, 'Embody Aspect boosts a particular stat, depending on the form of a Terastallized Ogerpon', 'Embody Aspect boosts a particular stat, depending on the form of a Terastallized Ogerpon').
ability_entry(emergency_exit, generation_vii, true, 'This Pokémon automatically switches out when its HP drops below half.', 'After this Pokémon is hit by a move, if that move caused this Pokémon''s HP to drop below half, it switches out.').
ability_entry(fairy_aura, generation_vi, true, 'Strengthens fairy moves to 1.33× their power for all friendly and opposing Pokémon.', 'Strengthens fairy moves for all friendly and opposing Pokémon.').
ability_entry(filter, generation_iv, true, 'Decreases damage taken from super-effective moves by 1/4.', 'This Pokémon takes 0.75× as much damage from moves that are super effective against it. This ability functions identically to solid rock.').
ability_entry(flame_body, generation_iii, true, 'Has a 30% chance of burning attacking Pokémon on contact.', 'Whenever a move makes contact with this Pokémon, the move''s user has a 30% chance of being burned. Overworld: If any Pokémon in the party has this ability, each egg in the party has its hatch counter decreased by 2 (rather than 1) each step cycle, making eggs hatch roughly twice as quickly. This effect does not stack if multiple Pokémon have this ability or magma armor.').
ability_entry(flare_boost, generation_v, true, 'Increases Special Attack to 1.5× when burned.', 'This Pokémon has 1.5× its Special Attack when burned.').
ability_entry(flash_fire, generation_iii, true, 'Protects against fire moves. Once one has been blocked, the Pokémon''s own Fire moves inflict 1.5× damage until it leaves battle.', 'This Pokémon is immune to fire-type moves. Once this Pokémon has been hit by a Fire move, its own Fire moves will inflict 1.5× as much damage until it leaves battle. This ability has no effect while the Pokémon is frozen. The Fire damage bonus is retained even if the Pokémon is frozen and thawed or the ability is lost or disabled. Fire moves will ignore this Pokémon''s substitute. This ability takes effect even on non-damaging moves, i.e. will o wisp.').
ability_entry(flower_gift, generation_iv, true, 'Increases friendly Pokémon''s Attack and Special Defense to 1.5× during strong sunlight.', 'Friendly Pokémon have 1.5× their Attack and Special Defense during strong sunlight if any friendly Pokémon has this ability. Unlike forecast, multitype, and zen mode, this ability is not tied to its Pokémon''s form change; cherrim will switch between its forms even if it loses this ability. As such, this ability also works if obtained by a Pokémon other than Cherrim.').
ability_entry(flower_veil, generation_vi, true, 'Protects friendly grass Pokémon from having their stats lowered by other Pokémon.', 'Protects friendly grass Pokémon from having their stats lowered by other Pokémon.').
ability_entry(fluffy, generation_vii, true, 'Damage from contact moves is halved. Damage from Fire moves is doubled.', 'Damage from contact moves is halved. Damage from Fire moves is doubled.').
ability_entry(forecast, generation_iii, true, 'Changes castform''s type and form to match the weather.', 'During rain, strong sunlight, or hail, this Pokémon''s type changes to water, fire, or ice, respectively, and its form changes to match. This ability has no effect for any Pokémon other than castform. If the weather ends or becomes anything that does not trigger this ability, or a Pokémon with air lock or cloud nine enters battle, this Pokémon''s type and form revert to their default. If this ability is lost or disabled, this Pokémon cannot change its current type and form until it regains its ability.').
ability_entry(forewarn, generation_iv, true, 'Reveals the opponents'' strongest move upon entering battle.', 'When this Pokémon enters battle, it reveals the move with the highest base power known by any opposing Pokémon to all participating trainers. In the event of a tie, one is chosen at random. Moves without a listed base power are assigned one as follows: Power | Moves ----: | ----- 160 | One-hit KO moves: fissure, guillotine, horn drill, and sheer cold 120 | Counter moves: counter, metal burst, and mirror coat 80 | Variable power or set damage: crush grip, dragon rage, electro ball, endeavor, final gambit, flail, frustration, grass knot, gyro ball, heat crash, heavy slam, hidden power, low kick, natural gift, night shade, psywave, return, reversal, seismic toss, sonic boom, trump card, and wring out 0 | Any such move not listed').
ability_entry(friend_guard, generation_v, true, 'Decreases all direct damage taken by friendly Pokémon to 0.75×.', 'All friendly Pokémon take 0.75× as much direct damage from moves while this Pokémon is in battle. This effect stacks if multiple allied Pokémon have it.').
ability_entry(frisk, generation_iv, true, 'Reveals an opponent''s held item upon entering battle.', 'When this Pokémon enters battle, it reveals an opposing Pokémon''s held item to all participating trainers. In a double battle, if one opponent has an item, this Pokémon will Frisk that Pokémon; if both have an item, it will Frisk one at random.').
ability_entry(full_metal_body, generation_vii, true, 'Other Pokémon cannot lower this Pokémon''s stats.', 'This Pokémon''s stats cannot be lowered by other Pokémon''s moves or abilities. This effect only applies to normal stat modifications and not more exotic effects such as topsy turvy or power swap. This Ability is not bypassed by mold breaker, teravolt, or turboblaze.').
ability_entry(fur_coat, generation_vi, true, 'Halves damage from physical attacks.', 'Halves damage from physical attacks.').
ability_entry(gale_wings, generation_vi, true, 'Raises flying moves'' priority by one stage.', 'Raises flying moves'' priority by one stage.').
ability_entry(galvanize, generation_vii, true, 'This Pokémon''s Normal moves are Electric and have their power increased to 1.2×.', 'When this Pokémon uses a Normal moves, that move is Electric its power is 1.2×.').
ability_entry(gluttony, generation_iv, true, 'Makes the Pokémon eat any held Berry triggered by low HP below 1/2 its max HP.', 'This Pokémon eats any held Berry triggered by low HP when it falls below 50% of its HP, regardless of the Berry''s usual threshold.').
ability_entry(good_as_gold, generation_ix, true, 'Gives immunity to status moves.', 'A body of pure, solid gold gives the Pokémon full immunity to other Pokémon’s status moves.').
ability_entry(gooey, generation_vi, true, 'Lowers attacking Pokémon''s Speed by one stage on contact.', 'Lowers attacking Pokémon''s Speed by one stage on contact.').
ability_entry(gorilla_tactics, generation_viii, true, 'Boosts the Pokémon''s Attack stat but only allows the use of the first selected move.', 'Boosts the Pokémon’s Attack stat but only allows the use of the first selected move.').
ability_entry(grass_pelt, generation_vi, true, 'Boosts Defense while grassy terrain is in effect.', 'Boosts Defense while grassy terrain is in effect.').
ability_entry(grassy_surge, generation_vii, true, 'When this Pokémon enters battle, it changes the terrain to Grassy Terrain.', 'When this Pokémon enters battle, it changes the terrain to grassy terrain.').
ability_entry(grim_neigh, generation_viii, true, 'Boosts Special Attack after knocking out a Pokémon.', 'When the Pokémon knocks out a target, it utters a terrifying neigh, which boosts its Sp. Atk stat.').
ability_entry(guard_dog, generation_ix, true, 'Boosts Attack if intimidated, and prevents being forced to switch out.', 'Boosts the Pokémon’s Attack stat if intimidated. Moves and items that would force the Pokémon to switch out also fail to work.').
ability_entry(gulp_missile, generation_viii, true, 'If a Cramorant with Gulp Missile uses Surf or Dive, it catches prey and changes its form depending on its remaining HP.', 'When the Pokémon uses Surf or Dive, it will come back with prey. When it takes damage, it will spit out the prey to attack.').
ability_entry(guts, generation_iii, true, 'Increases Attack to 1.5× with a major status ailment.', 'Whenever this Pokémon is asleep, burned, paralyzed, or poisoned, it has 1.5× its Attack. This Pokémon is not affected by the usual Attack cut from a burn. This bonus does not count as a stat modifier.').
ability_entry(hadron_engine, generation_ix, true, 'Creates an Electric Terrain when entering battle, and boosts Special Attack while active.', 'Turns the ground into Electric Terrain when the Pokémon enters a battle. The futuristic engine within the Pokémon also boosts its Sp. Atk stat on Electric Terrain.').
ability_entry(harvest, generation_v, true, 'Has a 50% chance of restoring a used Berry after each turn if the Pokémon has held no items in the meantime.', 'After each turn, if the last item this Pokémon consumed was a Berry and it is not currently holding an item, it has a 50% chance of regaining that Berry, or a 100% chance during strong sunlight.').
ability_entry(healer, generation_v, true, 'Has a 30% chance of curing each adjacent ally of any major status ailment after each turn.', 'Friendly Pokémon next to this Pokémon in double and triple battles each have a 30% chance of being cured of any major status ailment after each turn.').
ability_entry(heatproof, generation_iv, true, 'Halves damage from fire moves and burns.', 'This Pokémon takes half as much damage from fire-type moves and burns.').
ability_entry(heavy_metal, generation_v, true, 'Doubles the Pokémon''s weight.', 'This Pokémon has double the usual weight for its species.').
ability_entry(honey_gather, generation_iv, true, 'The Pokémon may pick up honey after battle.', 'This Pokémon has a chance of picking up honey after each battle. This chance starts at 5% and rises another 5% after every tenth level: 5% from level 1–10, 10% from 11–20, and so on, up to 50% from 91–100. This ability is checked after the battle ends, at which point any temporary ability changes have worn off.').
ability_entry(hospitality, generation_ix, true, 'When a Pokémon with Hospitality enters a battle, it restores HP for an ally by 25%.', 'When the Pokémon enters a battle, it showers its ally with hospitality, restoring a small amount of the ally''s HP.').
ability_entry(huge_power, generation_iii, true, 'Doubles Attack in battle.', 'This Pokémon''s Attack is doubled while in battle. This bonus does not count as a stat modifier. This ability functions identically to pure power.').
ability_entry(hunger_switch, generation_viii, true, 'Causes Morpeko to change its form each turn, alternating between Full Belly Mode and Hangry Mode', 'The Pokémon changes its form, alternating between its Full Belly Mode and Hangry Mode after the end of every turn.').
ability_entry(hustle, generation_iii, true, 'Strengthens physical moves to inflict 1.5× damage, but decreases their accuracy to 0.8×.', 'This Pokémon''s physical moves do 1.5× as much regular damage, but have 0.8× their usual accuracy. Special moves are unaffected. Moves that do set damage, such as seismic toss, have their accuracy affected, but not their damage. Overworld: If the lead Pokémon has this ability, higher-levelled Pokémon have their encounter rate increased.').
ability_entry(hydration, generation_iv, true, 'Cures any major status ailment after each turn during rain.', 'This Pokémon is cured of any major status ailment after each turn during rain.').
ability_entry(hyper_cutter, generation_iii, true, 'Prevents Attack from being lowered by other Pokémon.', 'This Pokémon''s Attack cannot be lowered by other Pokémon. This ability does not prevent any Attack losses other than stat modifiers, such as the Attack cut from a burn. This Pokémon can still be passed negative Attack modifiers through heart swap or power swap.').
ability_entry(ice_body, generation_iv, true, 'Heals for 1/16 max HP after each turn during hail. Protects against hail damage.', 'This Pokémon heals for 1/16 of its maximum HP after each turn during hail, and it does not take hail damage regardless of type.').
ability_entry(ice_face, generation_viii, true, 'The Pokémon’s ice head can take a physical attack as a substitute, but the attack also changes the Pokémon’s appearance. The ice will be restored when it snows.', 'When an Eiscue that''s in its Ice Face form is hit by a physical move, it takes no damage and changes into its Noice Face form. If a hailstorm or snowstorm begins while Eiscue is in its Noice Face form, or if it is sent out in its Noice Face form during hail, it will immediately revert to its Ice Face form.').
ability_entry(ice_scales, generation_viii, true, 'Halves damage from Special moves.', 'The Pokémon is protected by ice scales, which halve the damage taken from special moves.').
ability_entry(illuminate, generation_iii, true, 'Doubles the wild encounter rate.', 'Overworld: If the lead Pokémon has this ability, the wild encounter rate is doubled. This ability has no effect in battle.').
ability_entry(illusion, generation_v, true, 'Takes the appearance of the last conscious party Pokémon upon being sent out until hit by a damaging move.', 'This Pokémon, upon being sent out, appears to have the species, nickname, and Poké Ball of the last Pokémon in the party that is able to battle. This illusion breaks upon being hit by a damaging move. Other damage, e.g. from weather or spikes, does not break the illusion, nor does damage done to a substitute. If the party order becomes temporarily shuffled around as Pokémon are switched out in battle, this ability chooses the last Pokémon according to that shuffled order.').
ability_entry(immunity, generation_iii, true, 'Prevents poison.', 'This Pokémon cannot be poisoned. This includes bad poison. If a Pokémon is poisoned and acquires this ability, its poison is healed; this includes when regaining a lost ability upon leaving battle.').
ability_entry(imposter, generation_v, true, 'Transforms upon entering battle.', 'This Pokémon transforms into a random opponent upon entering battle. This effect is identical to the move transform.').
ability_entry(infiltrator, generation_v, true, 'Bypasses light screen, reflect, and safeguard.', 'This Pokémon''s moves ignore light screen, reflect, and safeguard.').
ability_entry(innards_out, generation_vii, true, 'When this Pokémon faints from an opponent''s move, that opponent takes damage equal to the HP this Pokémon had remaining.', 'When this Pokémon faints from an opponent''s move, that opponent takes damage equal to the HP this Pokémon had remaining.').
ability_entry(inner_focus, generation_iii, true, 'Prevents flinching.', 'This Pokémon cannot flinch.').
ability_entry(insomnia, generation_iii, true, 'Prevents sleep.', 'This Pokémon cannot be asleep. This causes rest to fail altogether. If a Pokémon is asleep and acquires this ability, it will immediately wake up; this includes when regaining a lost ability upon leaving battle. This ability functions identically to vital spirit in battle.').
ability_entry(intimidate, generation_iii, true, 'Lowers opponents'' Attack one stage upon entering battle.', 'When this Pokémon enters battle, the opponent''s Attack is lowered by one stage. In a double battle, both opponents are affected. This ability also takes effect when acquired during a battle, but will not take effect again if lost and reobtained without leaving battle. This ability has no effect on an opponent that has a substitute. Overworld: If the first Pokémon in the party has this ability, any random encounter with a Pokémon five or more levels lower than it has a 50% chance of being skipped.').
ability_entry(intrepid_sword, generation_viii, true, 'Boosts Attack in battle.', 'Boosts the Pokémon’s Attack stat the first time the Pokémon enters a battle.').
ability_entry(iron_barbs, generation_v, true, 'Damages attacking Pokémon for 1/8 their max HP on contact.', 'Whenever a move makes contact with this Pokémon, the move''s user takes 1/8 of its maximum HP in damage. This ability functions identically to rough skin.').
ability_entry(iron_fist, generation_iv, true, 'Strengthens punch-based moves to 1.2× their power.', 'Moves flagged as being punch-based have 1.2× their base power for this Pokémon. sucker punch is not flagged as punch-based; its original, Japanese name only means "surprise attack".').
ability_entry(justified, generation_v, true, 'Raises Attack one stage upon taking damage from a dark move.', 'Whenever a dark-type move hits this Pokémon, its Attack rises one stage. The move is not negated in any way.').
ability_entry(keen_eye, generation_iii, true, 'Prevents accuracy from being lowered.', 'This Pokémon cannot have its accuracy lowered. This ability does not prevent any accuracy losses other than stat modifiers, such as the accuracy cut from fog; nor does it prevent other Pokémon''s evasion from making this Pokémon''s moves less accurate. This Pokémon can still be passed negative accuracy modifiers through heart swap. Overworld: If the first Pokémon in the party has this ability, any random encounter with a Pokémon five or more levels lower than it has a 50% chance of being skipped.').
ability_entry(klutz, generation_iv, true, 'Prevents the Pokémon from using its held item in battle.', 'In battle, this Pokémon cannot use its held item, nor will the item have any passive effect on the battle, positive or negative. This Pokémon also cannot use fling. The Speed cut from the iron ball and the effort items (the macho brace, power weight, power bracer, power belt, power lens, power band, and power anklet) is unaffected. Items that do not directly affect the battle, such as the exp share, the amulet coin, or the soothe bell, work as usual. All held items work as usual out of battle. Other moves that use the held item, such as natural gift and switcheroo, work as usual.').
ability_entry(leaf_guard, generation_iv, true, 'Protects against major status ailments during strong sunlight.', 'This Pokémon cannot be given a major status ailment during strong sunlight. This ability does not heal prior status ailments. rest will fail altogether with this ability in effect. yawn will immediately fail if used on this Pokémon during strong sunlight, and an already-used Yawn will fail if the weather turns to strong sunlight in the meantime.').
ability_entry(levitate, generation_iii, true, 'Evades ground moves.', 'This Pokémon is immune to ground-type moves, spikes, toxic spikes, and arena trap. This ability is disabled during gravity or ingrain, or while holding an iron ball. This ability is not disabled during roost.').
ability_entry(libero, generation_viii, true, 'Libero changes the Pokémon''s type to that of its previously used attack.', 'Changes the Pokémon’s type to the type of the move it’s about to use. This works only once each time the Pokémon enters battle.').
ability_entry(light_metal, generation_v, true, 'Halves the Pokémon''s weight.', 'This Pokémon has half the usual weight for its species.').
ability_entry(lightning_rod, generation_iii, true, 'Redirects single-target electric moves to this Pokémon where possible. Absorbs Electric moves, raising Special Attack one stage.', 'All other Pokémon''s single-target electric-type moves are redirected to this Pokémon if it is an eligible target. Other Pokémon''s Electric moves raise this Pokémon''s Special Attack one stage, negating any other effect on it, and cannot miss it. If the move''s intended target also has this ability, the move is not redirected. When multiple Pokémon with this ability are possible targets for redirection, the move is redirected to the one with the highest Speed stat, or, in the case of a tie, to a random tied Pokémon. follow me takes precedence over this ability. If the Pokémon is a ground-type and thus immune to Electric moves, its immunity prevents the Special Attack boost.').
ability_entry(limber, generation_iii, true, 'Prevents paralysis.', 'This Pokémon cannot be paralyzed. If a Pokémon is paralyzed and acquires this ability, its paralysis is healed; this includes when regaining a lost ability upon leaving battle.').
ability_entry(lingering_aroma, generation_ix, true, 'Contact changes the attacker''s Ability to Lingering Aroma.', 'Contact with the Pokémon changes the attacker’s Ability to Lingering Aroma.').
ability_entry(liquid_ooze, generation_iii, true, 'Damages opponents using leeching moves for as much as they would heal.', 'Whenever a Pokémon would heal after hitting this Pokémon with a leeching move like absorb, it instead loses as many HP as it would usually gain. dream eater is unaffected.').
ability_entry(liquid_voice, generation_vii, true, 'Sound-based moves become Water-type.', 'When this Pokémon uses a move that is sound-based, that move''s type is Water.').
ability_entry(long_reach, generation_vii, true, 'This Pokémon''s moves do not make contact.', 'A move used by this Pokémon will not make contact.').
ability_entry(magic_bounce, generation_v, true, 'Reflects most non-damaging moves back at their user.', 'When this Pokémon is targeted by a move flagged as being reflectable, the move is redirected to its user. All reflectable moves are non-damaging, and most non-damaging moves that target other Pokémon are reflectable. A move reflected by this ability or magic coat cannot be reflected back.').
ability_entry(magic_guard, generation_iv, true, 'Protects against damage not directly caused by a move.', 'This Pokémon is immune to damage not directly caused by a move. For example, this Pokémon takes no damage from from weather, recoil, status ailments, or spikes, but it still suffers from the Attack cut when burned, and a life orb will still power up this Pokémon''s moves without damaging it. Anything that directly depends on such damage will also not happen; for example, leech seed will neither hurt this Pokémon nor heal the opponent, and Pokémon with a jaboca berry or rowap berry will not consume the berry when hit by this Pokémon. The following are unaffected: struggle, pain split (whether used by or against this Pokémon), belly drum, substitute, curse, moves that knock the user out, and damage from confusion. This Pokémon will neither lose nor regain HP if it drains HP from a Pokémon with liquid ooze. If this Pokémon is badly poisoned, the poison counter is still increased each turn; if the Pokémon loses this ability, it will begin taking as much damage as it would be if it had been taking increasing damage each turn.').
ability_entry(magician, generation_vi, true, 'Steals the target''s held item when the bearer uses a damaging move.', 'Steals the target''s held item when the bearer uses a damaging move.').
ability_entry(magma_armor, generation_iii, true, 'Prevents freezing.', 'This Pokémon cannot be frozen. If a Pokémon is frozen and acquires this ability, it will immediately thaw out; this includes when regaining a lost ability upon leaving battle. Overworld: If any Pokémon in the party has this ability, each egg in the party has its hatch counter decreased by 2 (rather than 1) each step cycle, making eggs hatch roughly twice as quickly. This effect does not stack if multiple Pokémon have this ability or flame body.').
ability_entry(magnet_pull, generation_iii, true, 'Prevents steel opponents from fleeing or switching out.', 'While this Pokémon is in battle, opposing steel-type Pokémon cannot flee or switch out. Pokémon with run away can still flee. Pokémon can still switch out with the use of a move or item. Overworld: If the lead Pokémon has this ability, Steel-type Pokémon have a higher encounter rate.').
ability_entry(marvel_scale, generation_iii, true, 'Increases Defense to 1.5× with a major status ailment.', 'Whenever this Pokémon has a major status ailment, it has 1.5× its Defense. This bonus does not count as a stat modifier.').
ability_entry(mega_launcher, generation_vi, true, 'Strengthens aura and pulse moves to 1.5× their power.', 'Strengthens aura and pulse moves to 1.5× their power.').
ability_entry(merciless, generation_vii, true, 'This Pokémon''s moves critical hit against poisoned targets.', 'This Pokémon''s moves critical hit against poisoned targets.').
ability_entry(mimicry, generation_viii, true, 'Changes type depending on the terrain.', 'Changes the Pokémon’s type depending on the terrain.').
ability_entry(minds_eye, generation_ix, true, 'The Pokémon ignores changes to opponents'' evasiveness, its accuracy can''t be lowered, and it can hit Ghost types with Normal- and Fighting-type moves.', 'Mind''s Eye enables the Pokémon with this Ability to hit Ghost-type Pokémon with damage-dealing Normal- and Fighting-type moves. It also prevents other Pokémon from lowering the Pokémon''s accuracy and ignores changes to the opponents'' evasion.').
ability_entry(minus, generation_iii, true, 'Increases Special Attack to 1.5× when a friendly Pokémon has plus or minus.', 'This Pokémon has 1.5× its Special Attack if any friendly Pokémon has plus or minus. This bonus does not count as a stat modifier. If either ability is disabled by gastro acid, both lose their effect.').
ability_entry(mirror_armor, generation_viii, true, 'Reflects any stat-lowering effects.', 'Bounces back only the stat-lowering effects that the Pokémon receives.').
ability_entry(misty_surge, generation_vii, true, 'When this Pokémon enters battle, it changes the terrain to Misty Terrain.', 'When this Pokémon enters battle, it changes the terrain to misty terrain.').
ability_entry(mold_breaker, generation_iv, true, 'Bypasses targets'' abilities if they could hinder or prevent a move.', 'This Pokémon''s moves completely ignore abilities that could hinder or prevent their effect on the target. For example, this Pokémon''s moves ignore abilities that would fully negate them, such as water absorb; abilities that would prevent any of their effects, such as clear body, shell armor, or sticky hold; and abilities that grant any general protective benefit, such as simple, snow cloak, or thick fat. If an ability could either hinder or help this Pokémon''s moves, e.g. dry skin or unaware, the ability is ignored either way. Abilities that do not fit this description, even if they could hinder moves in some other way, are not affected. For example, cursed body only affects potential future uses of the move, while liquid ooze and shadow tag can only hinder a move''s effect on the user. This ablity cannot ignore type or form changes granted by abilities, for example color change or forecast; nor effects that were caused by abilities but are no longer tied to an ability, such as the rain from drizzle. This ability cannot ignore multitype at all. An ability ignored by this ability is only nullified while the move is being used. For example, this Pokémon''s moves can paralyze a Pokémon with limber, but Limber will activate and heal the paralysis immediately thereafter, and this Pokémon''s spikes are not affected by this ability after they have been placed. When this Pokémon enters battle, all participating trainers are notified that it has this ability. This ability functions identically to teravolt and turboblaze.').
ability_entry(moody, generation_v, true, 'Raises a random stat two stages and lowers another one stage after each turn.', 'After each turn, one of this Pokémon''s stats at random rises two stages, and another falls one stage. If a stat is already at 6 or -6 stages, it will not be chosen to be increased or decreased, respectively.').
ability_entry(motor_drive, generation_iv, true, 'Absorbs electric moves, raising Speed one stage.', 'Whenever an electric-type move hits this Pokémon, its Speed rises one stage, negating any other effect on it. This ability will not take effect if this Pokémon is immune to Electric moves. Electric moves will ignore this Pokémon''s substitute. This effect includes non-damaging moves, i.e. thunder wave.').
ability_entry(moxie, generation_v, true, 'Raises Attack one stage upon KOing a Pokémon.', 'This Pokémon''s Attack rises one stage upon knocking out another Pokémon, even a friendly Pokémon. This ability does not take effect when the Pokémon indirectly causes another Pokémon to faint, e.g. through poison or spikes. If this Pokémon knocks out a Pokémon with mummy, the former''s ability will change without taking effect.').
ability_entry(multiscale, generation_v, true, 'Halves damage taken from full HP.', 'This Pokémon takes half as much damage when it is hit having full HP.').
ability_entry(multitype, generation_iv, true, 'Changes arceus''s type and form to match its held Plate.', 'If this Pokémon is holding an elemental Plate, its type and form change to match the Plate. This Pokémon''s held item, whether or not it is a Plate, cannot be taken by covet or thief, nor removed by knock off, nor traded by switcheroo or trick. Covet, Thief, and Knock Off still inflict damage against this Pokémon. Unlike with sticky hold, this Pokémon cannot use fling, Switcheroo, or Trick to lose its item itself, nor gain an item through Switcheroo or Trick if it does not have one. This ability has no effect for any Pokémon other than arceus. This ability cannot be traded with skill swap, nor copied with role play or trace, nor disabled with gastro acid, nor changed with worry seed. This Pokémon cannot use Skill Swap or Role Play to lose its ability itself. mold breaker cannot ignore this ability. If a Pokémon Transforms into an Arceus with this ability, it will Transform into Arceus''s default, normal-type form. If the Transforming Pokémon is holding a Plate, this ability will then activate and change the Pokémon into the corresponding form.').
ability_entry(mummy, generation_v, true, 'Changes attacking Pokémon''s abilities to Mummy on contact.', 'Whenever a contact move hits this Pokémon, the attacking Pokémon''s ability changes to Mummy. multitype is unaffected. If a Pokémon with moxie knocks this Pokémon out, the former''s ability will change without taking effect.').
ability_entry(mycelium_might, generation_ix, true, 'Status moves go last, but are not affected by the opponent''s ability.', 'The Pokémon will always act more slowly when using status moves, but these moves will be unimpeded by the Ability of the target.').
ability_entry(natural_cure, generation_iii, true, 'Cures any major status ailment upon switching out.', 'This Pokémon is cured of any major status ailment when it is switched out for another Pokémon. If this ability is acquired during battle, the Pokémon is cured upon leaving battle before losing the temporary ability.').
ability_entry(neuroforce, generation_vii, true, 'Increases super-effective damage dealt to 1.25×.', 'Increases super-effective damage dealt to 1.25×.').
ability_entry(neutralizing_gas, generation_viii, true, 'Neutralizes abilities of all Pokémon in battle.', 'While the Pokémon is in the battle, the effects of all other Pokémon’s Abilities will be nullified or will not be triggered.').
ability_entry(no_guard, generation_iv, true, 'Ensures all moves used by and against the Pokémon hit.', 'Moves used by or against this Pokémon never miss. One-hit KO moves are unaffected. Moves affected by this ability can hit Pokémon during the preparation turn of moves like dig or fly. Overworld: If the lead Pokémon has this ability, the wild encounter rate is doubled.').
ability_entry(normalize, generation_iv, true, 'Makes the Pokémon''s moves all act normal-type.', 'This Pokémon''s moves all act as if they were normal-type. Moves that inflict typeless damage do so as usual. Moves of variable type, such as hidden power, are affected. They otherwise work as usual, however; weather ball, for example, is always forced to be Normal, but it still has doubled power and looks different during weather. As thunder wave is prevented by immunities, unlike most non-damaging moves, it does not affect ghost-type Pokémon under the effect of this ability.').
ability_entry(oblivious, generation_iii, true, 'Prevents infatuation and protects against captivate.', 'This Pokémon cannot be infatuated and is immune to captivate. If a Pokémon is infatuated and acquires this ability, its infatuation is cleared.').
ability_entry(opportunist, generation_ix, true, 'Copies stat boosts by the opponent.', 'If an opponent’s stat is boosted, the Pokémon seizes the opportunity to boost the same stat for itself.').
ability_entry(orichalcum_pulse, generation_ix, true, 'Turns the sunlight harsh when entering battle, and boosts Attack while active.', 'Turns the sunlight harsh when the Pokémon enters a battle. The ancient pulse thrumming through the Pokémon also boosts its Attack stat in harsh sunlight.').
ability_entry(overcoat, generation_v, true, 'Protects against damage from weather.', 'This Pokémon does not take damage from weather.').
ability_entry(overgrow, generation_iii, true, 'Strengthens grass moves to inflict 1.5× damage at 1/3 max HP or less.', 'When this Pokémon has 1/3 or less of its HP remaining, its grass-type moves inflict 1.5× as much regular damage.').
ability_entry(own_tempo, generation_iii, true, 'Prevents confusion.', 'This Pokémon cannot be confused. If a Pokémon is confused and acquires this ability, its confusion will immediately be healed.').
ability_entry(parental_bond, generation_vi, true, 'Lets the bearer hit twice with damaging moves. The second hit has half power.', 'Lets the bearer hit twice with damaging moves. The second hit has half power.').
ability_entry(pastel_veil, generation_viii, true, 'Prevents the Pokémon and its allies from being poisoned.', 'Prevents the Pokémon and its teammates from being poisoned. It also cures teammates of poisoning when it enters the battlefield.').
ability_entry(perish_body, generation_viii, true, 'When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle.', 'When the Pokémon with Perish Body is hit with a contact move, both the attacker and the Pokémon with Perish Body will faint in three turns.').
ability_entry(pickpocket, generation_v, true, 'Steals attacking Pokémon''s held items on contact.', 'Whenever a move makes contact with this Pokémon, if it does not have a held item, it steals the attacker''s held item. This Pokémon cannot steal upon being knocked out. It can steal if the attacker has a substitute, but cannot steal when its own Substitute is hit. If a move hits multiple times, only the last hit triggers this ability. If this Pokémon is wild, it cannot steal from a trained Pokémon.').
ability_entry(pickup, generation_iii, true, 'Picks up other Pokémon''s used and Flung held items. May also pick up an item after battle.', 'At the end of each turn, if another Pokémon consumed or Flung a held item that turn, this Pokémon picks up the item if it is not already holding one. After each battle, this Pokémon has a 10% chance of picking up an item if it is not already holding one. The air balloon and eject button cannot be picked up. The items that may be found vary by game, and, since Pokémon Emerald, by the Pokémon''s level. This ability is checked after the battle ends, at which point any temporary ability changes have worn off.').
ability_entry(pixilate, generation_vi, true, 'Turns the bearer''s normal moves into fairy moves and strengthens them to 1.3× their power.', 'Turns the bearer''s normal-type moves into fairy moves. Moves changed by this ability have 1.3× their power.').
ability_entry(plus, generation_iii, true, 'Increases Special Attack to 1.5× when a friendly Pokémon has plus or minus.', 'This Pokémon has 1.5× its Special Attack if any friendly Pokémon has plus or minus. This bonus does not count as a stat modifier. If either ability is disabled by gastro acid, both lose their effect.').
ability_entry(poison_heal, generation_iv, true, 'Heals for 1/8 max HP after each turn when poisoned in place of damage.', 'If this Pokémon is poisoned, it will heal for 1/8 of its maximum HP after each turn rather than taking damage. This includes bad poison.').
ability_entry(poison_point, generation_iii, true, 'Has a 30% chance of poisoning attacking Pokémon on contact.', 'Whenever a move makes contact with this Pokémon, the move''s user has a 30% chance of being poisoned.').
ability_entry(poison_puppeteer, generation_ix, true, 'Pokémon poisoned by Pecharunt''s moves will also become confused.', 'When a Pokémon is poisoned by any of Pecharunt''s moves, it will also become confused.').
ability_entry(poison_touch, generation_v, true, 'Has a 30% chance of poisoning target Pokémon upon contact.', 'This Pokémon''s contact moves have a 30% chance of poisoning the target with each hit. This counts as an extra effect for the purposes of shield dust. This ability takes effect before mummy.').
ability_entry(power_construct, generation_vii, true, 'Transforms 10% or 50% Zygarde into Complete Forme when its HP is below 50%.', 'Transforms 10% or 50% Zygarde into Complete Forme when its HP is below 50%. This ability cannot be copied or replaced. This ability only takes effect for Zygarde.').
ability_entry(power_of_alchemy, generation_vii, true, 'When an ally faints, this Pokémon gains its Ability.', 'When an ally faints, this Pokémon gains its Ability.').
ability_entry(power_spot, generation_viii, true, 'Just being next to the Pokémon powers up moves.', '"The power of moves used by the allies of the Pokémon with Power Spot is increased by 30%."').
ability_entry(prankster, generation_v, true, 'Raises non-damaging moves'' priority by one stage.', 'This Pokémon''s non-damaging moves have their priority increased by one stage.').
ability_entry(pressure, generation_iii, true, 'Increases the PP cost of moves targetting the Pokémon by one.', 'Moves targetting this Pokémon use one extra PP. This ability stacks if multiple targets have it. This ability still affects moves that fail or miss. This ability does not affect ally moves that target either the entire field or just its side, nor this Pokémon''s self-targetted moves; it does, however, affect single-targetted ally moves aimed at this Pokémon, ally moves that target all other Pokémon, and opponents'' moves that target the entire field. If this ability raises a move''s PP cost above its remaining PP, it will use all remaining PP. When this Pokémon enters battle, all participating trainers are notified that it has this ability. Overworld: If the lead Pokémon has this ability, higher-levelled Pokémon have their encounter rate increased.').
ability_entry(primordial_sea, generation_vi, true, 'Creates heavy rain, which has all the properties of Rain Dance, cannot be replaced, and causes damaging Fire moves to fail.', 'When this Pokémon enters battle or gains this ability, the weather becomes heavy rain. Heavy rain has all the properties of rain dance and also causes damaging Fire moves to fail. Heavy rain ends when this Pokémon leaves battle or loses this ability, or when this ability is nullified. The weather cannot otherwise be changed except by the effects of delta stream and desolate land. air lock and cloud nine will prevent the effects of heavy rain, including allowing Fire moves to work, but will not allow the weather to be changed.').
ability_entry(prism_armor, generation_vii, true, 'Reduces super-effective damage to 0.75×.', 'Super-effective damage this Pokémon takes is reduced to 0.75×. This Ability is not bypassed by mold breaker, teravolt, or turboblaze.').
ability_entry(propeller_tail, generation_viii, true, 'Ignores moves and abilities that draw in moves.', 'Ignores the effects of opposing Pokémon’s Abilities and moves that draw in moves.').
ability_entry(protean, generation_vi, true, 'Changes the bearer''s type to match each move it uses.', 'Changes the bearer''s type to match each move it uses. The type change takes place just before the move is used.').
ability_entry(protosynthesis, generation_ix, true, 'Raises highest stat in harsh sunlight, or if holding Booster Energy.', 'Boosts the Pokémon’s most proficient stat in harsh sunlight or if the Pokémon is holding Booster Energy.').
ability_entry(psychic_surge, generation_vii, true, 'When this Pokémon enters battle, it changes the terrain to Psychic Terrain.', 'When this Pokémon enters battle, it changes the terrain to psychic terrain.').
ability_entry(punk_rock, generation_viii, true, 'Boosts sound-based moves and halves damage from the same moves.', 'Boosts the power of sound-based moves. The Pokémon also takes half the damage from these kinds of moves.').
ability_entry(pure_power, generation_iii, true, 'Doubles Attack in battle.', 'This Pokémon''s Attack is doubled in battle. This bonus does not count as a stat modifier. This ability functions identically to huge power.').
ability_entry(purifying_salt, generation_ix, true, 'Protects from status conditions and halves damage from Ghost-type moves.', 'The Pokémon’s pure salt protects it from status conditions and halves the damage taken from Ghost-type moves.').
ability_entry(quark_drive, generation_ix, true, 'Raises highest stat on Electric Terrain, or if holding Booster Energy.', 'Boosts the Pokémon’s most proficient stat on Electric Terrain or if the Pokémon is holding Booster Energy.').
ability_entry(queenly_majesty, generation_vii, true, 'Opposing Pokémon cannot use priority attacks.', 'When an opposing Pokémon attempts to use a move that targets this Pokémon or an ally, and that move has priority, it will fail.').
ability_entry(quick_draw, generation_viii, true, 'Enables the Pokémon to move first occasionally.', 'If a Pokémon with this Ability selects a damaging move, it has a 30% chance of going first in its priority bracket.').
ability_entry(quick_feet, generation_iv, true, 'Increases Speed to 1.5× with a major status ailment.', 'Whenever this Pokémon has a major status ailment, it has 1.5× its Speed. This Pokémon is not affected by the usual Speed cut from paralysis. Overworld: If the lead Pokémon has this ability, the wild encounter rate is halved.').
ability_entry(rain_dish, generation_iii, true, 'Heals for 1/16 max HP after each turn during rain.', 'This Pokémon heals for 1/16 of its maximum HP after each turn during rain.').
ability_entry(rattled, generation_v, true, 'Raises Speed one stage upon being hit by a dark, ghost, or bug move.', 'This Pokémon''s Speed rises one stage with each hit from a damaging dark-, ghost-, or bug-type move.').
ability_entry(receiver, generation_vii, true, 'When an ally faints, this Pokémon gains its Ability.', 'When an ally faints, this Pokémon gains its Ability.').
ability_entry(reckless, generation_iv, true, 'Strengthens recoil moves to 1.2× their power.', 'This Pokémon''s recoil moves and crash moves have 1.2× their base power. struggle is unaffected. The "crash moves" are the moves that damage the user upon missing: jump kick and high jump kick.').
ability_entry(refrigerate, generation_vi, true, 'Turns the bearer''s normal moves into ice moves and strengthens them to 1.3× their power.', 'Turns the bearer''s normal-type moves into ice-type moves. Moves changed by this ability have 1.3× their power.').
ability_entry(regenerator, generation_v, true, 'Heals for 1/3 max HP upon switching out.', 'This Pokémon regains 1/3 of its maximum HP when it is switched out for another Pokémon under any circumstances other than having fainted. This ability does not take effect when a battle ends.').
ability_entry(ripen, generation_viii, true, 'Doubles the effect of berries.', 'Ripens Berries and doubles their effect.').
ability_entry(rivalry, generation_iv, true, 'Increases damage inflicted to 1.25× against Pokémon of the same gender, but decreases damage to 0.75× against the opposite gender.', 'This Pokémon inflicts 1.25× as much regular damage against Pokémon of the same gender and 0.75× as much regular damage against Pokémon of the opposite gender. If either Pokémon is genderless, damage is unaffected.').
ability_entry(rks_system, generation_vii, true, 'Changes this Pokémon''s type to match its held Memory.', 'Changes this Pokémon''s type to match its held Memory. This ability cannot be copied, replaced, or nullified. This ability only takes effect for Silvally.').
ability_entry(rock_head, generation_iii, true, 'Protects against recoil damage.', 'This Pokémon does not receive recoil damage from its recoil moves. struggle''s recoil is unaffected. This ability does not prevent crash damage from missing with jump kick or high jump kick.').
ability_entry(rocky_payload, generation_ix, true, 'Powers up Rock-type moves.', 'Increases the power of Rock-type moves used by this Pokémon by 50%.').
ability_entry(rough_skin, generation_iii, true, 'Damages attacking Pokémon for 1/8 their max HP on contact.', 'Whenever a move makes contact with this Pokémon, the move''s user takes 1/8 of its maximum HP in damage. This ability functions identically to iron barbs.').
ability_entry(run_away, generation_iii, true, 'Ensures success fleeing from wild battles.', 'This Pokémon is always successful fleeing from wild battles, even if trapped by a move or ability.').
ability_entry(sand_force, generation_v, true, 'Strengthens rock, ground, and steel moves to 1.3× their power during a sandstorm. Protects against sandstorm damage.', 'During a sandstorm, this Pokémon''s rock-, ground-, and steel-type moves have 1.3× their base power. This Pokémon does not take sandstorm damage, regardless of type.').
ability_entry(sand_rush, generation_v, true, 'Doubles Speed during a sandstorm. Protects against sandstorm damage.', 'This Pokémon''s Speed is doubled during a sandstorm, and it does not take sandstorm damage, regardless of type.').
ability_entry(sand_spit, generation_viii, true, 'Creates a sandstorm when hit by an attack.', 'The Pokémon creates a sandstorm when it’s hit by an attack.').
ability_entry(sand_stream, generation_iii, true, 'Summons a sandstorm that lasts indefinitely upon entering battle.', 'The weather changes to a sandstorm when this Pokémon enters battle and does not end unless cancelled by another weather condition. If multiple Pokémon with this ability, drizzle, drought, or snow warning are sent out at the same time, the abilities will activate in order of Speed, respecting trick room. Each ability''s weather will cancel the previous weather, and only the weather summoned by the slowest of the Pokémon will stay. Overworld: If the lead Pokémon has this ability, the wild encounter rate is halved in a sandstorm.').
ability_entry(sand_veil, generation_iii, true, 'Increases evasion to 1.25× during a sandstorm. Protects against sandstorm damage.', 'During a sandstorm, this Pokémon has 1.25× its evasion, and it does not take sandstorm damage regardless of type. The evasion bonus does not count as a stat modifier. Overworld: If the lead Pokémon has this ability, the wild encounter rate is halved in a sandstorm.').
ability_entry(sap_sipper, generation_v, true, 'Absorbs grass moves, raising Attack one stage.', 'Whenever a grass-type move hits this Pokémon, its Attack rises one stage, negating any other effect on it.').
ability_entry(schooling, generation_vii, true, 'Wishiwashi becomes Schooling Form when its HP is 25% or higher.', 'If this Pokémon is a wishiwashi and level 20 or above, then when it enters battle and at the start of each turn, it becomes Schooling Form if its HP is 25% or higher and Solo Form otherwise. This ability cannot be replaced, copied, or nullified.').
ability_entry(scrappy, generation_iv, true, 'Lets the Pokémon''s normal and fighting moves hit ghost Pokémon.', 'This Pokémon ignores ghost-type Pokémon''s immunity to normal- and fighting-type moves. Ghost Pokémon''s other types affect damage as usual.').
ability_entry(screen_cleaner, generation_viii, true, 'Nullifies effects of Light Screen, Reflect, and Aurora Veil.', 'When the Pokémon enters a battle, the effects of Light Screen, Reflect, and Aurora Veil are nullified for both opposing and ally Pokémon.').
ability_entry(seed_sower, generation_ix, true, 'Turns the ground into Grassy Terrain when the Pokémon is hit by an attack.', 'Turns the ground into Grassy Terrain when the Pokémon is hit by an attack.').
ability_entry(serene_grace, generation_iii, true, 'Doubles the chance of moves'' extra effects occurring.', 'This Pokémon''s moves have twice their usual effect chance. An effect chance is a move''s chance to inflict a status ailment, cause a stat change, or make the target flinch in addition to the move''s main effect. For example, flamethrower''s chance of burning the target is doubled, but protect''s chance of success and air cutter''s increased critical hit rate are unaffected. secret power is unaffected.').
ability_entry(shadow_shield, generation_vii, true, 'When this Pokémon has full HP, regular damage from moves is halved.', 'When this Pokémon has full HP, regular damage (not fixed damage!) from moves is halved. This ability cannot be nullified.').
ability_entry(shadow_tag, generation_iii, true, 'Prevents opponents from fleeing or switching out.', 'While this Pokémon is in battle, opposing Pokémon cannot flee or switch out. Other Pokémon with this ability are unaffected. Pokémon with run away can still flee. Pokémon can still switch out with the use of a move or item.').
ability_entry(sharpness, generation_ix, true, 'Powers up slicing moves.', 'Increases the power of all ''slicing'' moves by 50%.').
ability_entry(shed_skin, generation_iii, true, 'Has a 33% chance of curing any major status ailment after each turn.', 'After each turn, this Pokémon has a 33% of being cured of any major status ailment.').
ability_entry(sheer_force, generation_v, true, 'Strengthens moves with extra effects to 1.3× their power, but prevents their extra effects.', 'This Pokémon''s moves with extra effects have 1.3× their power, but lose their extra effects. An effect chance is a move''s chance to inflict a status ailment, cause a stat change, or make the target flinch in addition to the move''s main effect. For example, thunder shock''s paralysis is an extra effect, but thunder wave''s is not, nor are knock off''s item removal and air cutter''s increased critical hit rate. Moves that lower the user''s stats are unaffected.').
ability_entry(shell_armor, generation_iii, true, 'Protects against critical hits.', 'Moves cannot score critical hits against this Pokémon. This ability functions identically to battle armor.').
ability_entry(shield_dust, generation_iii, true, 'Protects against incoming moves'' extra effects.', 'This Pokémon is immune to the extra effects of moves used against it. An extra effect is a move''s chance, listed as an "effect chance", to inflict a status ailment, cause a stat change, or make the target flinch in addition to the move''s main effect. For example, thunder shock''s paralysis is an extra effect, but thunder wave''s is not, nor are knock off''s item removal and air cutter''s increased critical hit rate.').
ability_entry(shields_down, generation_vii, true, 'Transforms this Minior between Core Form and Meteor Form. Prevents major status ailments and drowsiness while in Meteor Form.', 'When this Pokémon enters battle and at the end of each turn, if its HP is 50% or above, it changes into Meteor Form; otherwise, it changes into Core Form. In Meteor Form, it cannot be given a major status ailment (though existing ones are not cured), cannot become drowsy from yawn, and cannot use rest (which will simply fail). This ability cannot be copied, replaced, or nullified. This ability only takes effect for Minior.').
ability_entry(simple, generation_iv, true, 'Doubles the Pokémon''s stat modifiers. These doubled modifiers are still capped at -6 or 6 stages.', 'Each stage of this Pokémon''s stat modifiers acts as two stages. These doubled stages are still limited to a minimum of -6 and a maximum of 6. This Pokémon can still accumulate less than -3 or more than 3 stages of stat modifiers, even though the extra ones have no effect after doubling.').
ability_entry(skill_link, generation_iv, true, 'Extends two-to-five-hit moves and triple kick to their full length every time.', 'This Pokémon always hits five times with two-to-five-hit moves, such as icicle spear. It also bypasses the accuracy checks on triple kick''s second and third hits.').
ability_entry(slow_start, generation_iv, true, 'Halves Attack and Speed for five turns upon entering battle.', 'This Pokémon''s Attack and Speed are halved for five turns upon entering battle. This ability also takes effect when acquired during battle. If this Pokémon loses its ability before the five turns are up, its Attack and Speed return to normal; if it then regains this ability without leaving battle, its Attack and Speed are halved again, but the counter keeps counting from where it was.').
ability_entry(slush_rush, generation_vii, true, 'During Hail, this Pokémon has double Speed.', 'During Hail, this Pokémon has double Speed.').
ability_entry(sniper, generation_iv, true, 'Strengthens critical hits to inflict 3× damage rather than 2×.', 'This Pokémon inflicts triple damage with critical hits, rather than the usual double damage.').
ability_entry(snow_cloak, generation_iv, true, 'Increases evasion to 1.25× during hail. Protects against hail damage.', 'During hail, this Pokémon has 1.25× its evasion, and it does not take hail damage regardless of type. The evasion bonus does not count as a stat modifier. Overworld: If the lead Pokémon has this ability, the wild encounter rate is halved in snow.').
ability_entry(snow_warning, generation_iv, true, 'Summons hail that lasts indefinitely upon entering battle.', 'The weather changes to hail when this Pokémon enters battle and does not end unless cancelled by another weather condition. If multiple Pokémon with this ability, drizzle, drought, or sand stream are sent out at the same time, the abilities will activate in order of Speed, respecting trick room. Each ability''s weather will cancel the previous weather, and only the weather summoned by the slowest of the Pokémon will stay.').
ability_entry(solar_power, generation_iv, true, 'Increases Special Attack to 1.5× but costs 1/8 max HP after each turn during strong sunlight.', 'During strong sunlight, this Pokémon has 1.5× its Special Attack but takes 1/8 of its maximum HP in damage after each turn.').
ability_entry(solid_rock, generation_iv, true, 'Decreases damage taken from super-effective moves by 1/4.', 'This Pokémon takes 0.75× as much damage from moves that are super effective against it. This ability functions identically to filter.').
ability_entry(soul_heart, generation_vii, true, 'This Pokémon''s Special Attack rises by one stage every time any Pokémon faints.', 'This Pokémon''s Special Attack rises by one stage every time any Pokémon faints.').
ability_entry(soundproof, generation_iii, true, 'Protects against sound-based moves.', 'This Pokémon is immune to moves flagged as being sound-based. heal bell is unaffected. uproar still prevents this Pokémon from sleeping. This Pokémon can still receive a Perish Song counter through baton pass, and will retain a Perish Song counter if it acquires this ability after Perish Song is used. howl, roar of time, sonic boom, and yawn are not flagged as sound-based.').
ability_entry(speed_boost, generation_iii, true, 'Raises Speed one stage after each turn.', 'This Pokémon''s Speed rises one stage after each turn.').
ability_entry(stakeout, generation_vii, true, 'This Pokémon''s moves have double power against Pokémon that switched in this turn.', 'This Pokémon''s moves have double power against Pokémon that switched in this turn.').
ability_entry(stall, generation_iv, true, 'Makes the Pokémon move last within its move''s priority bracket.', 'This Pokémon moves last within its priority bracket. Multiple Pokémon with this ability move in order of Speed amongst themselves. The full incense and lagging tail take precedence over this ability; that is, Pokémon with these items move after Pokémon with this ability. Pokémon with both this ability and one of these items are delayed as much as if they had only the item. This ability works as usual during trick room: Pokémon with this ability will move in reverse order of Speed after Pokémon without it.').
ability_entry(stalwart, generation_viii, true, 'Ignores moves and abilities that draw in moves.', 'Ignores the effects of opposing Pokémon’s Abilities and moves that draw in moves.').
ability_entry(stamina, generation_vii, true, 'Raises this Pokémon''s Defense by one stage when it takes damage from a move.', 'Raises this Pokémon''s Defense by one stage when it takes damage from a move.').
ability_entry(stance_change, generation_vi, true, 'Changes aegislash to Blade Forme before using a damaging move, or Shield Forme before using kings shield.', 'Changes aegislash to Blade Forme before using a damaging move, or Shield Forme before using kings shield.').
ability_entry(static, generation_iii, true, 'Has a 30% chance of paralyzing attacking Pokémon on contact.', 'Whenever a move makes contact with this Pokémon, the move''s user has a 30% chance of being paralyzed. Pokémon that are immune to electric-type moves can still be paralyzed by this ability. Overworld: If the lead Pokémon has this ability, there is a 50% chance that encounters will be with an electric Pokémon, if applicable.').
ability_entry(steadfast, generation_iv, true, 'Raises Speed one stage upon flinching.', 'Whenever this Pokémon flinches, its Speed rises one stage.').
ability_entry(steam_engine, generation_viii, true, 'Boosts the Speed stat drastically when the Pokémon is hit by a Fire- or Water-type move.', 'Raises the user''s Speed by three stages when it is hit by a Fire- or Water-type attack. The attack still deals damage.').
ability_entry(steelworker, generation_vii, true, 'This Pokémon''s Steel moves have 1.5× power.', 'This Pokémon''s Steel moves have 1.5× power.').
ability_entry(steely_spirit, generation_viii, true, 'Powers up ally Pokémon''s Steel-type moves.', 'Powers up the Steel-type moves of the Pokémon and its allies.').
ability_entry(stench, generation_iii, true, 'Has a 10% chance of making target Pokémon flinch with each hit.', 'This Pokémon''s damaging moves have a 10% chance to make the target flinch with each hit if they do not already cause flinching as a secondary effect. This ability does not stack with a held item. Overworld: The wild encounter rate is halved while this Pokémon is first in the party.').
ability_entry(sticky_hold, generation_iii, true, 'Prevents a held item from being removed by other Pokémon.', 'This Pokémon''s hold item cannot be removed by other Pokémon. Damaging moves that would remove this Pokémon''s item can still inflict damage against this Pokémon, e.g. knock off or pluck. This Pokémon can still use moves that involve the loss of its own item, e.g. fling or trick. Overworld: If the lead Pokémon has this ability, the encounter rate while fishing is increased.').
ability_entry(storm_drain, generation_iv, true, 'Redirects single-target water moves to this Pokémon where possible. Absorbs Water moves, raising Special Attack one stage.', 'All other Pokémon''s single-target water-type moves are redirected to this Pokémon, if it is an eligible target. Other Pokémon''s Water moves raise this Pokémon''s Special Attack one stage, negating any other effect on it, and cannot miss it. If the move''s intended target also has this ability, the move is not redirected. When multiple Pokémon with this ability are possible targets for redirection, the move is redirected to the one with the highest Speed stat, or, in the case of a tie, to a random tied Pokémon. follow me takes precedence over this ability.').
ability_entry(strong_jaw, generation_vi, true, 'Strengthens biting moves to 1.5× their power.', 'Strengthens biting moves to 1.5× their power.').
ability_entry(sturdy, generation_iii, true, 'Prevents being KOed from full HP, leaving 1 HP instead. Protects against the one-hit KO moves regardless of HP.', 'When this Pokémon is at full HP, any hit that would knock it out will instead leave it with 1 HP. Regardless of its current HP, it is also immune to the one-hit KO moves: fissure, guillotine, horn drill, and sheer cold. If this Pokémon is holding a focus sash, this ability takes precedence and the item will not be consumed.').
ability_entry(suction_cups, generation_iii, true, 'Prevents being forced out of battle by other Pokémon''s moves.', 'This Pokémon cannot be forced out of battle by moves such as whirlwind. dragon tail and circle throw still inflict damage against this Pokémon. Overworld: If the lead Pokémon has this ability, the success rate while fishing is increased.').
ability_entry(super_luck, generation_iv, true, 'Raises moves'' critical hit rates one stage.', 'This Pokémon''s moves have critical hit rates one stage higher than normal.').
ability_entry(supersweet_syrup, generation_ix, true, 'Once per battle, when a Pokémon with Supersweet Syrup enters the battle, it lowers the evasion stat of all adjacent opponents by one stage.', 'A sickly sweet scent spreads across the field the first time the Pokémon enters a battle, lowering the evasiveness of opposing Pokémon.').
ability_entry(supreme_overlord, generation_ix, true, 'Attack and Special Attack are boosted for each party Pokémon that has been defeated.', 'When the Pokémon enters a battle, its Attack and Sp. Atk stats are slightly boosted for each of the allies in its party that have already been defeated.').
ability_entry(surge_surfer, generation_vii, true, 'Doubles this Pokémon''s Speed on Electric Terrain.', 'Doubles this Pokémon''s Speed on Electric Terrain.').
ability_entry(swarm, generation_iii, true, 'Strengthens bug moves to inflict 1.5× damage at 1/3 max HP or less.', 'When this Pokémon has 1/3 or less of its HP remaining, its bug-type moves inflict 1.5× as much regular damage. Overworld: If the lead Pokémon has this ability, the wild encounter rate is increased.').
ability_entry(sweet_veil, generation_vi, true, 'Prevents friendly Pokémon from sleeping.', 'Prevents friendly Pokémon from sleeping.').
ability_entry(swift_swim, generation_iii, true, 'Doubles Speed during rain.', 'This Pokémon''s Speed is doubled during rain. This bonus does not count as a stat modifier.').
ability_entry(sword_of_ruin, generation_ix, true, 'Lowers Defense of all Pokémon except itself.', 'The power of the Pokémon’s ruinous sword lowers the Defense stats of all Pokémon except itself.').
ability_entry(symbiosis, generation_vi, true, 'Passes the bearer''s held item to an ally when the ally uses up its item.', 'Passes the bearer''s held item to an ally when the ally uses up its item.').
ability_entry(synchronize, generation_iii, true, 'Copies burns, paralysis, and poison received onto the Pokémon that inflicted them.', 'Whenever this Pokémon is burned, paralyzed, or poisoned, the Pokémon who gave this Pokémon that ailment is also given the ailment. This ability passes back bad poison when this Pokémon is badly poisoned. This ability cannot pass on a status ailment that the Pokémon did not directly receive from another Pokémon, such as the poison from toxic spikes or the burn from a flame orb. Overworld: If the lead Pokémon has this ability, wild Pokémon have a 50% chance of having the lead Pokémon''s nature, and a 50% chance of being given a random nature as usual, including the lead Pokémon''s nature. This does not work on Pokémon received outside of battle or roaming legendaries.').
ability_entry(tablets_of_ruin, generation_ix, true, 'Lowers Attack of all Pokémon except itself.', 'The power of the Pokémon’s ruinous wooden tablets lowers the Attack stats of all Pokémon except itself.').
ability_entry(tangled_feet, generation_iv, true, 'Doubles evasion when confused.', 'When this Pokémon is confused, it has twice its evasion.').
ability_entry(tangling_hair, generation_vii, true, 'When this Pokémon takes regular damage from a contact move, the attacking Pokémon''s Speed lowers by one stage.', 'When this Pokémon takes regular damage from a contact move, the attacking Pokémon''s Speed lowers by one stage.').
ability_entry(technician, generation_iv, true, 'Strengthens moves of 60 base power or less to 1.5× their power.', 'This Pokémon''s moves have 1.5× their power if their base power is 60 or less. This includes moves of variable power, such as hidden power and magnitude, when their power is 60 or less. helping hand''s power boost is taken into account for any move, as is defense curl''s power boost for rollout.').
ability_entry(telepathy, generation_v, true, 'Protects against friendly Pokémon''s damaging moves.', 'This Pokémon does not take damage from friendly Pokémon''s moves, including single-target moves aimed at it.').
ability_entry(tera_shell, generation_ix, true, 'All damage-dealing moves that hit the Pokémon when its HP is full will not be very effective.', 'The Pokémon’s shell contains the powers of each type. All damage-dealing moves that hit the Pokémon when its HP is full will not be very effective.').
ability_entry(tera_shift, generation_ix, true, 'When Terapagos enters the battle, it turns into its Terastal Form until the end of the battle.', 'When the Pokémon enters a battle, it absorbs the energy around itself and transforms into its Terastal Form.').
ability_entry(teraform_zero, generation_ix, true, 'As soon as Terapagos assumes its Stellar Form, it will immediately neutralize weather and terrain effects.', 'When Terapagos changes into its Stellar Form, it uses its hidden powers to eliminate all effects of weather and terrain, reducing them to zero.').
ability_entry(teravolt, generation_v, true, 'Bypasses targets'' abilities if they could hinder or prevent moves.', 'This Pokémon''s moves completely ignore abilities that could hinder or prevent their effect on the target. For example, this Pokémon''s moves ignore abilities that would fully negate them, such as water absorb; abilities that would prevent any of their effects, such as clear body, shell armor, or sticky hold; and abilities that grant any general protective benefit, such as simple, snow cloak, or thick fat. If an ability could either hinder or help this Pokémon''s moves, e.g. dry skin or unaware, the ability is ignored either way. Abilities that do not fit this description, even if they could hinder moves in some other way, are not affected. For example, cursed body only affects potential future uses of the move, while liquid ooze and shadow tag can only hinder a move''s effect on the user. This ablity cannot ignore type or form changes granted by abilities, for example color change or forecast; nor effects that were caused by abilities but are no longer tied to an ability, such as the rain from drizzle. This ability cannot ignore multitype at all. An ability ignored by this ability is only nullified while the move is being used. For example, this Pokémon''s moves can paralyze a Pokémon with limber, but Limber will activate and heal the paralysis immediately thereafter, and this Pokémon''s spikes are not affected by this ability after they have been placed. When this Pokémon enters battle, all participating trainers are notified that it has this ability. This ability functions identically to mold breaker and turboblaze.').
ability_entry(thermal_exchange, generation_ix, true, 'Raises Attack when hit by a Fire-type move. Cannot be burned.', 'Boosts the Attack stat when the Pokémon is hit by a Fire-type move. The Pokémon also cannot be burned.').
ability_entry(thick_fat, generation_iii, true, 'Halves damage from fire and ice moves.', 'This Pokémon takes half as much damage from fire- and ice-type moves.').
ability_entry(tinted_lens, generation_iv, true, 'Doubles damage inflicted with not-very-effective moves.', 'This Pokémon deals twice as much damage with moves that are not very effective against the target.').
ability_entry(torrent, generation_iii, true, 'Strengthens water moves to inflict 1.5× damage at 1/3 max HP or less.', 'When this Pokémon has 1/3 or less of its HP remaining, its water-type moves inflict 1.5× as much regular damage.').
ability_entry(tough_claws, generation_vi, true, 'Strengthens moves that make contact to 1.33× their power.', 'Strengthens moves that make contact to 1.33× their power.').
ability_entry(toxic_boost, generation_v, true, 'Increases Attack to 1.5× when poisoned.', 'This Pokémon has 1.5× its Attack when poisoned.').
ability_entry(toxic_chain, generation_ix, true, 'May cause bad poisoning when the Pokémon hits an opponent with a move.', 'The power of the Pokémon''s toxic chain may badly poison any target the Pokémon hits with a move.').
ability_entry(toxic_debris, generation_ix, true, 'Scatters poison spikes at the feet of the opposing team when the Pokémon takes damage from physical moves.', 'Scatters poison spikes at the feet of the opposing team when the Pokémon takes damage from physical moves.').
ability_entry(trace, generation_iii, true, 'Copies an opponent''s ability upon entering battle.', 'When this Pokémon enters battle, it copies a random opponent''s ability. This ability cannot copy flower gift, forecast, illusion, imposter, multitype, trace, wonder guard, or zen mode.').
ability_entry(transistor, generation_viii, true, 'Powers up Electric-type moves.', 'Increases the power of Electric-type moves used by this Pokémon by 50%.').
ability_entry(triage, generation_vii, true, 'This Pokémon''s healing moves have their priority increased by 3.', 'This Pokémon''s healing moves have their priority increased by 3.').
ability_entry(truant, generation_iii, true, 'Skips every second turn.', 'Every second turn on which this Pokémon should attempt to use a move, it will instead do nothing ("loaf around"). Loafing around interrupts moves that take multiple turns the same way paralysis, flinching, etc do. Most such moves, for example bide or rollout, are simply cut off upon loafing around. Attacks with a recharge turn, such as hyper beam, do not have to recharge; attacks with a preparation turn, such as fly, do not end up being used. Moves that are forced over multiple turns and keep going through failure, such as outrage, uproar, or any move forced by encore, keep going as usual. If this Pokémon is confused, its confusion is not checked when loafing around; the Pokémon cannot hurt itself, and its confusion does not end or come closer to ending. If this Pokémon attempts to move but fails, e.g. because of paralysis or gravity, it still counts as having moved and will loaf around the next turn. If it does not attempt to move, e.g. because it is asleep or frozen, whatever it would have done will be postponed until its next attempt; that is, it will either loaf around or move as usual, depending on what it last did. This ability cannot be changed with worry seed, but it can be disabled with gastro acid, changed with role play, or traded away with skill swap.').
ability_entry(turboblaze, generation_v, true, 'Bypasses targets'' abilities if they could hinder or prevent moves.', 'This Pokémon''s moves completely ignore abilities that could hinder or prevent their effect on the target. For example, this Pokémon''s moves ignore abilities that would fully negate them, such as water absorb; abilities that would prevent any of their effects, such as clear body, shell armor, or sticky hold; and abilities that grant any general protective benefit, such as simple, snow cloak, or thick fat. If an ability could either hinder or help this Pokémon''s moves, e.g. dry skin or unaware, the ability is ignored either way. Abilities that do not fit this description, even if they could hinder moves in some other way, are not affected. For example, cursed body only affects potential future uses of the move, while liquid ooze and shadow tag can only hinder a move''s effect on the user. This ablity cannot ignore type or form changes granted by abilities, for example color change or forecast; nor effects that were caused by abilities but are no longer tied to an ability, such as the rain from drizzle. This ability cannot ignore multitype at all. An ability ignored by this ability is only nullified while the move is being used. For example, this Pokémon''s moves can paralyze a Pokémon with limber, but Limber will activate and heal the paralysis immediately thereafter, and this Pokémon''s spikes are not affected by this ability after they have been placed. When this Pokémon enters battle, all participating trainers are notified that it has this ability. This ability functions identically to mold breaker and teravolt.').
ability_entry(unaware, generation_iv, true, 'Ignores other Pokémon''s stat modifiers for damage and accuracy calculation.', 'This Pokémon ignores other Pokémon''s stat modifiers for the purposes of damage and accuracy calculation. Effectively, this affects modifiers of every stat except Speed. The power of punishment and stored power is calculated as usual. When this Pokémon hurts itself in confusion, its stat modifiers affect damage as usual.').
ability_entry(unburden, generation_iv, true, 'Doubles Speed upon using or losing a held item.', 'When this Pokémon uses or loses its held item, its Speed is doubled. If it gains another item or leaves battle, this bonus is lost. This includes when the Pokémon drops its item because of knock off. This bonus does not count as a stat modifier. There is no notification when this ability takes effect.').
ability_entry(unnerve, generation_v, true, 'Prevents opposing Pokémon from eating held Berries.', 'Opposing Pokémon cannot eat held Berries while this Pokémon is in battle. Affected Pokémon can still use bug bite or pluck to eat a target''s Berry.').
ability_entry(unseen_fist, generation_viii, true, 'Contact moves can strike through Protect/Detect.', 'If the Pokémon uses moves that make direct contact, it can attack the target even if the target protects itself.').
ability_entry(vessel_of_ruin, generation_ix, true, 'Lowers Special Attack of all Pokémon except itself.', 'The power of the Pokémon’s ruinous vessel lowers the Sp. Atk stats of all Pokémon except itself.').
ability_entry(victory_star, generation_v, true, 'Increases moves'' accuracy to 1.1× for friendly Pokémon.', 'All friendly Pokémon''s moves, including this Pokémon''s own moves, have 1.1× their usual accuracy while this Pokémon is in battle.').
ability_entry(vital_spirit, generation_iii, true, 'Prevents sleep.', 'This Pokémon cannot be asleep. This causes rest to fail altogether. If a Pokémon is asleep and acquires this ability, it will immediately wake up; this includes when regaining a lost ability upon leaving battle. This ability functions identically to insomnia in battle. Overworld: If the lead Pokémon has this ability, higher-levelled Pokémon have their encounter rate increased.').
ability_entry(volt_absorb, generation_iii, true, 'Absorbs electric moves, healing for 1/4 max HP.', 'Whenever an electric-type move hits this Pokémon, it heals for 1/4 of its maximum HP, negating any other effect on it. This ability will not take effect if this Pokémon is ground-type and thus immune to Electric moves. Electric moves will ignore this Pokémon''s substitute. This effect includes non-damaging moves, i.e. thunder wave.').
ability_entry(wandering_spirit, generation_viii, true, 'Swaps abilities with opponents on contact.', 'The Pokémon exchanges Abilities with a Pokémon that hits it with a move that makes direct contact.').
ability_entry(water_absorb, generation_iii, true, 'Absorbs water moves, healing for 1/4 max HP.', 'Whenever a water-type move hits this Pokémon, it heals for 1/4 of its maximum HP, negating any other effect on it. Water moves will ignore this Pokémon''s substitute.').
ability_entry(water_bubble, generation_vii, true, 'Halves damage from Fire moves, doubles damage of Water moves, and prevents burns.', 'When this Pokémon is hit by a Fire move, the damage is halved. When this Pokémon uses a Water move, the power is doubled. This Pokémon cannot be burned, and if it becomes burned, the burn is immediately cured.').
ability_entry(water_compaction, generation_vii, true, 'Raises this Pokémon''s Defense by two stages when it''s hit by a Water move.', 'Raises this Pokémon''s Defense by two stages when it''s hit by a Water move.').
ability_entry(water_veil, generation_iii, true, 'Prevents burns.', 'This Pokémon cannot be burned. If a Pokémon is burned and acquires this ability, its burn is healed; this includes when regaining a lost ability upon leaving battle.').
ability_entry(weak_armor, generation_v, true, 'Raises Speed and lowers Defense by one stage each upon being hit by a physical move.', 'Whenever a physical move hits this Pokémon, its Speed rises one stage and its Defense falls one stage. This ability triggers on every hit of a multiple-hit move.').
ability_entry(well_baked_body, generation_ix, true, 'Immune to Fire-type moves, and Defense is sharply boosted.', 'The Pokémon takes no damage when hit by Fire-type moves. Instead, its Defense stat is sharply boosted.').
ability_entry(white_smoke, generation_iii, true, 'Prevents stats from being lowered by other Pokémon.', 'This Pokémon cannot have its stats lowered by other Pokémon. This ability does not prevent any stat losses other than stat modifiers, such as the Speed cut from paralysis; nor self-inflicted stat drops, such as the Special Attack drop from overheat; nor opponent-triggered stat boosts, such as the Attack boost from swagger. This Pokémon can still be passed negative stat modifiers through guard swap, heart swap, or power swap. This ability functions identically to clear body in battle. Overworld: If the lead Pokémon has this ability, the wild encounter rate is halved.').
ability_entry(wimp_out, generation_vii, true, 'This Pokémon automatically switches out when its HP drops below half.', 'After this Pokémon is hit by a move, if that move caused this Pokémon''s HP to drop below half, it switches out.').
ability_entry(wind_power, generation_ix, true, 'When hit by a wind move, the power of the next Electric-type move it uses is doubled.', 'The Pokémon becomes charged when it is hit by a wind move, boosting the power of the next Electric-type move the Pokémon uses.').
ability_entry(wind_rider, generation_ix, true, 'Gives immunity to wind moves, and causes the Pokémon''s Attack to increase by one stage when hit by one.', 'Boosts the Pokémon’s Attack stat if Tailwind takes effect or if the Pokémon is hit by a wind move. The Pokémon also takes no damage from wind moves.').
ability_entry(wonder_guard, generation_iii, true, 'Protects against damaging moves that are not super effective.', 'This Pokémon is immune to damaging moves that are not super effective against it. Moves that inflict fixed damage, such as night shade or seismic toss, are considered super effective if their types are. Damage not directly dealt by moves, such as damage from weather, a status ailment, or spikes, is not prevented. This ability cannot be copied with role play or traded away with skill swap, but it can be copied with trace, disabled with gastro acid, or changed with worry seed. This Pokémon can still use Role Play itself to lose this ability, but not Skill Swap. If this Pokémon has a substitute, this ability will block moves as usual and any moves not blocked will react to the Substitute as usual.').
ability_entry(wonder_skin, generation_v, true, 'Lowers incoming non-damaging moves'' base accuracy to exactly 50%.', 'Non-damaging moves have exactly 50% base accuracy against this Pokémon.').
ability_entry(zen_mode, generation_v, true, 'Changes darmanitan''s form after each turn depending on its HP: Zen Mode below 50% max HP, and Standard Mode otherwise.', 'This Pokémon switches between Standard Mode and Zen Mode after each turn depending on its HP. Below 50% of its maximum HP, it switches to Zen Mode, and at 50% or above, it switches to Standard Mode. This Pokémon returns to Standard Mode upon leaving battle or losing this ability. This ability has no effect if this Pokémon is not a darmanitan.').
ability_entry(zero_to_hero, generation_ix, true, 'Transforms into its Hero Form when switching out.', 'The Pokémon transforms into its Hero Form when it switches out.').
