:- encoding(utf8).
% Lore local da geracao 8
% Formato: pokemon_lore(ID, Texto).
:- multifile pokemon_lore/2.
pokemon_lore(810, 'Grookey é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(811, 'Thwackey é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Grookey.').
pokemon_lore(812, 'Rillaboom é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Thwackey.').
pokemon_lore(813, 'Scorbunny é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(814, 'Raboot é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Scorbunny.').
pokemon_lore(815, 'Cinderace é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Raboot.').
pokemon_lore(816, 'Sobble é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(817, 'Drizzile é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sobble.').
pokemon_lore(818, 'Inteleon é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Drizzile.').
pokemon_lore(819, 'Skwovet é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(820, 'Greedent é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Skwovet.').
pokemon_lore(821, 'Rookidee é um Pokémon do tipo Voador. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(822, 'Corvisquire é um Pokémon do tipo Voador. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Rookidee.').
pokemon_lore(823, 'Corviknight é um Pokémon do tipo Voador/Aço. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Corvisquire.').
pokemon_lore(824, 'Blipbug é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(825, 'Dottler é um Pokémon do tipo Inseto/Psíquico. Vive com frequência em habitat pouco documentado, com aparência amarelada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Blipbug.').
pokemon_lore(826, 'Orbeetle é um Pokémon do tipo Inseto/Psíquico. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Dottler.').
pokemon_lore(827, 'Nickit é um Pokémon do tipo Sombrio. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(828, 'Thievul é um Pokémon do tipo Sombrio. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Nickit.').
pokemon_lore(829, 'Gossifleur é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(830, 'Eldegoss é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Gossifleur.').
pokemon_lore(831, 'Wooloo é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(832, 'Dubwool é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Wooloo.').
pokemon_lore(833, 'Chewtle é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(834, 'Drednaw é um Pokémon do tipo Água/Pedra. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Chewtle.').
pokemon_lore(835, 'Yamper é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(836, 'Boltund é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Yamper.').
pokemon_lore(837, 'Rolycoly é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência escura e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(838, 'Carkol é um Pokémon do tipo Pedra/Fogo. Vive com frequência em habitat pouco documentado, com aparência escura e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Rolycoly.').
pokemon_lore(839, 'Coalossal é um Pokémon do tipo Pedra/Fogo. Vive com frequência em habitat pouco documentado, com aparência escura e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Carkol.').
pokemon_lore(840, 'Applin é um Pokémon do tipo Grama/Dragão. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(841, 'Flapple é um Pokémon do tipo Grama/Dragão. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Applin.').
pokemon_lore(842, 'Appletun é um Pokémon do tipo Grama/Dragão. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Applin.').
pokemon_lore(843, 'Silicobra é um Pokémon do tipo Terra. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(844, 'Sandaconda é um Pokémon do tipo Terra. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Silicobra.').
pokemon_lore(845, 'Cramorant é um Pokémon do tipo Voador/Água. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(846, 'Arrokuda é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(847, 'Barraskewda é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Arrokuda.').
pokemon_lore(848, 'Toxel é um Pokémon do tipo Elétrico/Veneno. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura ereta. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(849, 'Toxtricity Amped é um Pokémon do tipo Elétrico/Veneno. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Toxel.').
pokemon_lore(850, 'Sizzlipede é um Pokémon do tipo Fogo/Inseto. Vive com frequência em habitat pouco documentado, com aparência avermelhada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(851, 'Centiskorch é um Pokémon do tipo Fogo/Inseto. Vive com frequência em habitat pouco documentado, com aparência avermelhada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sizzlipede.').
pokemon_lore(852, 'Clobbopus é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(853, 'Grapploct é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência azulada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Clobbopus.').
pokemon_lore(854, 'Sinistea é um Pokémon do tipo Fantasma. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(855, 'Polteageist é um Pokémon do tipo Fantasma. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sinistea.').
pokemon_lore(856, 'Hatenna é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência rosada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(857, 'Hattrem é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência rosada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Hatenna.').
pokemon_lore(858, 'Hatterene é um Pokémon do tipo Psíquico/Fada. Vive com frequência em habitat pouco documentado, com aparência rosada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Hattrem.').
pokemon_lore(859, 'Impidimp é um Pokémon do tipo Sombrio/Fada. Vive com frequência em habitat pouco documentado, com aparência rosada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(860, 'Morgrem é um Pokémon do tipo Sombrio/Fada. Vive com frequência em habitat pouco documentado, com aparência rosada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Impidimp.').
pokemon_lore(861, 'Grimmsnarl é um Pokémon do tipo Sombrio/Fada. Vive com frequência em habitat pouco documentado, com aparência arroxeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Morgrem.').
pokemon_lore(862, 'Obstagoon é um Pokémon do tipo Sombrio/Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Linoone.').
pokemon_lore(863, 'Perrserker é um Pokémon do tipo Aço. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Meowth.').
pokemon_lore(864, 'Cursola é um Pokémon do tipo Fantasma. Vive com frequência em habitat pouco documentado, com aparência clara e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Corsola.').
pokemon_lore(865, 'Sirfetchd é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência clara e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Farfetchd.').
pokemon_lore(866, 'Mr Rime é um Pokémon do tipo Gelo/Psíquico. Vive com frequência em habitat pouco documentado, com aparência arroxeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Mr Mime.').
pokemon_lore(867, 'Runerigus é um Pokémon do tipo Terra/Fantasma. Vive com frequência em habitat pouco documentado, com aparência acinzentada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Yamask.').
pokemon_lore(868, 'Milcery é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência clara e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(869, 'Alcremie é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência clara e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Milcery.').
pokemon_lore(870, 'Falinks é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência amarelada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(871, 'Pincurchin é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência arroxeada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(872, 'Snom é um Pokémon do tipo Gelo/Inseto. Vive com frequência em habitat pouco documentado, com aparência clara e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(873, 'Frosmoth é um Pokémon do tipo Gelo/Inseto. Vive com frequência em habitat pouco documentado, com aparência clara e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Snom.').
pokemon_lore(874, 'Stonjourner é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(875, 'Eiscue Ice é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(876, 'Indeedee Male é um Pokémon do tipo Psíquico/Normal. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(877, 'Morpeko Full Belly é um Pokémon do tipo Elétrico/Sombrio. Vive com frequência em habitat pouco documentado, com aparência amarelada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(878, 'Cufant é um Pokémon do tipo Aço. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(879, 'Copperajah é um Pokémon do tipo Aço. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Cufant.').
pokemon_lore(880, 'Dracozolt é um Pokémon do tipo Elétrico/Dragão. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(881, 'Arctozolt é um Pokémon do tipo Elétrico/Gelo. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(882, 'Dracovish é um Pokémon do tipo Água/Dragão. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(883, 'Arctovish é um Pokémon do tipo Água/Gelo. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(884, 'Duraludon é um Pokémon do tipo Aço/Dragão. Vive com frequência em habitat pouco documentado, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(885, 'Dreepy é um Pokémon do tipo Dragão/Fantasma. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(886, 'Drakloak é um Pokémon do tipo Dragão/Fantasma. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Dreepy.').
pokemon_lore(887, 'Dragapult é um Pokémon do tipo Dragão/Fantasma. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Drakloak.').
pokemon_lore(888, 'Zacian é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(889, 'Zamazenta é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(890, 'Eternatus é um Pokémon do tipo Veneno/Dragão. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo com asas. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(891, 'Kubfu é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(892, 'Urshifu Single Strike é um Pokémon do tipo Lutador/Sombrio. Vive com frequência em habitat pouco documentado, com aparência acinzentada e aparencia humanoide. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva parte de Kubfu.').
pokemon_lore(893, 'Zarude é um Pokémon do tipo Sombrio/Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(894, 'Regieleki é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência amarelada e aparencia humanoide. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(895, 'Regidrago é um Pokémon do tipo Dragão. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(896, 'Glastrier é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(897, 'Spectrier é um Pokémon do tipo Fantasma. Vive com frequência em habitat pouco documentado, com aparência escura e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(898, 'Calyrex é um Pokémon do tipo Psíquico/Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(899, 'Wyrdeer é um Pokémon do tipo Normal/Psíquico. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Stantler.').
pokemon_lore(900, 'Kleavor é um Pokémon do tipo Inseto/Pedra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Scyther.').
pokemon_lore(901, 'Ursaluna é um Pokémon do tipo Terra/Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Ursaring.').
pokemon_lore(902, 'Basculegion Male é um Pokémon do tipo Água/Fantasma. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Basculin.').
pokemon_lore(903, 'Sneasler é um Pokémon do tipo Lutador/Veneno. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sneasel.').
pokemon_lore(904, 'Overqwil é um Pokémon do tipo Sombrio/Veneno. Vive com frequência em habitat pouco documentado, com aparência escura e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Qwilfish.').
pokemon_lore(905, 'Enamorus Incarnate é um Pokémon do tipo Fada/Voador. Vive com frequência em habitat pouco documentado, com aparência rosada e forma com bracos marcantes. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
