:- encoding(utf8).
% Lore local da geracao 2
% Formato: pokemon_lore(ID, Texto).
:- multifile pokemon_lore/2.
pokemon_lore(152, 'Chikorita é um Pokémon do tipo Grama. Vive com frequência em campos abertos, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(153, 'Bayleef é um Pokémon do tipo Grama. Vive com frequência em campos abertos, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Chikorita.').
pokemon_lore(154, 'Meganium é um Pokémon do tipo Grama. Vive com frequência em campos abertos, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Bayleef.').
pokemon_lore(155, 'Cyndaquil é um Pokémon do tipo Fogo. Vive com frequência em campos abertos, com aparência amarelada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(156, 'Quilava é um Pokémon do tipo Fogo. Vive com frequência em campos abertos, com aparência amarelada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Cyndaquil.').
pokemon_lore(157, 'Typhlosion é um Pokémon do tipo Fogo. Vive com frequência em campos abertos, com aparência amarelada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Quilava.').
pokemon_lore(158, 'Totodile é um Pokémon do tipo Água. Vive com frequência em margens de rios e lagos, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(159, 'Croconaw é um Pokémon do tipo Água. Vive com frequência em margens de rios e lagos, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Totodile.').
pokemon_lore(160, 'Feraligatr é um Pokémon do tipo Água. Vive com frequência em margens de rios e lagos, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Croconaw.').
pokemon_lore(161, 'Sentret é um Pokémon do tipo Normal. Vive com frequência em campos abertos, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(162, 'Furret é um Pokémon do tipo Normal. Vive com frequência em campos abertos, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sentret.').
pokemon_lore(163, 'Hoothoot é um Pokémon do tipo Normal/Voador. Vive com frequência em florestas, com aparência amarronzada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(164, 'Noctowl é um Pokémon do tipo Normal/Voador. Vive com frequência em florestas, com aparência amarronzada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Hoothoot.').
pokemon_lore(165, 'Ledyba é um Pokémon do tipo Inseto/Voador. Vive com frequência em florestas, com aparência avermelhada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(166, 'Ledian é um Pokémon do tipo Inseto/Voador. Vive com frequência em florestas, com aparência avermelhada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Ledyba.').
pokemon_lore(167, 'Spinarak é um Pokémon do tipo Inseto/Veneno. Vive com frequência em florestas, com aparência esverdeada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(168, 'Ariados é um Pokémon do tipo Inseto/Veneno. Vive com frequência em florestas, com aparência avermelhada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Spinarak.').
pokemon_lore(169, 'Crobat é um Pokémon do tipo Veneno/Voador. Vive com frequência em cavernas, com aparência arroxeada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Golbat.').
pokemon_lore(170, 'Chinchou é um Pokémon do tipo Água/Elétrico. Vive com frequência em mares e oceanos, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(171, 'Lanturn é um Pokémon do tipo Água/Elétrico. Vive com frequência em mares e oceanos, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Chinchou.').
pokemon_lore(172, 'Pichu é um Pokémon do tipo Elétrico. Vive com frequência em florestas, com aparência amarelada e postura quadrupede. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(173, 'Cleffa é um Pokémon do tipo Fada. Vive com frequência em regioes montanhosas, com aparência rosada e postura ereta. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(174, 'Igglybuff é um Pokémon do tipo Normal/Fada. Vive com frequência em campos abertos, com aparência rosada e aparencia humanoide. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(175, 'Togepi é um Pokémon do tipo Fada. Vive com frequência em florestas, com aparência clara e aparencia humanoide. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(176, 'Togetic é um Pokémon do tipo Fada/Voador. Vive com frequência em florestas, com aparência clara e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Togepi.').
pokemon_lore(177, 'Natu é um Pokémon do tipo Psíquico/Voador. Vive com frequência em florestas, com aparência esverdeada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(178, 'Xatu é um Pokémon do tipo Psíquico/Voador. Vive com frequência em florestas, com aparência esverdeada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Natu.').
pokemon_lore(179, 'Mareep é um Pokémon do tipo Elétrico. Vive com frequência em campos abertos, com aparência clara e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(180, 'Flaaffy é um Pokémon do tipo Elétrico. Vive com frequência em campos abertos, com aparência rosada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Mareep.').
pokemon_lore(181, 'Ampharos é um Pokémon do tipo Elétrico. Vive com frequência em campos abertos, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Flaaffy.').
pokemon_lore(182, 'Bellossom é um Pokémon do tipo Grama. Vive com frequência em campos abertos, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Gloom.').
pokemon_lore(183, 'Marill é um Pokémon do tipo Água/Fada. Vive com frequência em margens de rios e lagos, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Azurill.').
pokemon_lore(184, 'Azumarill é um Pokémon do tipo Água/Fada. Vive com frequência em margens de rios e lagos, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Marill.').
pokemon_lore(185, 'Sudowoodo é um Pokémon do tipo Pedra. Vive com frequência em florestas, com aparência amarronzada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Bonsly.').
pokemon_lore(186, 'Politoed é um Pokémon do tipo Água. Vive com frequência em margens de rios e lagos, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Poliwhirl.').
pokemon_lore(187, 'Hoppip é um Pokémon do tipo Grama/Voador. Vive com frequência em campos abertos, com aparência rosada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(188, 'Skiploom é um Pokémon do tipo Grama/Voador. Vive com frequência em campos abertos, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Hoppip.').
pokemon_lore(189, 'Jumpluff é um Pokémon do tipo Grama/Voador. Vive com frequência em campos abertos, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Skiploom.').
pokemon_lore(190, 'Aipom é um Pokémon do tipo Normal. Vive com frequência em florestas, com aparência arroxeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(191, 'Sunkern é um Pokémon do tipo Grama. Vive com frequência em campos abertos, com aparência amarelada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(192, 'Sunflora é um Pokémon do tipo Grama. Vive com frequência em campos abertos, com aparência amarelada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sunkern.').
pokemon_lore(193, 'Yanma é um Pokémon do tipo Inseto/Voador. Vive com frequência em florestas, com aparência avermelhada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(194, 'Wooper é um Pokémon do tipo Água/Terra. Vive com frequência em margens de rios e lagos, com aparência azulada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(195, 'Quagsire é um Pokémon do tipo Água/Terra. Vive com frequência em margens de rios e lagos, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Wooper.').
pokemon_lore(196, 'Espeon é um Pokémon do tipo Psíquico. Vive com frequência em areas urbanas, com aparência arroxeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Eevee.').
pokemon_lore(197, 'Umbreon é um Pokémon do tipo Sombrio. Vive com frequência em areas urbanas, com aparência escura e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Eevee.').
pokemon_lore(198, 'Murkrow é um Pokémon do tipo Sombrio/Voador. Vive com frequência em florestas, com aparência escura e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(199, 'Slowking é um Pokémon do tipo Água/Psíquico. Vive com frequência em margens de rios e lagos, com aparência rosada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Slowpoke.').
pokemon_lore(200, 'Misdreavus é um Pokémon do tipo Fantasma. Vive com frequência em cavernas, com aparência acinzentada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(201, 'Unown é um Pokémon do tipo Psíquico. Vive com frequência em locais raros e pouco acessiveis, com aparência escura e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(202, 'Wobbuffet é um Pokémon do tipo Psíquico. Vive com frequência em cavernas, com aparência azulada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Wynaut.').
pokemon_lore(203, 'Girafarig é um Pokémon do tipo Normal/Psíquico. Vive com frequência em campos abertos, com aparência amarelada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(204, 'Pineco é um Pokémon do tipo Inseto. Vive com frequência em florestas, com aparência acinzentada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(205, 'Forretress é um Pokémon do tipo Inseto/Aço. Vive com frequência em florestas, com aparência arroxeada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Pineco.').
pokemon_lore(206, 'Dunsparce é um Pokémon do tipo Normal. Vive com frequência em cavernas, com aparência amarelada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(207, 'Gligar é um Pokémon do tipo Terra/Voador. Vive com frequência em regioes montanhosas, com aparência arroxeada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(208, 'Steelix é um Pokémon do tipo Aço/Terra. Vive com frequência em cavernas, com aparência acinzentada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Onix.').
pokemon_lore(209, 'Snubbull é um Pokémon do tipo Fada. Vive com frequência em areas urbanas, com aparência rosada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(210, 'Granbull é um Pokémon do tipo Fada. Vive com frequência em areas urbanas, com aparência arroxeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Snubbull.').
pokemon_lore(211, 'Qwilfish é um Pokémon do tipo Água/Veneno. Vive com frequência em mares e oceanos, com aparência acinzentada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(212, 'Scizor é um Pokémon do tipo Inseto/Aço. Vive com frequência em campos abertos, com aparência avermelhada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Scyther.').
pokemon_lore(213, 'Shuckle é um Pokémon do tipo Inseto/Pedra. Vive com frequência em regioes montanhosas, com aparência amarelada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(214, 'Heracross é um Pokémon do tipo Inseto/Lutador. Vive com frequência em florestas, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(215, 'Sneasel é um Pokémon do tipo Sombrio/Gelo. Vive com frequência em florestas, com aparência escura e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(216, 'Teddiursa é um Pokémon do tipo Normal. Vive com frequência em regioes montanhosas, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(217, 'Ursaring é um Pokémon do tipo Normal. Vive com frequência em regioes montanhosas, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Teddiursa.').
pokemon_lore(218, 'Slugma é um Pokémon do tipo Fogo. Vive com frequência em regioes montanhosas, com aparência avermelhada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(219, 'Magcargo é um Pokémon do tipo Fogo/Pedra. Vive com frequência em regioes montanhosas, com aparência avermelhada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Slugma.').
pokemon_lore(220, 'Swinub é um Pokémon do tipo Gelo/Terra. Vive com frequência em cavernas, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(221, 'Piloswine é um Pokémon do tipo Gelo/Terra. Vive com frequência em cavernas, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Swinub.').
pokemon_lore(222, 'Corsola é um Pokémon do tipo Água/Pedra. Vive com frequência em mares e oceanos, com aparência rosada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(223, 'Remoraid é um Pokémon do tipo Água. Vive com frequência em mares e oceanos, com aparência acinzentada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(224, 'Octillery é um Pokémon do tipo Água. Vive com frequência em mares e oceanos, com aparência avermelhada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Remoraid.').
pokemon_lore(225, 'Delibird é um Pokémon do tipo Gelo/Voador. Vive com frequência em regioes montanhosas, com aparência avermelhada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(226, 'Mantine é um Pokémon do tipo Água/Voador. Vive com frequência em mares e oceanos, com aparência arroxeada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Mantyke.').
pokemon_lore(227, 'Skarmory é um Pokémon do tipo Aço/Voador. Vive com frequência em terrenos acidentados, com aparência acinzentada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(228, 'Houndour é um Pokémon do tipo Sombrio/Fogo. Vive com frequência em terrenos acidentados, com aparência escura e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(229, 'Houndoom é um Pokémon do tipo Sombrio/Fogo. Vive com frequência em terrenos acidentados, com aparência escura e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Houndour.').
pokemon_lore(230, 'Kingdra é um Pokémon do tipo Água/Dragão. Vive com frequência em mares e oceanos, com aparência azulada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Seadra.').
pokemon_lore(231, 'Phanpy é um Pokémon do tipo Terra. Vive com frequência em terrenos acidentados, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(232, 'Donphan é um Pokémon do tipo Terra. Vive com frequência em terrenos acidentados, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Phanpy.').
pokemon_lore(233, 'Porygon2 é um Pokémon do tipo Normal. Vive com frequência em areas urbanas, com aparência avermelhada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Porygon.').
pokemon_lore(234, 'Stantler é um Pokémon do tipo Normal. Vive com frequência em florestas, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(235, 'Smeargle é um Pokémon do tipo Normal. Vive com frequência em areas urbanas, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(236, 'Tyrogue é um Pokémon do tipo Lutador. Vive com frequência em areas urbanas, com aparência arroxeada e aparencia humanoide. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(237, 'Hitmontop é um Pokémon do tipo Lutador. Vive com frequência em areas urbanas, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tyrogue.').
pokemon_lore(238, 'Smoochum é um Pokémon do tipo Gelo/Psíquico. Vive com frequência em areas urbanas, com aparência rosada e aparencia humanoide. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(239, 'Elekid é um Pokémon do tipo Elétrico. Vive com frequência em campos abertos, com aparência amarelada e aparencia humanoide. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(240, 'Magby é um Pokémon do tipo Fogo. Vive com frequência em regioes montanhosas, com aparência avermelhada e postura ereta. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(241, 'Miltank é um Pokémon do tipo Normal. Vive com frequência em campos abertos, com aparência rosada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(242, 'Blissey é um Pokémon do tipo Normal. Vive com frequência em areas urbanas, com aparência rosada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Chansey.').
pokemon_lore(243, 'Raikou é um Pokémon do tipo Elétrico. Vive com frequência em campos abertos, com aparência amarelada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(244, 'Entei é um Pokémon do tipo Fogo. Vive com frequência em campos abertos, com aparência amarronzada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(245, 'Suicune é um Pokémon do tipo Água. Vive com frequência em campos abertos, com aparência azulada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(246, 'Larvitar é um Pokémon do tipo Pedra/Terra. Vive com frequência em regioes montanhosas, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(247, 'Pupitar é um Pokémon do tipo Pedra/Terra. Vive com frequência em regioes montanhosas, com aparência acinzentada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Larvitar.').
pokemon_lore(248, 'Tyranitar é um Pokémon do tipo Pedra/Sombrio. Vive com frequência em regioes montanhosas, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Pupitar.').
pokemon_lore(249, 'Lugia é um Pokémon do tipo Psíquico/Voador. Vive com frequência em locais raros e pouco acessiveis, com aparência clara e corpo com asas. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(250, 'Ho Oh é um Pokémon do tipo Fogo/Voador. Vive com frequência em locais raros e pouco acessiveis, com aparência avermelhada e corpo com asas. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(251, 'Celebi é um Pokémon do tipo Psíquico/Grama. Vive com frequência em florestas, com aparência esverdeada e aparencia humanoide. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
