:- encoding(utf8).
% Lore local da geracao 4
% Formato: pokemon_lore(ID, Texto).
:- multifile pokemon_lore/2.
pokemon_lore(387, 'Turtwig é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(388, 'Grotle é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Turtwig.').
pokemon_lore(389, 'Torterra é um Pokémon do tipo Grama/Terra. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Grotle.').
pokemon_lore(390, 'Chimchar é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(391, 'Monferno é um Pokémon do tipo Fogo/Lutador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Chimchar.').
pokemon_lore(392, 'Infernape é um Pokémon do tipo Fogo/Lutador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Monferno.').
pokemon_lore(393, 'Piplup é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(394, 'Prinplup é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Piplup.').
pokemon_lore(395, 'Empoleon é um Pokémon do tipo Água/Aço. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Prinplup.').
pokemon_lore(396, 'Starly é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(397, 'Staravia é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Starly.').
pokemon_lore(398, 'Staraptor é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Staravia.').
pokemon_lore(399, 'Bidoof é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(400, 'Bibarel é um Pokémon do tipo Normal/Água. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Bidoof.').
pokemon_lore(401, 'Kricketot é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência avermelhada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(402, 'Kricketune é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência avermelhada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Kricketot.').
pokemon_lore(403, 'Shinx é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(404, 'Luxio é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Shinx.').
pokemon_lore(405, 'Luxray é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Luxio.').
pokemon_lore(406, 'Budew é um Pokémon do tipo Grama/Veneno. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(407, 'Roserade é um Pokémon do tipo Grama/Veneno. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Roselia.').
pokemon_lore(408, 'Cranidos é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(409, 'Rampardos é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Cranidos.').
pokemon_lore(410, 'Shieldon é um Pokémon do tipo Pedra/Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(411, 'Bastiodon é um Pokémon do tipo Pedra/Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Shieldon.').
pokemon_lore(412, 'Burmy é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(413, 'Wormadam Plant é um Pokémon do tipo Inseto/Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Burmy.').
pokemon_lore(414, 'Mothim é um Pokémon do tipo Inseto/Voador. Vive com frequência em habitat pouco documentado, com aparência amarelada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Burmy.').
pokemon_lore(415, 'Combee é um Pokémon do tipo Inseto/Voador. Vive com frequência em habitat pouco documentado, com aparência amarelada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(416, 'Vespiquen é um Pokémon do tipo Inseto/Voador. Vive com frequência em habitat pouco documentado, com aparência amarelada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Combee.').
pokemon_lore(417, 'Pachirisu é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(418, 'Buizel é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(419, 'Floatzel é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Buizel.').
pokemon_lore(420, 'Cherubi é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência rosada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(421, 'Cherrim é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Cherubi.').
pokemon_lore(422, 'Shellos é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(423, 'Gastrodon é um Pokémon do tipo Água/Terra. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Shellos.').
pokemon_lore(424, 'Ambipom é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Aipom.').
pokemon_lore(425, 'Drifloon é um Pokémon do tipo Fantasma/Voador. Vive com frequência em habitat pouco documentado, com aparência arroxeada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(426, 'Drifblim é um Pokémon do tipo Fantasma/Voador. Vive com frequência em habitat pouco documentado, com aparência arroxeada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Drifloon.').
pokemon_lore(427, 'Buneary é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(428, 'Lopunny é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Buneary.').
pokemon_lore(429, 'Mismagius é um Pokémon do tipo Fantasma. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Misdreavus.').
pokemon_lore(430, 'Honchkrow é um Pokémon do tipo Sombrio/Voador. Vive com frequência em habitat pouco documentado, com aparência escura e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Murkrow.').
pokemon_lore(431, 'Glameow é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(432, 'Purugly é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Glameow.').
pokemon_lore(433, 'Chingling é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência amarelada e aparencia humanoide. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(434, 'Stunky é um Pokémon do tipo Veneno/Sombrio. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(435, 'Skuntank é um Pokémon do tipo Veneno/Sombrio. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Stunky.').
pokemon_lore(436, 'Bronzor é um Pokémon do tipo Aço/Psíquico. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(437, 'Bronzong é um Pokémon do tipo Aço/Psíquico. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Bronzor.').
pokemon_lore(438, 'Bonsly é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura bípede. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(439, 'Mime Jr é um Pokémon do tipo Psíquico/Fada. Vive com frequência em habitat pouco documentado, com aparência rosada e aparencia humanoide. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(440, 'Happiny é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência rosada e aparencia humanoide. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(441, 'Chatot é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência escura e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(442, 'Spiritomb é um Pokémon do tipo Fantasma/Sombrio. Vive com frequência em habitat pouco documentado, com aparência arroxeada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(443, 'Gible é um Pokémon do tipo Dragão/Terra. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(444, 'Gabite é um Pokémon do tipo Dragão/Terra. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Gible.').
pokemon_lore(445, 'Garchomp é um Pokémon do tipo Dragão/Terra. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Gabite.').
pokemon_lore(446, 'Munchlax é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência escura e aparencia humanoide. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(447, 'Riolu é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(448, 'Lucario é um Pokémon do tipo Lutador/Aço. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Riolu.').
pokemon_lore(449, 'Hippopotas é um Pokémon do tipo Terra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(450, 'Hippowdon é um Pokémon do tipo Terra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Hippopotas.').
pokemon_lore(451, 'Skorupi é um Pokémon do tipo Veneno/Inseto. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(452, 'Drapion é um Pokémon do tipo Veneno/Sombrio. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Skorupi.').
pokemon_lore(453, 'Croagunk é um Pokémon do tipo Veneno/Lutador. Vive com frequência em habitat pouco documentado, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(454, 'Toxicroak é um Pokémon do tipo Veneno/Lutador. Vive com frequência em habitat pouco documentado, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Croagunk.').
pokemon_lore(455, 'Carnivine é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(456, 'Finneon é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(457, 'Lumineon é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Finneon.').
pokemon_lore(458, 'Mantyke é um Pokémon do tipo Água/Voador. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo com asas. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(459, 'Snover é um Pokémon do tipo Grama/Gelo. Vive com frequência em habitat pouco documentado, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(460, 'Abomasnow é um Pokémon do tipo Grama/Gelo. Vive com frequência em habitat pouco documentado, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Snover.').
pokemon_lore(461, 'Weavile é um Pokémon do tipo Sombrio/Gelo. Vive com frequência em habitat pouco documentado, com aparência escura e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sneasel.').
pokemon_lore(462, 'Magnezone é um Pokémon do tipo Elétrico/Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Magneton.').
pokemon_lore(463, 'Lickilicky é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência rosada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Lickitung.').
pokemon_lore(464, 'Rhyperior é um Pokémon do tipo Terra/Pedra. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Rhydon.').
pokemon_lore(465, 'Tangrowth é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tangela.').
pokemon_lore(466, 'Electivire é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Electabuzz.').
pokemon_lore(467, 'Magmortar é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Magmar.').
pokemon_lore(468, 'Togekiss é um Pokémon do tipo Fada/Voador. Vive com frequência em habitat pouco documentado, com aparência clara e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Togetic.').
pokemon_lore(469, 'Yanmega é um Pokémon do tipo Inseto/Voador. Vive com frequência em habitat pouco documentado, com aparência esverdeada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Yanma.').
pokemon_lore(470, 'Leafeon é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Eevee.').
pokemon_lore(471, 'Glaceon é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Eevee.').
pokemon_lore(472, 'Gliscor é um Pokémon do tipo Terra/Voador. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Gligar.').
pokemon_lore(473, 'Mamoswine é um Pokémon do tipo Gelo/Terra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Piloswine.').
pokemon_lore(474, 'Porygon Z é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência avermelhada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Porygon2.').
pokemon_lore(475, 'Gallade é um Pokémon do tipo Psíquico/Lutador. Vive com frequência em habitat pouco documentado, com aparência clara e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Kirlia.').
pokemon_lore(476, 'Probopass é um Pokémon do tipo Pedra/Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Nosepass.').
pokemon_lore(477, 'Dusknoir é um Pokémon do tipo Fantasma. Vive com frequência em habitat pouco documentado, com aparência escura e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Dusclops.').
pokemon_lore(478, 'Froslass é um Pokémon do tipo Gelo/Fantasma. Vive com frequência em habitat pouco documentado, com aparência clara e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Snorunt.').
pokemon_lore(479, 'Rotom é um Pokémon do tipo Elétrico/Fantasma. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(480, 'Uxie é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura ereta. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(481, 'Mesprit é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência rosada e postura ereta. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(482, 'Azelf é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(483, 'Dialga é um Pokémon do tipo Aço/Dragão. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(484, 'Palkia é um Pokémon do tipo Água/Dragão. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura ereta. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(485, 'Heatran é um Pokémon do tipo Fogo/Aço. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(486, 'Regigigas é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência clara e aparencia humanoide. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(487, 'Giratina Altered é um Pokémon do tipo Fantasma/Dragão. Vive com frequência em habitat pouco documentado, com aparência escura e forma com tentaculos. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(488, 'Cresselia é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência amarelada e corpo serpentino. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(489, 'Phione é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e forma com bracos marcantes. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(490, 'Manaphy é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e aparencia humanoide. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(491, 'Darkrai é um Pokémon do tipo Sombrio. Vive com frequência em habitat pouco documentado, com aparência escura e aparencia humanoide. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(492, 'Shaymin Land é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(493, 'Arceus é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
