:- encoding(utf8).
% Lore local da geracao 7
% Formato: pokemon_lore(ID, Texto).
:- multifile pokemon_lore/2.
pokemon_lore(722, 'Rowlet é um Pokémon do tipo Grama/Voador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(723, 'Dartrix é um Pokémon do tipo Grama/Voador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Rowlet.').
pokemon_lore(724, 'Decidueye é um Pokémon do tipo Grama/Fantasma. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Dartrix.').
pokemon_lore(725, 'Litten é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(726, 'Torracat é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Litten.').
pokemon_lore(727, 'Incineroar é um Pokémon do tipo Fogo/Sombrio. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Torracat.').
pokemon_lore(728, 'Popplio é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(729, 'Brionne é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Popplio.').
pokemon_lore(730, 'Primarina é um Pokémon do tipo Água/Fada. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Brionne.').
pokemon_lore(731, 'Pikipek é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência escura e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(732, 'Trumbeak é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência escura e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Pikipek.').
pokemon_lore(733, 'Toucannon é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência escura e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Trumbeak.').
pokemon_lore(734, 'Yungoos é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(735, 'Gumshoos é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Yungoos.').
pokemon_lore(736, 'Grubbin é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(737, 'Charjabug é um Pokémon do tipo Inseto/Elétrico. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Grubbin.').
pokemon_lore(738, 'Vikavolt é um Pokémon do tipo Inseto/Elétrico. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Charjabug.').
pokemon_lore(739, 'Crabrawler é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(740, 'Crabominable é um Pokémon do tipo Lutador/Gelo. Vive com frequência em habitat pouco documentado, com aparência clara e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Crabrawler.').
pokemon_lore(741, 'Oricorio Baile é um Pokémon do tipo Fogo/Voador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(742, 'Cutiefly é um Pokémon do tipo Inseto/Fada. Vive com frequência em habitat pouco documentado, com aparência amarelada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(743, 'Ribombee é um Pokémon do tipo Inseto/Fada. Vive com frequência em habitat pouco documentado, com aparência amarelada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Cutiefly.').
pokemon_lore(744, 'Rockruff é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(745, 'Lycanroc Midday é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Rockruff.').
pokemon_lore(746, 'Wishiwashi Solo é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(747, 'Mareanie é um Pokémon do tipo Veneno/Água. Vive com frequência em habitat pouco documentado, com aparência azulada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(748, 'Toxapex é um Pokémon do tipo Veneno/Água. Vive com frequência em habitat pouco documentado, com aparência azulada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Mareanie.').
pokemon_lore(749, 'Mudbray é um Pokémon do tipo Terra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(750, 'Mudsdale é um Pokémon do tipo Terra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Mudbray.').
pokemon_lore(751, 'Dewpider é um Pokémon do tipo Água/Inseto. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(752, 'Araquanid é um Pokémon do tipo Água/Inseto. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Dewpider.').
pokemon_lore(753, 'Fomantis é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência rosada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(754, 'Lurantis é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência rosada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Fomantis.').
pokemon_lore(755, 'Morelull é um Pokémon do tipo Grama/Fada. Vive com frequência em habitat pouco documentado, com aparência arroxeada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(756, 'Shiinotic é um Pokémon do tipo Grama/Fada. Vive com frequência em habitat pouco documentado, com aparência arroxeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Morelull.').
pokemon_lore(757, 'Salandit é um Pokémon do tipo Veneno/Fogo. Vive com frequência em habitat pouco documentado, com aparência escura e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(758, 'Salazzle é um Pokémon do tipo Veneno/Fogo. Vive com frequência em habitat pouco documentado, com aparência escura e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Salandit.').
pokemon_lore(759, 'Stufful é um Pokémon do tipo Normal/Lutador. Vive com frequência em habitat pouco documentado, com aparência rosada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(760, 'Bewear é um Pokémon do tipo Normal/Lutador. Vive com frequência em habitat pouco documentado, com aparência rosada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Stufful.').
pokemon_lore(761, 'Bounsweet é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(762, 'Steenee é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência arroxeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Bounsweet.').
pokemon_lore(763, 'Tsareena é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência arroxeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Steenee.').
pokemon_lore(764, 'Comfey é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(765, 'Oranguru é um Pokémon do tipo Normal/Psíquico. Vive com frequência em habitat pouco documentado, com aparência clara e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(766, 'Passimian é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(767, 'Wimpod é um Pokémon do tipo Inseto/Água. Vive com frequência em habitat pouco documentado, com aparência acinzentada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(768, 'Golisopod é um Pokémon do tipo Inseto/Água. Vive com frequência em habitat pouco documentado, com aparência acinzentada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Wimpod.').
pokemon_lore(769, 'Sandygast é um Pokémon do tipo Fantasma/Terra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(770, 'Palossand é um Pokémon do tipo Fantasma/Terra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sandygast.').
pokemon_lore(771, 'Pyukumuku é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência escura e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(772, 'Type Null é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(773, 'Silvally é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva parte de Type Null.').
pokemon_lore(774, 'Minior Red Meteor é um Pokémon do tipo Pedra/Voador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(775, 'Komala é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(776, 'Turtonator é um Pokémon do tipo Fogo/Dragão. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(777, 'Togedemaru é um Pokémon do tipo Elétrico/Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(778, 'Mimikyu Disguised é um Pokémon do tipo Fantasma/Fada. Vive com frequência em habitat pouco documentado, com aparência amarelada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(779, 'Bruxish é um Pokémon do tipo Água/Psíquico. Vive com frequência em habitat pouco documentado, com aparência rosada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(780, 'Drampa é um Pokémon do tipo Normal/Dragão. Vive com frequência em habitat pouco documentado, com aparência clara e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(781, 'Dhelmise é um Pokémon do tipo Fantasma/Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(782, 'Jangmo O é um Pokémon do tipo Dragão. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(783, 'Hakamo O é um Pokémon do tipo Dragão/Lutador. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Jangmo O.').
pokemon_lore(784, 'Kommo O é um Pokémon do tipo Dragão/Lutador. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Hakamo O.').
pokemon_lore(785, 'Tapu Koko é um Pokémon do tipo Elétrico/Fada. Vive com frequência em habitat pouco documentado, com aparência amarelada e forma com bracos marcantes. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(786, 'Tapu Lele é um Pokémon do tipo Psíquico/Fada. Vive com frequência em habitat pouco documentado, com aparência rosada e forma com bracos marcantes. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(787, 'Tapu Bulu é um Pokémon do tipo Grama/Fada. Vive com frequência em habitat pouco documentado, com aparência avermelhada e forma com bracos marcantes. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(788, 'Tapu Fini é um Pokémon do tipo Água/Fada. Vive com frequência em habitat pouco documentado, com aparência arroxeada e forma com bracos marcantes. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(789, 'Cosmog é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo arredondado. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(790, 'Cosmoem é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo arredondado. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva parte de Cosmog.').
pokemon_lore(791, 'Solgaleo é um Pokémon do tipo Psíquico/Aço. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva parte de Cosmoem.').
pokemon_lore(792, 'Lunala é um Pokémon do tipo Psíquico/Fantasma. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo com asas. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva parte de Cosmoem.').
pokemon_lore(793, 'Nihilego é um Pokémon do tipo Pedra/Veneno. Vive com frequência em habitat pouco documentado, com aparência clara e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(794, 'Buzzwole é um Pokémon do tipo Inseto/Lutador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(795, 'Pheromosa é um Pokémon do tipo Inseto/Lutador. Vive com frequência em habitat pouco documentado, com aparência clara e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(796, 'Xurkitree é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência escura e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(797, 'Celesteela é um Pokémon do tipo Aço/Voador. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(798, 'Kartana é um Pokémon do tipo Grama/Aço. Vive com frequência em habitat pouco documentado, com aparência clara e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(799, 'Guzzlord é um Pokémon do tipo Sombrio/Dragão. Vive com frequência em habitat pouco documentado, com aparência escura e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(800, 'Necrozma é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência escura e forma com bracos marcantes. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(801, 'Magearna é um Pokémon do tipo Aço/Fada. Vive com frequência em habitat pouco documentado, com aparência acinzentada e aparencia humanoide. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(802, 'Marshadow é um Pokémon do tipo Lutador/Fantasma. Vive com frequência em habitat pouco documentado, com aparência acinzentada e aparencia humanoide. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(803, 'Poipole é um Pokémon do tipo Veneno. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(804, 'Naganadel é um Pokémon do tipo Veneno/Dragão. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Poipole.').
pokemon_lore(805, 'Stakataka é um Pokémon do tipo Pedra/Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(806, 'Blacephalon é um Pokémon do tipo Fogo/Fantasma. Vive com frequência em habitat pouco documentado, com aparência clara e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(807, 'Zeraora é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência amarelada e aparencia humanoide. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(808, 'Meltan é um Pokémon do tipo Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo arredondado. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(809, 'Melmetal é um Pokémon do tipo Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e aparencia humanoide. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva parte de Meltan.').
