:- encoding(utf8).
% Lore local da geracao 3
% Formato: pokemon_lore(ID, Texto).
:- multifile pokemon_lore/2.
pokemon_lore(252, 'Treecko é um Pokémon do tipo Grama. Vive com frequência em florestas, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(253, 'Grovyle é um Pokémon do tipo Grama. Vive com frequência em florestas, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Treecko.').
pokemon_lore(254, 'Sceptile é um Pokémon do tipo Grama. Vive com frequência em florestas, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Grovyle.').
pokemon_lore(255, 'Torchic é um Pokémon do tipo Fogo. Vive com frequência em campos abertos, com aparência avermelhada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(256, 'Combusken é um Pokémon do tipo Fogo/Lutador. Vive com frequência em campos abertos, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Torchic.').
pokemon_lore(257, 'Blaziken é um Pokémon do tipo Fogo/Lutador. Vive com frequência em campos abertos, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Combusken.').
pokemon_lore(258, 'Mudkip é um Pokémon do tipo Água. Vive com frequência em margens de rios e lagos, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(259, 'Marshtomp é um Pokémon do tipo Água/Terra. Vive com frequência em margens de rios e lagos, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Mudkip.').
pokemon_lore(260, 'Swampert é um Pokémon do tipo Água/Terra. Vive com frequência em margens de rios e lagos, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Marshtomp.').
pokemon_lore(261, 'Poochyena é um Pokémon do tipo Sombrio. Vive com frequência em campos abertos, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(262, 'Mightyena é um Pokémon do tipo Sombrio. Vive com frequência em campos abertos, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Poochyena.').
pokemon_lore(263, 'Zigzagoon é um Pokémon do tipo Normal. Vive com frequência em campos abertos, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(264, 'Linoone é um Pokémon do tipo Normal. Vive com frequência em campos abertos, com aparência clara e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Zigzagoon.').
pokemon_lore(265, 'Wurmple é um Pokémon do tipo Inseto. Vive com frequência em florestas, com aparência avermelhada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(266, 'Silcoon é um Pokémon do tipo Inseto. Vive com frequência em florestas, com aparência clara e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Wurmple.').
pokemon_lore(267, 'Beautifly é um Pokémon do tipo Inseto/Voador. Vive com frequência em florestas, com aparência amarelada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Silcoon.').
pokemon_lore(268, 'Cascoon é um Pokémon do tipo Inseto. Vive com frequência em florestas, com aparência arroxeada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Wurmple.').
pokemon_lore(269, 'Dustox é um Pokémon do tipo Inseto/Veneno. Vive com frequência em florestas, com aparência esverdeada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Cascoon.').
pokemon_lore(270, 'Lotad é um Pokémon do tipo Água/Grama. Vive com frequência em margens de rios e lagos, com aparência esverdeada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(271, 'Lombre é um Pokémon do tipo Água/Grama. Vive com frequência em margens de rios e lagos, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Lotad.').
pokemon_lore(272, 'Ludicolo é um Pokémon do tipo Água/Grama. Vive com frequência em margens de rios e lagos, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Lombre.').
pokemon_lore(273, 'Seedot é um Pokémon do tipo Grama. Vive com frequência em florestas, com aparência amarronzada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(274, 'Nuzleaf é um Pokémon do tipo Grama/Sombrio. Vive com frequência em florestas, com aparência amarronzada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Seedot.').
pokemon_lore(275, 'Shiftry é um Pokémon do tipo Grama/Sombrio. Vive com frequência em florestas, com aparência amarronzada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Nuzleaf.').
pokemon_lore(276, 'Taillow é um Pokémon do tipo Normal/Voador. Vive com frequência em campos abertos, com aparência azulada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(277, 'Swellow é um Pokémon do tipo Normal/Voador. Vive com frequência em campos abertos, com aparência azulada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Taillow.').
pokemon_lore(278, 'Wingull é um Pokémon do tipo Água/Voador. Vive com frequência em mares e oceanos, com aparência clara e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(279, 'Pelipper é um Pokémon do tipo Água/Voador. Vive com frequência em mares e oceanos, com aparência amarelada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Wingull.').
pokemon_lore(280, 'Ralts é um Pokémon do tipo Psíquico/Fada. Vive com frequência em areas urbanas, com aparência clara e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(281, 'Kirlia é um Pokémon do tipo Psíquico/Fada. Vive com frequência em areas urbanas, com aparência clara e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Ralts.').
pokemon_lore(282, 'Gardevoir é um Pokémon do tipo Psíquico/Fada. Vive com frequência em areas urbanas, com aparência clara e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Kirlia.').
pokemon_lore(283, 'Surskit é um Pokémon do tipo Inseto/Água. Vive com frequência em margens de rios e lagos, com aparência azulada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(284, 'Masquerain é um Pokémon do tipo Inseto/Voador. Vive com frequência em margens de rios e lagos, com aparência azulada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Surskit.').
pokemon_lore(285, 'Shroomish é um Pokémon do tipo Grama. Vive com frequência em florestas, com aparência amarronzada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(286, 'Breloom é um Pokémon do tipo Grama/Lutador. Vive com frequência em florestas, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Shroomish.').
pokemon_lore(287, 'Slakoth é um Pokémon do tipo Normal. Vive com frequência em florestas, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(288, 'Vigoroth é um Pokémon do tipo Normal. Vive com frequência em florestas, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Slakoth.').
pokemon_lore(289, 'Slaking é um Pokémon do tipo Normal. Vive com frequência em florestas, com aparência amarronzada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Vigoroth.').
pokemon_lore(290, 'Nincada é um Pokémon do tipo Inseto/Terra. Vive com frequência em florestas, com aparência acinzentada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(291, 'Ninjask é um Pokémon do tipo Inseto/Voador. Vive com frequência em florestas, com aparência amarelada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Nincada.').
pokemon_lore(292, 'Shedinja é um Pokémon do tipo Inseto/Fantasma. Vive com frequência em florestas, com aparência amarronzada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Nincada.').
pokemon_lore(293, 'Whismur é um Pokémon do tipo Normal. Vive com frequência em cavernas, com aparência rosada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(294, 'Loudred é um Pokémon do tipo Normal. Vive com frequência em cavernas, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Whismur.').
pokemon_lore(295, 'Exploud é um Pokémon do tipo Normal. Vive com frequência em cavernas, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Loudred.').
pokemon_lore(296, 'Makuhita é um Pokémon do tipo Lutador. Vive com frequência em regioes montanhosas, com aparência amarelada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(297, 'Hariyama é um Pokémon do tipo Lutador. Vive com frequência em regioes montanhosas, com aparência amarronzada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Makuhita.').
pokemon_lore(298, 'Azurill é um Pokémon do tipo Normal/Fada. Vive com frequência em margens de rios e lagos, com aparência azulada e postura bípede. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(299, 'Nosepass é um Pokémon do tipo Pedra. Vive com frequência em cavernas, com aparência acinzentada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(300, 'Skitty é um Pokémon do tipo Normal. Vive com frequência em florestas, com aparência rosada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(301, 'Delcatty é um Pokémon do tipo Normal. Vive com frequência em florestas, com aparência arroxeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Skitty.').
pokemon_lore(302, 'Sableye é um Pokémon do tipo Sombrio/Fantasma. Vive com frequência em cavernas, com aparência arroxeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(303, 'Mawile é um Pokémon do tipo Aço/Fada. Vive com frequência em cavernas, com aparência escura e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(304, 'Aron é um Pokémon do tipo Aço/Pedra. Vive com frequência em regioes montanhosas, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(305, 'Lairon é um Pokémon do tipo Aço/Pedra. Vive com frequência em regioes montanhosas, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Aron.').
pokemon_lore(306, 'Aggron é um Pokémon do tipo Aço/Pedra. Vive com frequência em regioes montanhosas, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Lairon.').
pokemon_lore(307, 'Meditite é um Pokémon do tipo Lutador/Psíquico. Vive com frequência em regioes montanhosas, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(308, 'Medicham é um Pokémon do tipo Lutador/Psíquico. Vive com frequência em regioes montanhosas, com aparência avermelhada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Meditite.').
pokemon_lore(309, 'Electrike é um Pokémon do tipo Elétrico. Vive com frequência em campos abertos, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(310, 'Manectric é um Pokémon do tipo Elétrico. Vive com frequência em campos abertos, com aparência amarelada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Electrike.').
pokemon_lore(311, 'Plusle é um Pokémon do tipo Elétrico. Vive com frequência em campos abertos, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(312, 'Minun é um Pokémon do tipo Elétrico. Vive com frequência em campos abertos, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(313, 'Volbeat é um Pokémon do tipo Inseto. Vive com frequência em florestas, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(314, 'Illumise é um Pokémon do tipo Inseto. Vive com frequência em florestas, com aparência arroxeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(315, 'Roselia é um Pokémon do tipo Grama/Veneno. Vive com frequência em campos abertos, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Budew.').
pokemon_lore(316, 'Gulpin é um Pokémon do tipo Veneno. Vive com frequência em campos abertos, com aparência esverdeada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(317, 'Swalot é um Pokémon do tipo Veneno. Vive com frequência em campos abertos, com aparência arroxeada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Gulpin.').
pokemon_lore(318, 'Carvanha é um Pokémon do tipo Água/Sombrio. Vive com frequência em mares e oceanos, com aparência avermelhada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(319, 'Sharpedo é um Pokémon do tipo Água/Sombrio. Vive com frequência em mares e oceanos, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Carvanha.').
pokemon_lore(320, 'Wailmer é um Pokémon do tipo Água. Vive com frequência em mares e oceanos, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(321, 'Wailord é um Pokémon do tipo Água. Vive com frequência em mares e oceanos, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Wailmer.').
pokemon_lore(322, 'Numel é um Pokémon do tipo Fogo/Terra. Vive com frequência em regioes montanhosas, com aparência amarelada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(323, 'Camerupt é um Pokémon do tipo Fogo/Terra. Vive com frequência em regioes montanhosas, com aparência avermelhada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Numel.').
pokemon_lore(324, 'Torkoal é um Pokémon do tipo Fogo. Vive com frequência em regioes montanhosas, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(325, 'Spoink é um Pokémon do tipo Psíquico. Vive com frequência em regioes montanhosas, com aparência escura e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(326, 'Grumpig é um Pokémon do tipo Psíquico. Vive com frequência em regioes montanhosas, com aparência arroxeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Spoink.').
pokemon_lore(327, 'Spinda é um Pokémon do tipo Normal. Vive com frequência em regioes montanhosas, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(328, 'Trapinch é um Pokémon do tipo Terra. Vive com frequência em terrenos acidentados, com aparência amarronzada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(329, 'Vibrava é um Pokémon do tipo Terra/Dragão. Vive com frequência em terrenos acidentados, com aparência esverdeada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Trapinch.').
pokemon_lore(330, 'Flygon é um Pokémon do tipo Terra/Dragão. Vive com frequência em terrenos acidentados, com aparência esverdeada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Vibrava.').
pokemon_lore(331, 'Cacnea é um Pokémon do tipo Grama. Vive com frequência em terrenos acidentados, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(332, 'Cacturne é um Pokémon do tipo Grama/Sombrio. Vive com frequência em terrenos acidentados, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Cacnea.').
pokemon_lore(333, 'Swablu é um Pokémon do tipo Normal/Voador. Vive com frequência em florestas, com aparência azulada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(334, 'Altaria é um Pokémon do tipo Dragão/Voador. Vive com frequência em florestas, com aparência azulada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Swablu.').
pokemon_lore(335, 'Zangoose é um Pokémon do tipo Normal. Vive com frequência em campos abertos, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(336, 'Seviper é um Pokémon do tipo Veneno. Vive com frequência em campos abertos, com aparência escura e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(337, 'Lunatone é um Pokémon do tipo Pedra/Psíquico. Vive com frequência em cavernas, com aparência amarelada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(338, 'Solrock é um Pokémon do tipo Pedra/Psíquico. Vive com frequência em cavernas, com aparência avermelhada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(339, 'Barboach é um Pokémon do tipo Água/Terra. Vive com frequência em margens de rios e lagos, com aparência acinzentada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(340, 'Whiscash é um Pokémon do tipo Água/Terra. Vive com frequência em margens de rios e lagos, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Barboach.').
pokemon_lore(341, 'Corphish é um Pokémon do tipo Água. Vive com frequência em margens de rios e lagos, com aparência avermelhada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(342, 'Crawdaunt é um Pokémon do tipo Água/Sombrio. Vive com frequência em margens de rios e lagos, com aparência avermelhada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Corphish.').
pokemon_lore(343, 'Baltoy é um Pokémon do tipo Terra/Psíquico. Vive com frequência em terrenos acidentados, com aparência amarronzada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(344, 'Claydol é um Pokémon do tipo Terra/Psíquico. Vive com frequência em terrenos acidentados, com aparência escura e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Baltoy.').
pokemon_lore(345, 'Lileep é um Pokémon do tipo Pedra/Grama. Vive com frequência em mares e oceanos, com aparência arroxeada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(346, 'Cradily é um Pokémon do tipo Pedra/Grama. Vive com frequência em mares e oceanos, com aparência esverdeada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Lileep.').
pokemon_lore(347, 'Anorith é um Pokémon do tipo Pedra/Inseto. Vive com frequência em margens de rios e lagos, com aparência acinzentada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(348, 'Armaldo é um Pokémon do tipo Pedra/Inseto. Vive com frequência em margens de rios e lagos, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Anorith.').
pokemon_lore(349, 'Feebas é um Pokémon do tipo Água. Vive com frequência em margens de rios e lagos, com aparência amarronzada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(350, 'Milotic é um Pokémon do tipo Água. Vive com frequência em margens de rios e lagos, com aparência rosada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Feebas.').
pokemon_lore(351, 'Castform é um Pokémon do tipo Normal. Vive com frequência em campos abertos, com aparência acinzentada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(352, 'Kecleon é um Pokémon do tipo Normal. Vive com frequência em florestas, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(353, 'Shuppet é um Pokémon do tipo Fantasma. Vive com frequência em areas urbanas, com aparência escura e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(354, 'Banette é um Pokémon do tipo Fantasma. Vive com frequência em areas urbanas, com aparência escura e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Shuppet.').
pokemon_lore(355, 'Duskull é um Pokémon do tipo Fantasma. Vive com frequência em florestas, com aparência escura e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(356, 'Dusclops é um Pokémon do tipo Fantasma. Vive com frequência em florestas, com aparência escura e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Duskull.').
pokemon_lore(357, 'Tropius é um Pokémon do tipo Grama/Voador. Vive com frequência em florestas, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(358, 'Chimecho é um Pokémon do tipo Psíquico. Vive com frequência em campos abertos, com aparência azulada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Chingling.').
pokemon_lore(359, 'Absol é um Pokémon do tipo Sombrio. Vive com frequência em regioes montanhosas, com aparência clara e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(360, 'Wynaut é um Pokémon do tipo Psíquico. Vive com frequência em cavernas, com aparência azulada e postura ereta. É uma forma infantil, geralmente dependente de cuidados e com comportamento mais delicado. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(361, 'Snorunt é um Pokémon do tipo Gelo. Vive com frequência em cavernas, com aparência acinzentada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(362, 'Glalie é um Pokémon do tipo Gelo. Vive com frequência em cavernas, com aparência acinzentada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Snorunt.').
pokemon_lore(363, 'Spheal é um Pokémon do tipo Gelo/Água. Vive com frequência em mares e oceanos, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(364, 'Sealeo é um Pokémon do tipo Gelo/Água. Vive com frequência em mares e oceanos, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Spheal.').
pokemon_lore(365, 'Walrein é um Pokémon do tipo Gelo/Água. Vive com frequência em mares e oceanos, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sealeo.').
pokemon_lore(366, 'Clamperl é um Pokémon do tipo Água. Vive com frequência em mares e oceanos, com aparência azulada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(367, 'Huntail é um Pokémon do tipo Água. Vive com frequência em mares e oceanos, com aparência azulada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Clamperl.').
pokemon_lore(368, 'Gorebyss é um Pokémon do tipo Água. Vive com frequência em mares e oceanos, com aparência rosada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Clamperl.').
pokemon_lore(369, 'Relicanth é um Pokémon do tipo Água/Pedra. Vive com frequência em mares e oceanos, com aparência acinzentada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(370, 'Luvdisc é um Pokémon do tipo Água. Vive com frequência em mares e oceanos, com aparência rosada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(371, 'Bagon é um Pokémon do tipo Dragão. Vive com frequência em terrenos acidentados, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(372, 'Shelgon é um Pokémon do tipo Dragão. Vive com frequência em terrenos acidentados, com aparência clara e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Bagon.').
pokemon_lore(373, 'Salamence é um Pokémon do tipo Dragão/Voador. Vive com frequência em terrenos acidentados, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Shelgon.').
pokemon_lore(374, 'Beldum é um Pokémon do tipo Aço/Psíquico. Vive com frequência em terrenos acidentados, com aparência azulada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(375, 'Metang é um Pokémon do tipo Aço/Psíquico. Vive com frequência em terrenos acidentados, com aparência azulada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Beldum.').
pokemon_lore(376, 'Metagross é um Pokémon do tipo Aço/Psíquico. Vive com frequência em terrenos acidentados, com aparência azulada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Metang.').
pokemon_lore(377, 'Regirock é um Pokémon do tipo Pedra. Vive com frequência em cavernas, com aparência amarronzada e aparencia humanoide. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(378, 'Regice é um Pokémon do tipo Gelo. Vive com frequência em cavernas, com aparência azulada e aparencia humanoide. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(379, 'Registeel é um Pokémon do tipo Aço. Vive com frequência em cavernas, com aparência acinzentada e aparencia humanoide. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(380, 'Latias é um Pokémon do tipo Dragão/Psíquico. Vive com frequência em margens de rios e lagos, com aparência avermelhada e corpo com asas. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(381, 'Latios é um Pokémon do tipo Dragão/Psíquico. Vive com frequência em margens de rios e lagos, com aparência azulada e corpo com asas. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(382, 'Kyogre é um Pokémon do tipo Água. Vive com frequência em mares e oceanos, com aparência azulada e corpo de peixe. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(383, 'Groudon é um Pokémon do tipo Terra. Vive com frequência em terrenos acidentados, com aparência avermelhada e postura ereta. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(384, 'Rayquaza é um Pokémon do tipo Dragão/Voador. Vive com frequência em locais raros e pouco acessiveis, com aparência esverdeada e corpo serpentino. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(385, 'Jirachi é um Pokémon do tipo Aço/Psíquico. Vive com frequência em regioes montanhosas, com aparência amarelada e aparencia humanoide. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(386, 'Deoxys Normal é um Pokémon do tipo Psíquico. Vive com frequência em locais raros e pouco acessiveis, com aparência avermelhada e aparencia humanoide. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
