:- encoding(utf8).
% Lore local da geracao 9
% Formato: pokemon_lore(ID, Texto).
:- multifile pokemon_lore/2.
pokemon_lore(906, 'Sprigatito é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(907, 'Floragato é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sprigatito.').
pokemon_lore(908, 'Meowscarada é um Pokémon do tipo Grama/Sombrio. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Floragato.').
pokemon_lore(909, 'Fuecoco é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(910, 'Crocalor é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Fuecoco.').
pokemon_lore(911, 'Skeledirge é um Pokémon do tipo Fogo/Fantasma. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Crocalor.').
pokemon_lore(912, 'Quaxly é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(913, 'Quaxwell é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Quaxly.').
pokemon_lore(914, 'Quaquaval é um Pokémon do tipo Água/Lutador. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Quaxwell.').
pokemon_lore(915, 'Lechonk é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(916, 'Oinkologne Male é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Lechonk.').
pokemon_lore(917, 'Tarountula é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência clara e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(918, 'Spidops é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tarountula.').
pokemon_lore(919, 'Nymble é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(920, 'Lokix é um Pokémon do tipo Inseto/Sombrio. Vive com frequência em habitat pouco documentado, com aparência acinzentada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Nymble.').
pokemon_lore(921, 'Pawmi é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(922, 'Pawmo é um Pokémon do tipo Elétrico/Lutador. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Pawmi.').
pokemon_lore(923, 'Pawmot é um Pokémon do tipo Elétrico/Lutador. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Pawmo.').
pokemon_lore(924, 'Tandemaus é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência clara e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(925, 'Maushold Family Of Four é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência clara e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tandemaus.').
pokemon_lore(926, 'Fidough é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(927, 'Dachsbun é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Fidough.').
pokemon_lore(928, 'Smoliv é um Pokémon do tipo Grama/Normal. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(929, 'Dolliv é um Pokémon do tipo Grama/Normal. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Smoliv.').
pokemon_lore(930, 'Arboliva é um Pokémon do tipo Grama/Normal. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Dolliv.').
pokemon_lore(931, 'Squawkabilly Green Plumage é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(932, 'Nacli é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(933, 'Naclstack é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Nacli.').
pokemon_lore(934, 'Garganacl é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Naclstack.').
pokemon_lore(935, 'Charcadet é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(936, 'Armarouge é um Pokémon do tipo Fogo/Psíquico. Vive com frequência em habitat pouco documentado, com aparência avermelhada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Charcadet.').
pokemon_lore(937, 'Ceruledge é um Pokémon do tipo Fogo/Fantasma. Vive com frequência em habitat pouco documentado, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Charcadet.').
pokemon_lore(938, 'Tadbulb é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência amarelada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(939, 'Bellibolt é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tadbulb.').
pokemon_lore(940, 'Wattrel é um Pokémon do tipo Elétrico/Voador. Vive com frequência em habitat pouco documentado, com aparência escura e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(941, 'Kilowattrel é um Pokémon do tipo Elétrico/Voador. Vive com frequência em habitat pouco documentado, com aparência amarelada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Wattrel.').
pokemon_lore(942, 'Maschiff é um Pokémon do tipo Sombrio. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(943, 'Mabosstiff é um Pokémon do tipo Sombrio. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Maschiff.').
pokemon_lore(944, 'Shroodle é um Pokémon do tipo Veneno/Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(945, 'Grafaiai é um Pokémon do tipo Veneno/Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Shroodle.').
pokemon_lore(946, 'Bramblin é um Pokémon do tipo Grama/Fantasma. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(947, 'Brambleghast é um Pokémon do tipo Grama/Fantasma. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Bramblin.').
pokemon_lore(948, 'Toedscool é um Pokémon do tipo Terra/Grama. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(949, 'Toedscruel é um Pokémon do tipo Terra/Grama. Vive com frequência em habitat pouco documentado, com aparência escura e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Toedscool.').
pokemon_lore(950, 'Klawf é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(951, 'Capsakid é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(952, 'Scovillain é um Pokémon do tipo Grama/Fogo. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Capsakid.').
pokemon_lore(953, 'Rellor é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(954, 'Rabsca é um Pokémon do tipo Inseto/Psíquico. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Rellor.').
pokemon_lore(955, 'Flittle é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(956, 'Espathra é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Flittle.').
pokemon_lore(957, 'Tinkatink é um Pokémon do tipo Fada/Aço. Vive com frequência em habitat pouco documentado, com aparência rosada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(958, 'Tinkatuff é um Pokémon do tipo Fada/Aço. Vive com frequência em habitat pouco documentado, com aparência rosada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tinkatink.').
pokemon_lore(959, 'Tinkaton é um Pokémon do tipo Fada/Aço. Vive com frequência em habitat pouco documentado, com aparência rosada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tinkatuff.').
pokemon_lore(960, 'Wiglett é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência clara e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(961, 'Wugtrio é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência avermelhada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Wiglett.').
pokemon_lore(962, 'Bombirdier é um Pokémon do tipo Voador/Sombrio. Vive com frequência em habitat pouco documentado, com aparência clara e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(963, 'Finizen é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(964, 'Palafin Zero é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Finizen.').
pokemon_lore(965, 'Varoom é um Pokémon do tipo Aço/Veneno. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(966, 'Revavroom é um Pokémon do tipo Aço/Veneno. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Varoom.').
pokemon_lore(967, 'Cyclizar é um Pokémon do tipo Dragão/Normal. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(968, 'Orthworm é um Pokémon do tipo Aço. Vive com frequência em habitat pouco documentado, com aparência rosada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(969, 'Glimmet é um Pokémon do tipo Pedra/Veneno. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(970, 'Glimmora é um Pokémon do tipo Pedra/Veneno. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Glimmet.').
pokemon_lore(971, 'Greavard é um Pokémon do tipo Fantasma. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(972, 'Houndstone é um Pokémon do tipo Fantasma. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Greavard.').
pokemon_lore(973, 'Flamigo é um Pokémon do tipo Voador/Lutador. Vive com frequência em habitat pouco documentado, com aparência rosada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(974, 'Cetoddle é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(975, 'Cetitan é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Cetoddle.').
pokemon_lore(976, 'Veluza é um Pokémon do tipo Água/Psíquico. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(977, 'Dondozo é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(978, 'Tatsugiri Curly é um Pokémon do tipo Dragão/Água. Vive com frequência em habitat pouco documentado, com aparência rosada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(979, 'Annihilape é um Pokémon do tipo Lutador/Fantasma. Vive com frequência em habitat pouco documentado, com aparência acinzentada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Primeape.').
pokemon_lore(980, 'Clodsire é um Pokémon do tipo Veneno/Terra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Wooper.').
pokemon_lore(981, 'Farigiraf é um Pokémon do tipo Normal/Psíquico. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Girafarig.').
pokemon_lore(982, 'Dudunsparce Two Segment é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarelada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Dunsparce.').
pokemon_lore(983, 'Kingambit é um Pokémon do tipo Sombrio/Aço. Vive com frequência em habitat pouco documentado, com aparência escura e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Bisharp.').
pokemon_lore(984, 'Great Tusk é um Pokémon do tipo Terra/Lutador. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(985, 'Scream Tail é um Pokémon do tipo Fada/Psíquico. Vive com frequência em habitat pouco documentado, com aparência rosada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(986, 'Brute Bonnet é um Pokémon do tipo Grama/Sombrio. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(987, 'Flutter Mane é um Pokémon do tipo Fantasma/Fada. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(988, 'Slither Wing é um Pokémon do tipo Inseto/Lutador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(989, 'Sandy Shocks é um Pokémon do tipo Elétrico/Terra. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(990, 'Iron Treads é um Pokémon do tipo Terra/Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(991, 'Iron Bundle é um Pokémon do tipo Gelo/Água. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(992, 'Iron Hands é um Pokémon do tipo Lutador/Elétrico. Vive com frequência em habitat pouco documentado, com aparência acinzentada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(993, 'Iron Jugulis é um Pokémon do tipo Sombrio/Voador. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(994, 'Iron Moth é um Pokémon do tipo Fogo/Veneno. Vive com frequência em habitat pouco documentado, com aparência amarelada e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(995, 'Iron Thorns é um Pokémon do tipo Pedra/Elétrico. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(996, 'Frigibax é um Pokémon do tipo Dragão/Gelo. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(997, 'Arctibax é um Pokémon do tipo Dragão/Gelo. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Frigibax.').
pokemon_lore(998, 'Baxcalibur é um Pokémon do tipo Dragão/Gelo. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Arctibax.').
pokemon_lore(999, 'Gimmighoul é um Pokémon do tipo Fantasma. Vive com frequência em habitat pouco documentado, com aparência amarronzada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1000, 'Gholdengo é um Pokémon do tipo Aço/Fantasma. Vive com frequência em habitat pouco documentado, com aparência amarelada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Gimmighoul.').
pokemon_lore(1001, 'Wo Chien é um Pokémon do tipo Sombrio/Grama. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo serpentino. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1002, 'Chien Pao é um Pokémon do tipo Sombrio/Gelo. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1003, 'Ting Lu é um Pokémon do tipo Sombrio/Terra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1004, 'Chi Yu é um Pokémon do tipo Sombrio/Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo de peixe. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1005, 'Roaring Moon é um Pokémon do tipo Dragão/Sombrio. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1006, 'Iron Valiant é um Pokémon do tipo Fada/Lutador. Vive com frequência em habitat pouco documentado, com aparência clara e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1007, 'Koraidon é um Pokémon do tipo Lutador/Dragão. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1008, 'Miraidon é um Pokémon do tipo Elétrico/Dragão. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1009, 'Walking Wake é um Pokémon do tipo Água/Dragão. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1010, 'Iron Leaves é um Pokémon do tipo Grama/Psíquico. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1011, 'Dipplin é um Pokémon do tipo Grama/Dragão. Vive com frequência em habitat pouco documentado, com aparência esverdeada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Applin.').
pokemon_lore(1012, 'Poltchageist é um Pokémon do tipo Grama/Fantasma. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1013, 'Sinistcha é um Pokémon do tipo Grama/Fantasma. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Poltchageist.').
pokemon_lore(1014, 'Okidogi é um Pokémon do tipo Veneno/Lutador. Vive com frequência em habitat pouco documentado, com aparência escura e postura ereta. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1015, 'Munkidori é um Pokémon do tipo Veneno/Psíquico. Vive com frequência em habitat pouco documentado, com aparência escura e aparencia humanoide. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1016, 'Fezandipiti é um Pokémon do tipo Veneno/Fada. Vive com frequência em habitat pouco documentado, com aparência escura e corpo com asas. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1017, 'Ogerpon é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1018, 'Archaludon é um Pokémon do tipo Aço/Dragão. Vive com frequência em habitat pouco documentado, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Duraludon.').
pokemon_lore(1019, 'Hydrapple é um Pokémon do tipo Grama/Dragão. Vive com frequência em habitat pouco documentado, com aparência esverdeada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Dipplin.').
pokemon_lore(1020, 'Gouging Fire é um Pokémon do tipo Fogo/Dragão. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1021, 'Raging Bolt é um Pokémon do tipo Elétrico/Dragão. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1022, 'Iron Boulder é um Pokémon do tipo Pedra/Psíquico. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1023, 'Iron Crown é um Pokémon do tipo Aço/Psíquico. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1024, 'Terapagos é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(1025, 'Pecharunt é um Pokémon do tipo Veneno/Fantasma. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo arredondado. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
