:- encoding(utf8).
% Lore local da geracao 6
% Formato: pokemon_lore(ID, Texto).
:- multifile pokemon_lore/2.
pokemon_lore(650, 'Chespin é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(651, 'Quilladin é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Chespin.').
pokemon_lore(652, 'Chesnaught é um Pokémon do tipo Grama/Lutador. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Quilladin.').
pokemon_lore(653, 'Fennekin é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(654, 'Braixen é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Fennekin.').
pokemon_lore(655, 'Delphox é um Pokémon do tipo Fogo/Psíquico. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Braixen.').
pokemon_lore(656, 'Froakie é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(657, 'Frogadier é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Froakie.').
pokemon_lore(658, 'Greninja é um Pokémon do tipo Água/Sombrio. Vive com frequência em habitat pouco documentado, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Frogadier.').
pokemon_lore(659, 'Bunnelby é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(660, 'Diggersby é um Pokémon do tipo Normal/Terra. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Bunnelby.').
pokemon_lore(661, 'Fletchling é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(662, 'Fletchinder é um Pokémon do tipo Fogo/Voador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Fletchling.').
pokemon_lore(663, 'Talonflame é um Pokémon do tipo Fogo/Voador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Fletchinder.').
pokemon_lore(664, 'Scatterbug é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência escura e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(665, 'Spewpa é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência escura e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Scatterbug.').
pokemon_lore(666, 'Vivillon é um Pokémon do tipo Inseto/Voador. Vive com frequência em habitat pouco documentado, com aparência clara e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Spewpa.').
pokemon_lore(667, 'Litleo é um Pokémon do tipo Fogo/Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(668, 'Pyroar Male é um Pokémon do tipo Fogo/Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Litleo.').
pokemon_lore(669, 'Flabebe é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência clara e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(670, 'Floette é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência clara e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Flabebe.').
pokemon_lore(671, 'Florges é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência clara e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Floette.').
pokemon_lore(672, 'Skiddo é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(673, 'Gogoat é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Skiddo.').
pokemon_lore(674, 'Pancham é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(675, 'Pangoro é um Pokémon do tipo Lutador/Sombrio. Vive com frequência em habitat pouco documentado, com aparência clara e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Pancham.').
pokemon_lore(676, 'Furfrou é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(677, 'Espurr é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(678, 'Meowstic Male é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Espurr.').
pokemon_lore(679, 'Honedge é um Pokémon do tipo Aço/Fantasma. Vive com frequência em habitat pouco documentado, com aparência amarronzada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(680, 'Doublade é um Pokémon do tipo Aço/Fantasma. Vive com frequência em habitat pouco documentado, com aparência amarronzada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Honedge.').
pokemon_lore(681, 'Aegislash Shield é um Pokémon do tipo Aço/Fantasma. Vive com frequência em habitat pouco documentado, com aparência amarronzada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Doublade.').
pokemon_lore(682, 'Spritzee é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência rosada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(683, 'Aromatisse é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência rosada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Spritzee.').
pokemon_lore(684, 'Swirlix é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência clara e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(685, 'Slurpuff é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência clara e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Swirlix.').
pokemon_lore(686, 'Inkay é um Pokémon do tipo Sombrio/Psíquico. Vive com frequência em habitat pouco documentado, com aparência azulada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(687, 'Malamar é um Pokémon do tipo Sombrio/Psíquico. Vive com frequência em habitat pouco documentado, com aparência azulada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Inkay.').
pokemon_lore(688, 'Binacle é um Pokémon do tipo Pedra/Água. Vive com frequência em habitat pouco documentado, com aparência amarronzada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(689, 'Barbaracle é um Pokémon do tipo Pedra/Água. Vive com frequência em habitat pouco documentado, com aparência amarronzada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Binacle.').
pokemon_lore(690, 'Skrelp é um Pokémon do tipo Veneno/Água. Vive com frequência em habitat pouco documentado, com aparência amarronzada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(691, 'Dragalge é um Pokémon do tipo Veneno/Dragão. Vive com frequência em habitat pouco documentado, com aparência amarronzada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Skrelp.').
pokemon_lore(692, 'Clauncher é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(693, 'Clawitzer é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Clauncher.').
pokemon_lore(694, 'Helioptile é um Pokémon do tipo Elétrico/Normal. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(695, 'Heliolisk é um Pokémon do tipo Elétrico/Normal. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Helioptile.').
pokemon_lore(696, 'Tyrunt é um Pokémon do tipo Pedra/Dragão. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(697, 'Tyrantrum é um Pokémon do tipo Pedra/Dragão. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tyrunt.').
pokemon_lore(698, 'Amaura é um Pokémon do tipo Pedra/Gelo. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(699, 'Aurorus é um Pokémon do tipo Pedra/Gelo. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Amaura.').
pokemon_lore(700, 'Sylveon é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência rosada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Eevee.').
pokemon_lore(701, 'Hawlucha é um Pokémon do tipo Lutador/Voador. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(702, 'Dedenne é um Pokémon do tipo Elétrico/Fada. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(703, 'Carbink é um Pokémon do tipo Pedra/Fada. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(704, 'Goomy é um Pokémon do tipo Dragão. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(705, 'Sliggoo é um Pokémon do tipo Dragão. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Goomy.').
pokemon_lore(706, 'Goodra é um Pokémon do tipo Dragão. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sliggoo.').
pokemon_lore(707, 'Klefki é um Pokémon do tipo Aço/Fada. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(708, 'Phantump é um Pokémon do tipo Fantasma/Grama. Vive com frequência em habitat pouco documentado, com aparência amarronzada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(709, 'Trevenant é um Pokémon do tipo Fantasma/Grama. Vive com frequência em habitat pouco documentado, com aparência amarronzada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Phantump.').
pokemon_lore(710, 'Pumpkaboo Average é um Pokémon do tipo Fantasma/Grama. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(711, 'Gourgeist Average é um Pokémon do tipo Fantasma/Grama. Vive com frequência em habitat pouco documentado, com aparência amarronzada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Pumpkaboo.').
pokemon_lore(712, 'Bergmite é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(713, 'Avalugg é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Bergmite.').
pokemon_lore(714, 'Noibat é um Pokémon do tipo Voador/Dragão. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(715, 'Noivern é um Pokémon do tipo Voador/Dragão. Vive com frequência em habitat pouco documentado, com aparência arroxeada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Noibat.').
pokemon_lore(716, 'Xerneas é um Pokémon do tipo Fada. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(717, 'Yveltal é um Pokémon do tipo Sombrio/Voador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo com asas. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(718, 'Zygarde 50 é um Pokémon do tipo Dragão/Terra. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo serpentino. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(719, 'Diancie é um Pokémon do tipo Pedra/Fada. Vive com frequência em habitat pouco documentado, com aparência rosada e forma com bracos marcantes. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(720, 'Hoopa é um Pokémon do tipo Psíquico/Fantasma. Vive com frequência em habitat pouco documentado, com aparência arroxeada e forma com bracos marcantes. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(721, 'Volcanion é um Pokémon do tipo Fogo/Água. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
