:- encoding(utf8).
% Lore local da geracao 5
% Formato: pokemon_lore(ID, Texto).
:- multifile pokemon_lore/2.
pokemon_lore(494, 'Victini é um Pokémon do tipo Psíquico/Fogo. Vive com frequência em habitat pouco documentado, com aparência amarelada e aparencia humanoide. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(495, 'Snivy é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(496, 'Servine é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Snivy.').
pokemon_lore(497, 'Serperior é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo serpentino. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Servine.').
pokemon_lore(498, 'Tepig é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(499, 'Pignite é um Pokémon do tipo Fogo/Lutador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tepig.').
pokemon_lore(500, 'Emboar é um Pokémon do tipo Fogo/Lutador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Pignite.').
pokemon_lore(501, 'Oshawott é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(502, 'Dewott é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Oshawott.').
pokemon_lore(503, 'Samurott é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Dewott.').
pokemon_lore(504, 'Patrat é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(505, 'Watchog é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Patrat.').
pokemon_lore(506, 'Lillipup é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(507, 'Herdier é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Lillipup.').
pokemon_lore(508, 'Stoutland é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Herdier.').
pokemon_lore(509, 'Purrloin é um Pokémon do tipo Sombrio. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(510, 'Liepard é um Pokémon do tipo Sombrio. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Purrloin.').
pokemon_lore(511, 'Pansage é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(512, 'Simisage é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Pansage.').
pokemon_lore(513, 'Pansear é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(514, 'Simisear é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Pansear.').
pokemon_lore(515, 'Panpour é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(516, 'Simipour é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Panpour.').
pokemon_lore(517, 'Munna é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência rosada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(518, 'Musharna é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência rosada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Munna.').
pokemon_lore(519, 'Pidove é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(520, 'Tranquill é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Pidove.').
pokemon_lore(521, 'Unfezant é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tranquill.').
pokemon_lore(522, 'Blitzle é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência escura e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(523, 'Zebstrika é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência escura e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Blitzle.').
pokemon_lore(524, 'Roggenrola é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência azulada e postura bípede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(525, 'Boldore é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência azulada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Roggenrola.').
pokemon_lore(526, 'Gigalith é um Pokémon do tipo Pedra. Vive com frequência em habitat pouco documentado, com aparência azulada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Boldore.').
pokemon_lore(527, 'Woobat é um Pokémon do tipo Psíquico/Voador. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(528, 'Swoobat é um Pokémon do tipo Psíquico/Voador. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Woobat.').
pokemon_lore(529, 'Drilbur é um Pokémon do tipo Terra. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(530, 'Excadrill é um Pokémon do tipo Terra/Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Drilbur.').
pokemon_lore(531, 'Audino é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência rosada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(532, 'Timburr é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência acinzentada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(533, 'Gurdurr é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência acinzentada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Timburr.').
pokemon_lore(534, 'Conkeldurr é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Gurdurr.').
pokemon_lore(535, 'Tympole é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(536, 'Palpitoad é um Pokémon do tipo Água/Terra. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tympole.').
pokemon_lore(537, 'Seismitoad é um Pokémon do tipo Água/Terra. Vive com frequência em habitat pouco documentado, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Palpitoad.').
pokemon_lore(538, 'Throh é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(539, 'Sawk é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(540, 'Sewaddle é um Pokémon do tipo Inseto/Grama. Vive com frequência em habitat pouco documentado, com aparência amarelada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(541, 'Swadloon é um Pokémon do tipo Inseto/Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sewaddle.').
pokemon_lore(542, 'Leavanny é um Pokémon do tipo Inseto/Grama. Vive com frequência em habitat pouco documentado, com aparência amarelada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Swadloon.').
pokemon_lore(543, 'Venipede é um Pokémon do tipo Inseto/Veneno. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(544, 'Whirlipede é um Pokémon do tipo Inseto/Veneno. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Venipede.').
pokemon_lore(545, 'Scolipede é um Pokémon do tipo Inseto/Veneno. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Whirlipede.').
pokemon_lore(546, 'Cottonee é um Pokémon do tipo Grama/Fada. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(547, 'Whimsicott é um Pokémon do tipo Grama/Fada. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Cottonee.').
pokemon_lore(548, 'Petilil é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(549, 'Lilligant é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Petilil.').
pokemon_lore(550, 'Basculin Red Striped é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(551, 'Sandile é um Pokémon do tipo Terra/Sombrio. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(552, 'Krokorok é um Pokémon do tipo Terra/Sombrio. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Sandile.').
pokemon_lore(553, 'Krookodile é um Pokémon do tipo Terra/Sombrio. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Krokorok.').
pokemon_lore(554, 'Darumaka é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(555, 'Darmanitan Standard é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Darumaka.').
pokemon_lore(556, 'Maractus é um Pokémon do tipo Grama. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(557, 'Dwebble é um Pokémon do tipo Inseto/Pedra. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(558, 'Crustle é um Pokémon do tipo Inseto/Pedra. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Dwebble.').
pokemon_lore(559, 'Scraggy é um Pokémon do tipo Sombrio/Lutador. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(560, 'Scrafty é um Pokémon do tipo Sombrio/Lutador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Scraggy.').
pokemon_lore(561, 'Sigilyph é um Pokémon do tipo Psíquico/Voador. Vive com frequência em habitat pouco documentado, com aparência escura e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(562, 'Yamask é um Pokémon do tipo Fantasma. Vive com frequência em habitat pouco documentado, com aparência escura e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(563, 'Cofagrigus é um Pokémon do tipo Fantasma. Vive com frequência em habitat pouco documentado, com aparência amarelada e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Yamask.').
pokemon_lore(564, 'Tirtouga é um Pokémon do tipo Água/Pedra. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(565, 'Carracosta é um Pokémon do tipo Água/Pedra. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tirtouga.').
pokemon_lore(566, 'Archen é um Pokémon do tipo Pedra/Voador. Vive com frequência em habitat pouco documentado, com aparência amarelada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(567, 'Archeops é um Pokémon do tipo Pedra/Voador. Vive com frequência em habitat pouco documentado, com aparência amarelada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Archen.').
pokemon_lore(568, 'Trubbish é um Pokémon do tipo Veneno. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(569, 'Garbodor é um Pokémon do tipo Veneno. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Trubbish.').
pokemon_lore(570, 'Zorua é um Pokémon do tipo Sombrio. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(571, 'Zoroark é um Pokémon do tipo Sombrio. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Zorua.').
pokemon_lore(572, 'Minccino é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(573, 'Cinccino é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Minccino.').
pokemon_lore(574, 'Gothita é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência arroxeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(575, 'Gothorita é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência arroxeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Gothita.').
pokemon_lore(576, 'Gothitelle é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência arroxeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Gothorita.').
pokemon_lore(577, 'Solosis é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(578, 'Duosion é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência esverdeada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Solosis.').
pokemon_lore(579, 'Reuniclus é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Duosion.').
pokemon_lore(580, 'Ducklett é um Pokémon do tipo Água/Voador. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(581, 'Swanna é um Pokémon do tipo Água/Voador. Vive com frequência em habitat pouco documentado, com aparência clara e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Ducklett.').
pokemon_lore(582, 'Vanillite é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência clara e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(583, 'Vanillish é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência clara e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Vanillite.').
pokemon_lore(584, 'Vanilluxe é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência clara e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Vanillish.').
pokemon_lore(585, 'Deerling é um Pokémon do tipo Normal/Grama. Vive com frequência em habitat pouco documentado, com aparência rosada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(586, 'Sawsbuck é um Pokémon do tipo Normal/Grama. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Deerling.').
pokemon_lore(587, 'Emolga é um Pokémon do tipo Elétrico/Voador. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(588, 'Karrablast é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência azulada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(589, 'Escavalier é um Pokémon do tipo Inseto/Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Karrablast.').
pokemon_lore(590, 'Foongus é um Pokémon do tipo Grama/Veneno. Vive com frequência em habitat pouco documentado, com aparência clara e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(591, 'Amoonguss é um Pokémon do tipo Grama/Veneno. Vive com frequência em habitat pouco documentado, com aparência clara e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Foongus.').
pokemon_lore(592, 'Frillish Male é um Pokémon do tipo Água/Fantasma. Vive com frequência em habitat pouco documentado, com aparência clara e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(593, 'Jellicent Male é um Pokémon do tipo Água/Fantasma. Vive com frequência em habitat pouco documentado, com aparência clara e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Frillish.').
pokemon_lore(594, 'Alomomola é um Pokémon do tipo Água. Vive com frequência em habitat pouco documentado, com aparência rosada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(595, 'Joltik é um Pokémon do tipo Inseto/Elétrico. Vive com frequência em habitat pouco documentado, com aparência amarelada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(596, 'Galvantula é um Pokémon do tipo Inseto/Elétrico. Vive com frequência em habitat pouco documentado, com aparência amarelada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Joltik.').
pokemon_lore(597, 'Ferroseed é um Pokémon do tipo Grama/Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(598, 'Ferrothorn é um Pokémon do tipo Grama/Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e forma com tentaculos. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Ferroseed.').
pokemon_lore(599, 'Klink é um Pokémon do tipo Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(600, 'Klang é um Pokémon do tipo Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Klink.').
pokemon_lore(601, 'Klinklang é um Pokémon do tipo Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e estrutura com multiplas cabecas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Klang.').
pokemon_lore(602, 'Tynamo é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência clara e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(603, 'Eelektrik é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Tynamo.').
pokemon_lore(604, 'Eelektross é um Pokémon do tipo Elétrico. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Eelektrik.').
pokemon_lore(605, 'Elgyem é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(606, 'Beheeyem é um Pokémon do tipo Psíquico. Vive com frequência em habitat pouco documentado, com aparência amarronzada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Elgyem.').
pokemon_lore(607, 'Litwick é um Pokémon do tipo Fantasma/Fogo. Vive com frequência em habitat pouco documentado, com aparência clara e forma amorfa. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(608, 'Lampent é um Pokémon do tipo Fantasma/Fogo. Vive com frequência em habitat pouco documentado, com aparência escura e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Litwick.').
pokemon_lore(609, 'Chandelure é um Pokémon do tipo Fantasma/Fogo. Vive com frequência em habitat pouco documentado, com aparência escura e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Lampent.').
pokemon_lore(610, 'Axew é um Pokémon do tipo Dragão. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(611, 'Fraxure é um Pokémon do tipo Dragão. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Axew.').
pokemon_lore(612, 'Haxorus é um Pokémon do tipo Dragão. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Fraxure.').
pokemon_lore(613, 'Cubchoo é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência clara e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(614, 'Beartic é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência clara e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Cubchoo.').
pokemon_lore(615, 'Cryogonal é um Pokémon do tipo Gelo. Vive com frequência em habitat pouco documentado, com aparência azulada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(616, 'Shelmet é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo arredondado. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(617, 'Accelgor é um Pokémon do tipo Inseto. Vive com frequência em habitat pouco documentado, com aparência avermelhada e forma com bracos marcantes. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Shelmet.').
pokemon_lore(618, 'Stunfisk é um Pokémon do tipo Terra/Elétrico. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo de peixe. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(619, 'Mienfoo é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(620, 'Mienshao é um Pokémon do tipo Lutador. Vive com frequência em habitat pouco documentado, com aparência arroxeada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Mienfoo.').
pokemon_lore(621, 'Druddigon é um Pokémon do tipo Dragão. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(622, 'Golett é um Pokémon do tipo Terra/Fantasma. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(623, 'Golurk é um Pokémon do tipo Terra/Fantasma. Vive com frequência em habitat pouco documentado, com aparência esverdeada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Golett.').
pokemon_lore(624, 'Pawniard é um Pokémon do tipo Sombrio/Aço. Vive com frequência em habitat pouco documentado, com aparência avermelhada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(625, 'Bisharp é um Pokémon do tipo Sombrio/Aço. Vive com frequência em habitat pouco documentado, com aparência avermelhada e aparencia humanoide. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Pawniard.').
pokemon_lore(626, 'Bouffalant é um Pokémon do tipo Normal. Vive com frequência em habitat pouco documentado, com aparência amarronzada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(627, 'Rufflet é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência clara e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(628, 'Braviary é um Pokémon do tipo Normal/Voador. Vive com frequência em habitat pouco documentado, com aparência avermelhada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Rufflet.').
pokemon_lore(629, 'Vullaby é um Pokémon do tipo Sombrio/Voador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(630, 'Mandibuzz é um Pokémon do tipo Sombrio/Voador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e corpo com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Vullaby.').
pokemon_lore(631, 'Heatmor é um Pokémon do tipo Fogo. Vive com frequência em habitat pouco documentado, com aparência avermelhada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(632, 'Durant é um Pokémon do tipo Inseto/Aço. Vive com frequência em habitat pouco documentado, com aparência acinzentada e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(633, 'Deino é um Pokémon do tipo Sombrio/Dragão. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(634, 'Zweilous é um Pokémon do tipo Sombrio/Dragão. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Deino.').
pokemon_lore(635, 'Hydreigon é um Pokémon do tipo Sombrio/Dragão. Vive com frequência em habitat pouco documentado, com aparência azulada e postura ereta. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Zweilous.').
pokemon_lore(636, 'Larvesta é um Pokémon do tipo Inseto/Fogo. Vive com frequência em habitat pouco documentado, com aparência clara e corpo com aspecto de armadura. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(637, 'Volcarona é um Pokémon do tipo Inseto/Fogo. Vive com frequência em habitat pouco documentado, com aparência clara e estrutura de inseto com asas. É considerado uma espécie comum de se observar na sua região. Sua linhagem evolutiva parte de Larvesta.').
pokemon_lore(638, 'Cobalion é um Pokémon do tipo Aço/Lutador. Vive com frequência em habitat pouco documentado, com aparência azulada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(639, 'Terrakion é um Pokémon do tipo Pedra/Lutador. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(640, 'Virizion é um Pokémon do tipo Grama/Lutador. Vive com frequência em habitat pouco documentado, com aparência esverdeada e postura quadrupede. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(641, 'Tornadus Incarnate é um Pokémon do tipo Voador. Vive com frequência em habitat pouco documentado, com aparência esverdeada e forma com bracos marcantes. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(642, 'Thundurus Incarnate é um Pokémon do tipo Elétrico/Voador. Vive com frequência em habitat pouco documentado, com aparência azulada e forma com bracos marcantes. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(643, 'Reshiram é um Pokémon do tipo Dragão/Fogo. Vive com frequência em habitat pouco documentado, com aparência clara e corpo com asas. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(644, 'Zekrom é um Pokémon do tipo Dragão/Elétrico. Vive com frequência em habitat pouco documentado, com aparência escura e postura ereta. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(645, 'Landorus Incarnate é um Pokémon do tipo Terra/Voador. Vive com frequência em habitat pouco documentado, com aparência amarronzada e forma com bracos marcantes. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(646, 'Kyurem é um Pokémon do tipo Dragão/Gelo. Vive com frequência em habitat pouco documentado, com aparência acinzentada e postura ereta. É classificado como Pokémon lendário e aparece em poucos registros confiáveis. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(647, 'Keldeo Ordinary é um Pokémon do tipo Água/Lutador. Vive com frequência em habitat pouco documentado, com aparência amarelada e postura quadrupede. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(648, 'Meloetta Aria é um Pokémon do tipo Normal/Psíquico. Vive com frequência em habitat pouco documentado, com aparência clara e aparencia humanoide. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
pokemon_lore(649, 'Genesect é um Pokémon do tipo Inseto/Aço. Vive com frequência em habitat pouco documentado, com aparência arroxeada e aparencia humanoide. É classificado como Pokémon mítico, cercado por relatos raros e misteriosos. Sua linhagem evolutiva começa nesta forma.').
