:- encoding(utf8).

show_help :-
    writeln('Bot: Exemplos de uso:'),
    writeln('  1) info nome pikachu'),
    writeln('  2) info numero 25'),
    writeln('  3) pokemon charizard'),
    writeln('  4) tipo fogo'),
    writeln('  5) quantos pokemon existem do tipo grama'),
    writeln('  6) 25  (numero direto)'),
    writeln('  7) pokemon #25'),
    writeln('  8) geracao 1'),
    writeln('  9) geracao todas'),
    writeln(' 10) tipo fogo/voador'),
    writeln(' 11) habilidade blaze'),
    writeln(' 12) status velocidade'),
    writeln(' 13) status velocidade completo'),
    writeln(' 14) pokemon charizard mega x'),
    writeln(' 15) qual é um bom pokemon contra charizard'),
    writeln(' 16) quem ganha entre charizard e blastoise'),
    writeln(' 17) charizard ou blastoise'),
    writeln(' 18) comparacao entre alakazam e gengar'),
    writeln(' 19) habilidade static'),
    writeln(' 20) quais de elemento fogo'),
    writeln(' 21) quantas megas evoluções existem'),
    writeln(' 22) megas por geração'),
    writeln(' 23) pokemons por geração'),
    writeln(' 24) lendarios por geração'),
    writeln(' 25) pokemons do tipo fogo na geração 3'),
    writeln(' 26) megas do tipo dragão na geração 6'),
    writeln(' 27) lendarios do tipo psíquico').
