:- encoding(utf8).

% Auto-generated lexical expansion from items_catalog.pl
% Adds canonical item names and multiword competitive item phrases.
:- multifile item_intent_token/1.
:- multifile item_intent_phrase/1.

item_intent_token("ability_capsule").
item_intent_token("ability_patch").
item_intent_token("ability_shield").
item_intent_token("ability_urge").
item_intent_token("abomasite").
item_intent_token("abra_candy").
item_intent_token("absolite").
item_intent_token("absorb_bulb").
item_intent_token("academy_ball").
item_intent_token("academy_bottle").
item_intent_token("academy_cup").
item_intent_token("academy_tablecloth").
item_intent_token("acro_bike").
item_intent_token("adamant_crystal").
item_intent_token("adamant_mint").
item_intent_token("adamant_orb").
item_intent_token("adrenaline_orb").
item_intent_token("adventure_rules").
item_intent_token("aerodactyl_candy").
item_intent_token("aerodactylite").
item_intent_token("aggronite").
item_intent_token("aguav_berry").
item_intent_token("aipom_hair").
item_intent_token("air_balloon").
item_intent_token("air_mail").
item_intent_token("alakazite").
item_intent_token("alomomola_mucus").
item_intent_token("aloraichium_z_bag").
item_intent_token("aloraichium_z_held").
item_intent_token("altarianite").
item_intent_token("amaze_mulch").
item_intent_token("ampharosite").
item_intent_token("amulet_coin").
item_intent_token("antidote").
item_intent_token("apicot_berry").
item_intent_token("apple").
item_intent_token("applin_juice").
item_intent_token("apricorn_box").
item_intent_token("aqua_suit").
item_intent_token("armor_fossil").
item_intent_token("armor_pass").
item_intent_token("armorite_ore").
item_intent_token("arrokuda_scales").
item_intent_token("articuno_candy").
item_intent_token("aspear_berry").
item_intent_token("assault_vest").
item_intent_token("audinite").
item_intent_token("auroraticket").
item_intent_token("auspicious_armor").
item_intent_token("autograph").
item_intent_token("avocado").
item_intent_token("awakening").
item_intent_token("axew_scales").
item_intent_token("azure_flute").
item_intent_token("azurill_fur").
item_intent_token("babiri_berry").
item_intent_token("bachs_food_tin").
item_intent_token("bacon").
item_intent_token("bagon_scales").
item_intent_token("baguette").
item_intent_token("balm_mushroom").
item_intent_token("banana").
item_intent_token("band_autograph").
item_intent_token("banettite").
item_intent_token("barboach_slime").
item_intent_token("barred_cup").
item_intent_token("basculin_fang").
item_intent_token("basement_key").
item_intent_token("basement_key_goldenrod").
item_intent_token("basement_key_new_mauville").
item_intent_token("basil").
item_intent_token("battle_pocket").
item_intent_token("battle_tablecloth").
item_intent_token("beach_glass").
item_intent_token("bead_mail").
item_intent_token("beast_ball").
item_intent_token("beedrillite").
item_intent_token("bellsprout_candy").
item_intent_token("bellsprout_vine").
item_intent_token("belue_berry").
item_intent_token("bergmite_ice").
item_intent_token("berry_juice").
item_intent_token("berry_pots").
item_intent_token("berry_pouch").
item_intent_token("berry_sweet").
item_intent_token("bicycle").
item_intent_token("big_bamboo_shoot").
item_intent_token("big_malasada").
item_intent_token("big_mushroom").
item_intent_token("big_nugget").
item_intent_token("big_pearl").
item_intent_token("big_root").
item_intent_token("bike_green").
item_intent_token("bike_voucher").
item_intent_token("bike_yellow").
item_intent_token("binding_band").
item_intent_token("bitter_herba_mystica").
item_intent_token("black_apricorn").
item_intent_token("black_augurite").
item_intent_token("black_belt").
item_intent_token("black_flute").
item_intent_token("black_glasses").
item_intent_token("black_mane_hair").
item_intent_token("black_sludge").
item_intent_token("blank_plate").
item_intent_token("blastoisinite").
item_intent_token("blazikenite").
item_intent_token("bloom_mail").
item_intent_token("blue_apricorn").
item_intent_token("blue_bottle").
item_intent_token("blue_card").
item_intent_token("blue_cup").
item_intent_token("blue_dish").
item_intent_token("blue_flag_pick").
item_intent_token("blue_flute").
item_intent_token("blue_orb").
item_intent_token("blue_petal").
item_intent_token("blue_poke_ball_pick").
item_intent_token("blue_scarf").
item_intent_token("blue_shard").
item_intent_token("blue_sky_flower_pick").
item_intent_token("blue_tablecloth").
item_intent_token("bluk_berry").
item_intent_token("blunder_policy").
item_intent_token("bobs_food_tin").
item_intent_token("boiled_egg").
item_intent_token("bold_mint").
item_intent_token("bombirdier_feather").
item_intent_token("bonsly_tears").
item_intent_token("boost_mulch").
item_intent_token("booster_energy").
item_intent_token("bottle_cap").
item_intent_token("bounsweet_sweat").
item_intent_token("bramblin_twig").
item_intent_token("brave_mint").
item_intent_token("bread").
item_intent_token("brick_mail").
item_intent_token("bridge_mail_d").
item_intent_token("bridge_mail_m").
item_intent_token("bridge_mail_s").
item_intent_token("bridge_mail_t").
item_intent_token("bridge_mail_v").
item_intent_token("bright_powder").
item_intent_token("brittle_bones").
item_intent_token("bronze_bottle").
item_intent_token("bronze_cup").
item_intent_token("bronzor_fragment").
item_intent_token("bruxish_tooth").
item_intent_token("bubble_mail").
item_intent_token("bug_gem").
item_intent_token("bug_memory").
item_intent_token("bug_tera_shard").
item_intent_token("buginium_z_bag").
item_intent_token("buginium_z_held").
item_intent_token("buizel_fur").
item_intent_token("bulbasaur_candy").
item_intent_token("burn_drive").
item_intent_token("burn_heal").
item_intent_token("butter").
item_intent_token("bw_grass_tablecloth").
item_intent_token("cacnea_needle").
item_intent_token("calcium").
item_intent_token("calm_mint").
item_intent_token("cameruptite").
item_intent_token("camping_gear").
item_intent_token("candy_jar").
item_intent_token("capsakid_seed").
item_intent_token("carbink_jewel").
item_intent_token("carbos").
item_intent_token("card_key").
item_intent_token("card_key_letsgo").
item_intent_token("careful_mint").
item_intent_token("carrot_seeds").
item_intent_token("casteliacone").
item_intent_token("catching_charm").
item_intent_token("catching_pocket").
item_intent_token("caterpie_candy").
item_intent_token("cell_battery").
item_intent_token("cetoddle_grease").
item_intent_token("chalky_stone").
item_intent_token("chansey_candy").
item_intent_token("charcadet_soot").
item_intent_token("charcoal").
item_intent_token("charizardite_x").
item_intent_token("charizardite_y").
item_intent_token("charmander_candy").
item_intent_token("charti_berry").
item_intent_token("cheese").
item_intent_token("cheri_berry").
item_intent_token("cherish_ball").
item_intent_token("cherry_tomatoes").
item_intent_token("chesto_berry").
item_intent_token("chewtle_claw").
item_intent_token("chilan_berry").
item_intent_token("chili_sauce").
item_intent_token("chill_drive").
item_intent_token("chingling_fragment").
item_intent_token("chipped_pot").
item_intent_token("choice_band").
item_intent_token("choice_scarf").
item_intent_token("choice_specs").
item_intent_token("chople_berry").
item_intent_token("chorizo").
item_intent_token("clauncher_claw").
item_intent_token("claw_fossil").
item_intent_token("cleanse_tag").
item_intent_token("clear_amulet").
item_intent_token("clear_bell").
item_intent_token("clefairy_candy").
item_intent_token("cleffa_fur").
item_intent_token("clever_mochi").
item_intent_token("clever_wing").
item_intent_token("clothing_trunk").
item_intent_token("clover_sweet").
item_intent_token("coba_berry").
item_intent_token("coconut_milk").
item_intent_token("coin_case").
item_intent_token("colbur_berry").
item_intent_token("colress_machine").
item_intent_token("combee_honey").
item_intent_token("comet_shard").
item_intent_token("common_stone").
item_intent_token("contest_costume_dress").
item_intent_token("contest_costume_jacket").
item_intent_token("contest_pass").
item_intent_token("cornerstone_mask").
item_intent_token("cornn_berry").
item_intent_token("corphish_shell").
item_intent_token("coupon_1").
item_intent_token("coupon_2").
item_intent_token("coupon_3").
item_intent_token("courage_candy").
item_intent_token("courage_candy_l").
item_intent_token("courage_candy_xl").
item_intent_token("cover_fossil").
item_intent_token("covert_cloak").
item_intent_token("crabrawler_shell").
item_intent_token("cracked_pot").
item_intent_token("cramorant_down").
item_intent_token("cream_cheese").
item_intent_token("croagunk_poison").
item_intent_token("crown_pass").
item_intent_token("cryogonal_ice").
item_intent_token("crystal_cluster").
item_intent_token("cubchoo_fur").
item_intent_token("cubone_candy").
item_intent_token("cucumber").
item_intent_token("cufant_tarnish").
item_intent_token("curry_powder").
item_intent_token("custap_berry").
item_intent_token("cutiefly_powder").
item_intent_token("cyber_ball").
item_intent_token("cyclizar_scales").
item_intent_token("damp_mulch").
item_intent_token("damp_rock").
item_intent_token("dark_gem").
item_intent_token("dark_memory").
item_intent_token("dark_stone").
item_intent_token("dark_tera_shard").
item_intent_token("darkinium_z_bag").
item_intent_token("darkinium_z_held").
item_intent_token("data_card_01").
item_intent_token("data_card_02").
item_intent_token("data_card_03").
item_intent_token("data_card_04").
item_intent_token("data_card_05").
item_intent_token("data_card_06").
item_intent_token("data_card_07").
item_intent_token("data_card_08").
item_intent_token("data_card_09").
item_intent_token("data_card_10").
item_intent_token("data_card_11").
item_intent_token("data_card_12").
item_intent_token("data_card_13").
item_intent_token("data_card_14").
item_intent_token("data_card_15").
item_intent_token("data_card_16").
item_intent_token("data_card_17").
item_intent_token("data_card_18").
item_intent_token("data_card_19").
item_intent_token("data_card_20").
item_intent_token("data_card_21").
item_intent_token("data_card_22").
item_intent_token("data_card_23").
item_intent_token("data_card_24").
item_intent_token("data_card_25").
item_intent_token("data_card_26").
item_intent_token("data_card_27").
item_intent_token("dawn_stone").
item_intent_token("decidium_z_bag").
item_intent_token("decidium_z_held").
item_intent_token("dedenne_fur").
item_intent_token("deep_sea_scale").
item_intent_token("deep_sea_tooth").
item_intent_token("deerling_hair").
item_intent_token("deino_scales").
item_intent_token("delibird_parcel").
item_intent_token("destiny_knot").
item_intent_token("devon_goods").
item_intent_token("devon_parts").
item_intent_token("devon_scope").
item_intent_token("devon_scuba_gear").
item_intent_token("diamond_bottle").
item_intent_token("diamond_pattern_cup").
item_intent_token("diamond_tablecloth").
item_intent_token("diancite").
item_intent_token("diglett_candy").
item_intent_token("diglett_dirt").
item_intent_token("dire_hit").
item_intent_token("dire_hit_2").
item_intent_token("dire_hit_3").
item_intent_token("discount_coupon").
item_intent_token("ditto_candy").
item_intent_token("ditto_goo").
item_intent_token("dive_ball").
item_intent_token("dna_splicers").
item_intent_token("dna_splicers_merge").
item_intent_token("dna_splicers_split").
item_intent_token("doduo_candy").
item_intent_token("dome_fossil").
item_intent_token("dondozo_whisker").
item_intent_token("douse_drive").
item_intent_token("dowsing_machine").
item_intent_token("draco_plate").
item_intent_token("dragon_fang").
item_intent_token("dragon_gem").
item_intent_token("dragon_memory").
item_intent_token("dragon_scale").
item_intent_token("dragon_skull").
item_intent_token("dragon_tera_shard").
item_intent_token("dragonium_z_bag").
item_intent_token("dragonium_z_held").
item_intent_token("dratini_candy").
item_intent_token("dratini_scales").
item_intent_token("dread_plate").
item_intent_token("dream_ball").
item_intent_token("dream_mail").
item_intent_token("dreepy_powder").
item_intent_token("drifloon_gas").
item_intent_token("dropped_item").
item_intent_token("dropped_item_red").
item_intent_token("dropped_item_yellow").
item_intent_token("drowzee_candy").
item_intent_token("drowzee_fur").
item_intent_token("dubious_disc").
item_intent_token("ducklett_feather").
item_intent_token("dunsparce_scales").
item_intent_token("durin_berry").
item_intent_token("dusk_ball").
item_intent_token("dusk_stone").
item_intent_token("duskull_fragment").
item_intent_token("dynamax_band").
item_intent_token("dynamax_candy").
item_intent_token("dynamax_crystal_and15").
item_intent_token("dynamax_crystal_and337").
item_intent_token("dynamax_crystal_and390").
item_intent_token("dynamax_crystal_and458").
item_intent_token("dynamax_crystal_and603").
item_intent_token("dynamax_crystal_aql7235").
item_intent_token("dynamax_crystal_aql7525").
item_intent_token("dynamax_crystal_aql7557").
item_intent_token("dynamax_crystal_aql7595").
item_intent_token("dynamax_crystal_aql7602").
item_intent_token("dynamax_crystal_aqr7950").
item_intent_token("dynamax_crystal_aqr8232").
item_intent_token("dynamax_crystal_aqr8264").
item_intent_token("dynamax_crystal_aqr8414").
item_intent_token("dynamax_crystal_aqr8499").
item_intent_token("dynamax_crystal_aqr8518").
item_intent_token("dynamax_crystal_aqr8610").
item_intent_token("dynamax_crystal_aqr8709").
item_intent_token("dynamax_crystal_ara6585").
item_intent_token("dynamax_crystal_ari546").
item_intent_token("dynamax_crystal_ari553").
item_intent_token("dynamax_crystal_ari617").
item_intent_token("dynamax_crystal_ari951").
item_intent_token("dynamax_crystal_aur1577").
item_intent_token("dynamax_crystal_aur1605").
item_intent_token("dynamax_crystal_aur1612").
item_intent_token("dynamax_crystal_aur1641").
item_intent_token("dynamax_crystal_aur1708").
item_intent_token("dynamax_crystal_aur2088").
item_intent_token("dynamax_crystal_aur2095").
item_intent_token("dynamax_crystal_boo5235").
item_intent_token("dynamax_crystal_boo5340").
item_intent_token("dynamax_crystal_boo5351").
item_intent_token("dynamax_crystal_boo5435").
item_intent_token("dynamax_crystal_boo5506").
item_intent_token("dynamax_crystal_boo5602").
item_intent_token("dynamax_crystal_boo5733").
item_intent_token("dynamax_crystal_cap7754").
item_intent_token("dynamax_crystal_cap7773").
item_intent_token("dynamax_crystal_cap7776").
item_intent_token("dynamax_crystal_cap8278").
item_intent_token("dynamax_crystal_cap8322").
item_intent_token("dynamax_crystal_car2326").
item_intent_token("dynamax_crystal_car3307").
item_intent_token("dynamax_crystal_car3685").
item_intent_token("dynamax_crystal_car3699").
item_intent_token("dynamax_crystal_cas153").
item_intent_token("dynamax_crystal_cas168").
item_intent_token("dynamax_crystal_cas21").
item_intent_token("dynamax_crystal_cas219").
item_intent_token("dynamax_crystal_cas265").
item_intent_token("dynamax_crystal_cas403").
item_intent_token("dynamax_crystal_cas542").
item_intent_token("dynamax_crystal_cen5267").
item_intent_token("dynamax_crystal_cen5288").
item_intent_token("dynamax_crystal_cen5459").
item_intent_token("dynamax_crystal_cen5460").
item_intent_token("dynamax_crystal_cen551").
item_intent_token("dynamax_crystal_cep8162").
item_intent_token("dynamax_crystal_cep8238").
item_intent_token("dynamax_crystal_cep8417").
item_intent_token("dynamax_crystal_cep8974").
item_intent_token("dynamax_crystal_cet188").
item_intent_token("dynamax_crystal_cet539").
item_intent_token("dynamax_crystal_cet681").
item_intent_token("dynamax_crystal_cet804").
item_intent_token("dynamax_crystal_cet911").
item_intent_token("dynamax_crystal_cma2282").
item_intent_token("dynamax_crystal_cma2294").
item_intent_token("dynamax_crystal_cma2491").
item_intent_token("dynamax_crystal_cma2618").
item_intent_token("dynamax_crystal_cma2646").
item_intent_token("dynamax_crystal_cma2657").
item_intent_token("dynamax_crystal_cma2693").
item_intent_token("dynamax_crystal_cma2827").
item_intent_token("dynamax_crystal_cmi2845").
item_intent_token("dynamax_crystal_cmi2943").
item_intent_token("dynamax_crystal_cnc3208").
item_intent_token("dynamax_crystal_cnc3249").
item_intent_token("dynamax_crystal_cnc3268").
item_intent_token("dynamax_crystal_cnc3429").
item_intent_token("dynamax_crystal_cnc3449").
item_intent_token("dynamax_crystal_cnc3461").
item_intent_token("dynamax_crystal_cnc3572").
item_intent_token("dynamax_crystal_cnc3627").
item_intent_token("dynamax_crystal_col1956").
item_intent_token("dynamax_crystal_col2040").
item_intent_token("dynamax_crystal_col2177").
item_intent_token("dynamax_crystal_com4968").
item_intent_token("dynamax_crystal_crt4287").
item_intent_token("dynamax_crystal_cru4656").
item_intent_token("dynamax_crystal_cru4700").
item_intent_token("dynamax_crystal_cru4730").
item_intent_token("dynamax_crystal_cru4763").
item_intent_token("dynamax_crystal_cru4853").
item_intent_token("dynamax_crystal_crv4623").
item_intent_token("dynamax_crystal_crv4662").
item_intent_token("dynamax_crystal_crv4757").
item_intent_token("dynamax_crystal_crv4786").
item_intent_token("dynamax_crystal_cvn4785").
item_intent_token("dynamax_crystal_cvn4846").
item_intent_token("dynamax_crystal_cvn4915").
item_intent_token("dynamax_crystal_cyg7417").
item_intent_token("dynamax_crystal_cyg7528").
item_intent_token("dynamax_crystal_cyg7796").
item_intent_token("dynamax_crystal_cyg7924").
item_intent_token("dynamax_crystal_cyg7949").
item_intent_token("dynamax_crystal_cyg8301").
item_intent_token("dynamax_crystal_del7852").
item_intent_token("dynamax_crystal_del7882").
item_intent_token("dynamax_crystal_del7906").
item_intent_token("dynamax_crystal_dra4434").
item_intent_token("dynamax_crystal_dra5291").
item_intent_token("dynamax_crystal_dra5744").
item_intent_token("dynamax_crystal_dra6132").
item_intent_token("dynamax_crystal_dra6370").
item_intent_token("dynamax_crystal_dra6396").
item_intent_token("dynamax_crystal_dra6536").
item_intent_token("dynamax_crystal_dra6636").
item_intent_token("dynamax_crystal_dra6688").
item_intent_token("dynamax_crystal_dra6705").
item_intent_token("dynamax_crystal_dra7310").
item_intent_token("dynamax_crystal_dra7462").
item_intent_token("dynamax_crystal_equ8131").
item_intent_token("dynamax_crystal_eri1084").
item_intent_token("dynamax_crystal_eri1231").
item_intent_token("dynamax_crystal_eri1298").
item_intent_token("dynamax_crystal_eri1325").
item_intent_token("dynamax_crystal_eri1393").
item_intent_token("dynamax_crystal_eri1464").
item_intent_token("dynamax_crystal_eri1666").
item_intent_token("dynamax_crystal_eri472").
item_intent_token("dynamax_crystal_eri850").
item_intent_token("dynamax_crystal_eri874").
item_intent_token("dynamax_crystal_eri897").
item_intent_token("dynamax_crystal_eri984").
item_intent_token("dynamax_crystal_gem2216").
item_intent_token("dynamax_crystal_gem2286").
item_intent_token("dynamax_crystal_gem2421").
item_intent_token("dynamax_crystal_gem2473").
item_intent_token("dynamax_crystal_gem2484").
item_intent_token("dynamax_crystal_gem2650").
item_intent_token("dynamax_crystal_gem2777").
item_intent_token("dynamax_crystal_gem2891").
item_intent_token("dynamax_crystal_gem2930").
item_intent_token("dynamax_crystal_gem2990").
item_intent_token("dynamax_crystal_gru8353").
item_intent_token("dynamax_crystal_gru8425").
item_intent_token("dynamax_crystal_gru8636").
item_intent_token("dynamax_crystal_her6008").
item_intent_token("dynamax_crystal_her6117").
item_intent_token("dynamax_crystal_her6148").
item_intent_token("dynamax_crystal_her6406").
item_intent_token("dynamax_crystal_her6410").
item_intent_token("dynamax_crystal_her6526").
item_intent_token("dynamax_crystal_hya3418").
item_intent_token("dynamax_crystal_hya3482").
item_intent_token("dynamax_crystal_hya3748").
item_intent_token("dynamax_crystal_hya3845").
item_intent_token("dynamax_crystal_hya3903").
item_intent_token("dynamax_crystal_leo3773").
item_intent_token("dynamax_crystal_leo3852").
item_intent_token("dynamax_crystal_leo3905").
item_intent_token("dynamax_crystal_leo3982").
item_intent_token("dynamax_crystal_leo4031").
item_intent_token("dynamax_crystal_leo4057").
item_intent_token("dynamax_crystal_leo4357").
item_intent_token("dynamax_crystal_leo4359").
item_intent_token("dynamax_crystal_leo4534").
item_intent_token("dynamax_crystal_lep1829").
item_intent_token("dynamax_crystal_lep1865").
item_intent_token("dynamax_crystal_lib5531").
item_intent_token("dynamax_crystal_lib5603").
item_intent_token("dynamax_crystal_lib5685").
item_intent_token("dynamax_crystal_lib5787").
item_intent_token("dynamax_crystal_lyr7001").
item_intent_token("dynamax_crystal_lyr7106").
item_intent_token("dynamax_crystal_lyr7178").
item_intent_token("dynamax_crystal_lyr7298").
item_intent_token("dynamax_crystal_oct7228").
item_intent_token("dynamax_crystal_oph6056").
item_intent_token("dynamax_crystal_oph6075").
item_intent_token("dynamax_crystal_oph6149").
item_intent_token("dynamax_crystal_oph6378").
item_intent_token("dynamax_crystal_oph6556").
item_intent_token("dynamax_crystal_oph6603").
item_intent_token("dynamax_crystal_ori1543").
item_intent_token("dynamax_crystal_ori1713").
item_intent_token("dynamax_crystal_ori1790").
item_intent_token("dynamax_crystal_ori1852").
item_intent_token("dynamax_crystal_ori1879").
item_intent_token("dynamax_crystal_ori1899").
item_intent_token("dynamax_crystal_ori1903").
item_intent_token("dynamax_crystal_ori1948").
item_intent_token("dynamax_crystal_ori2004").
item_intent_token("dynamax_crystal_ori2061").
item_intent_token("dynamax_crystal_pav7790").
item_intent_token("dynamax_crystal_peg39").
item_intent_token("dynamax_crystal_peg8308").
item_intent_token("dynamax_crystal_peg8450").
item_intent_token("dynamax_crystal_peg8634").
item_intent_token("dynamax_crystal_peg8650").
item_intent_token("dynamax_crystal_peg8684").
item_intent_token("dynamax_crystal_peg8775").
item_intent_token("dynamax_crystal_peg8781").
item_intent_token("dynamax_crystal_peg8880").
item_intent_token("dynamax_crystal_peg8905").
item_intent_token("dynamax_crystal_per1017").
item_intent_token("dynamax_crystal_per1131").
item_intent_token("dynamax_crystal_per1228").
item_intent_token("dynamax_crystal_per834").
item_intent_token("dynamax_crystal_per936").
item_intent_token("dynamax_crystal_per941").
item_intent_token("dynamax_crystal_phe338").
item_intent_token("dynamax_crystal_phe99").
item_intent_token("dynamax_crystal_psa8728").
item_intent_token("dynamax_crystal_psc361").
item_intent_token("dynamax_crystal_psc437").
item_intent_token("dynamax_crystal_psc510").
item_intent_token("dynamax_crystal_psc596").
item_intent_token("dynamax_crystal_psc8773").
item_intent_token("dynamax_crystal_pup3045").
item_intent_token("dynamax_crystal_pup3165").
item_intent_token("dynamax_crystal_pup3185").
item_intent_token("dynamax_crystal_sco5928").
item_intent_token("dynamax_crystal_sco5944").
item_intent_token("dynamax_crystal_sco5953").
item_intent_token("dynamax_crystal_sco5984").
item_intent_token("dynamax_crystal_sco6027").
item_intent_token("dynamax_crystal_sco6084").
item_intent_token("dynamax_crystal_sco6134").
item_intent_token("dynamax_crystal_sco6165").
item_intent_token("dynamax_crystal_sco6241").
item_intent_token("dynamax_crystal_sco6247").
item_intent_token("dynamax_crystal_sco6252").
item_intent_token("dynamax_crystal_sco6508").
item_intent_token("dynamax_crystal_sco6527").
item_intent_token("dynamax_crystal_sco6553").
item_intent_token("dynamax_crystal_sco6630").
item_intent_token("dynamax_crystal_ser5854").
item_intent_token("dynamax_crystal_ser5879").
item_intent_token("dynamax_crystal_ser7141").
item_intent_token("dynamax_crystal_sge7479").
item_intent_token("dynamax_crystal_sgr6746").
item_intent_token("dynamax_crystal_sgr6812").
item_intent_token("dynamax_crystal_sgr6859").
item_intent_token("dynamax_crystal_sgr6879").
item_intent_token("dynamax_crystal_sgr6913").
item_intent_token("dynamax_crystal_sgr7116").
item_intent_token("dynamax_crystal_sgr7121").
item_intent_token("dynamax_crystal_sgr7194").
item_intent_token("dynamax_crystal_sgr7264").
item_intent_token("dynamax_crystal_sgr7337").
item_intent_token("dynamax_crystal_sgr7343").
item_intent_token("dynamax_crystal_sgr7348").
item_intent_token("dynamax_crystal_sgr7597").
item_intent_token("dynamax_crystal_tau1165").
item_intent_token("dynamax_crystal_tau1346").
item_intent_token("dynamax_crystal_tau1373").
item_intent_token("dynamax_crystal_tau1409").
item_intent_token("dynamax_crystal_tau1412").
item_intent_token("dynamax_crystal_tau1457").
item_intent_token("dynamax_crystal_tau1791").
item_intent_token("dynamax_crystal_tau1910").
item_intent_token("dynamax_crystal_tra6217").
item_intent_token("dynamax_crystal_tri544").
item_intent_token("dynamax_crystal_uma3323").
item_intent_token("dynamax_crystal_uma3569").
item_intent_token("dynamax_crystal_uma3594").
item_intent_token("dynamax_crystal_uma4033").
item_intent_token("dynamax_crystal_uma4069").
item_intent_token("dynamax_crystal_uma4295").
item_intent_token("dynamax_crystal_uma4301").
item_intent_token("dynamax_crystal_uma4375").
item_intent_token("dynamax_crystal_uma4377").
item_intent_token("dynamax_crystal_uma4518").
item_intent_token("dynamax_crystal_uma4554").
item_intent_token("dynamax_crystal_uma4660").
item_intent_token("dynamax_crystal_uma4905").
item_intent_token("dynamax_crystal_uma5054").
item_intent_token("dynamax_crystal_uma5191").
item_intent_token("dynamax_crystal_umi424").
item_intent_token("dynamax_crystal_umi5563").
item_intent_token("dynamax_crystal_umi5735").
item_intent_token("dynamax_crystal_umi6789").
item_intent_token("dynamax_crystal_vel3485").
item_intent_token("dynamax_crystal_vel3634").
item_intent_token("dynamax_crystal_vel3734").
item_intent_token("dynamax_crystal_vir4540").
item_intent_token("dynamax_crystal_vir4689").
item_intent_token("dynamax_crystal_vir4825").
item_intent_token("dynamax_crystal_vir4910").
item_intent_token("dynamax_crystal_vir4932").
item_intent_token("dynamax_crystal_vir5056").
item_intent_token("dynamax_crystal_vir5107").
item_intent_token("dynamax_crystal_vir5315").
item_intent_token("dynamax_crystal_vir5338").
item_intent_token("dynamax_crystal_vir5359").
item_intent_token("dynamax_crystal_vir5409").
item_intent_token("dynamax_crystal_vul7405").
item_intent_token("dynite_ore").
item_intent_token("earth_plate").
item_intent_token("eevee_candy").
item_intent_token("eevee_cup").
item_intent_token("eevee_fur").
item_intent_token("eevium_z_bag").
item_intent_token("eevium_z_held").
item_intent_token("egg").
item_intent_token("eiscue_down").
item_intent_token("eject_button").
item_intent_token("eject_pack").
item_intent_token("ekans_candy").
item_intent_token("ekans_fang").
item_intent_token("electabuzz_candy").
item_intent_token("electirizer").
item_intent_token("electric_gem").
item_intent_token("electric_memory").
item_intent_token("electric_seed").
item_intent_token("electric_tera_shard").
item_intent_token("electrium_z_bag").
item_intent_token("electrium_z_held").
item_intent_token("elevator_key").
item_intent_token("elixir").
item_intent_token("endorsement").
item_intent_token("energy_powder").
item_intent_token("energy_root").
item_intent_token("enigma_berry").
item_intent_token("enigma_stone").
item_intent_token("enigmatic_card").
item_intent_token("eon_flute").
item_intent_token("eon_ticket").
item_intent_token("escape_rope").
item_intent_token("ether").
item_intent_token("everstone").
item_intent_token("eviolite").
item_intent_token("exeggcute_candy").
item_intent_token("exercise_ball").
item_intent_token("exp_candy_l").
item_intent_token("exp_candy_m").
item_intent_token("exp_candy_s").
item_intent_token("exp_candy_xl").
item_intent_token("exp_candy_xs").
item_intent_token("exp_charm").
item_intent_token("exp_share").
item_intent_token("expert_belt").
item_intent_token("explorer_kit").
item_intent_token("fab_mail").
item_intent_token("fairium_z_bag").
item_intent_token("fairium_z_held").
item_intent_token("fairy_feather").
item_intent_token("fairy_gem").
item_intent_token("fairy_memory").
item_intent_token("fairy_tera_shard").
item_intent_token("falinks_sweat").
item_intent_token("fame_checker").
item_intent_token("fancy_apple").
item_intent_token("farfetchd_candy").
item_intent_token("fashion_case").
item_intent_token("fast_ball").
item_intent_token("favored_mail").
item_intent_token("feebas_scales").
item_intent_token("festival_ticket").
item_intent_token("fidough_fur").
item_intent_token("fighting_gem").
item_intent_token("fighting_memory").
item_intent_token("fighting_tera_shard").
item_intent_token("fightinium_z_bag").
item_intent_token("fightinium_z_held").
item_intent_token("figy_berry").
item_intent_token("finizen_mucus").
item_intent_token("finneon_scales").
item_intent_token("fire_gem").
item_intent_token("fire_memory").
item_intent_token("fire_pattern_cup").
item_intent_token("fire_stone").
item_intent_token("fire_tera_shard").
item_intent_token("firium_z_bag").
item_intent_token("firium_z_held").
item_intent_token("fishing_rod").
item_intent_token("fishing_rod_galar").
item_intent_token("fist_plate").
item_intent_token("flabebe_pollen").
item_intent_token("flame_mail").
item_intent_token("flame_orb").
item_intent_token("flame_plate").
item_intent_token("flamigo_down").
item_intent_token("fletchling_feather").
item_intent_token("flittle_down").
item_intent_token("float_stone").
item_intent_token("flower_pattern_cup").
item_intent_token("flower_sweet").
item_intent_token("fluffy_tail").
item_intent_token("flying_gem").
item_intent_token("flying_memory").
item_intent_token("flying_tera_shard").
item_intent_token("flyinium_z_bag").
item_intent_token("flyinium_z_held").
item_intent_token("focus_band").
item_intent_token("focus_sash").
item_intent_token("fomantis_leaf").
item_intent_token("foongus_spores").
item_intent_token("forage_bag").
item_intent_token("fossilized_bird").
item_intent_token("fossilized_dino").
item_intent_token("fossilized_drake").
item_intent_token("fossilized_fish").
item_intent_token("fresh_cream").
item_intent_token("fresh_start_mochi").
item_intent_token("fresh_water").
item_intent_token("fried_fillet").
item_intent_token("fried_food").
item_intent_token("friend_ball").
item_intent_token("frigibax_scales").
item_intent_token("fruit_bunch").
item_intent_token("full_heal").
item_intent_token("full_incense").
item_intent_token("full_restore").
item_intent_token("galactic_key").
item_intent_token("galarica_cuff").
item_intent_token("galarica_twig").
item_intent_token("galarica_wreath").
item_intent_token("galladite").
item_intent_token("ganlon_berry").
item_intent_token("garchompite").
item_intent_token("gardevoirite").
item_intent_token("gastly_candy").
item_intent_token("gastly_gas").
item_intent_token("gb_sounds").
item_intent_token("gengarite").
item_intent_token("genius_mochi").
item_intent_token("genius_wing").
item_intent_token("gentle_mint").
item_intent_token("geodude_candy").
item_intent_token("geodude_fragment").
item_intent_token("ghost_gem").
item_intent_token("ghost_memory").
item_intent_token("ghost_tera_shard").
item_intent_token("ghostium_z_bag").
item_intent_token("ghostium_z_held").
item_intent_token("gible_scales").
item_intent_token("gigantamix").
item_intent_token("gimmighoul_coin").
item_intent_token("girafarig_fur").
item_intent_token("glalitite").
item_intent_token("gligar_fang").
item_intent_token("glimmering_charm").
item_intent_token("glimmet_crystal").
item_intent_token("glitter_mail").
item_intent_token("go_goggles").
item_intent_token("god_stone").
item_intent_token("gold_bottle").
item_intent_token("gold_bottle_cap").
item_intent_token("gold_cup").
item_intent_token("gold_leaf").
item_intent_token("gold_pick").
item_intent_token("gold_teeth").
item_intent_token("goldeen_candy").
item_intent_token("golden_nanab_berry").
item_intent_token("golden_pinap_berry").
item_intent_token("golden_razz_berry").
item_intent_token("good_rod").
item_intent_token("gooey_mulch").
item_intent_token("goomy_goo").
item_intent_token("gothita_eyelash").
item_intent_token("gracidea").
item_intent_token("gram_1").
item_intent_token("gram_2").
item_intent_token("gram_3").
item_intent_token("grass_gem").
item_intent_token("grass_mail").
item_intent_token("grass_memory").
item_intent_token("grass_tera_shard").
item_intent_token("grassium_z_bag").
item_intent_token("grassium_z_held").
item_intent_token("grassy_seed").
item_intent_token("great_ball").
item_intent_token("greavard_wax").
item_intent_token("green_apricorn").
item_intent_token("green_bell_pepper").
item_intent_token("green_dish").
item_intent_token("green_petal").
item_intent_token("green_poke_ball_pick").
item_intent_token("green_scarf").
item_intent_token("green_shard").
item_intent_token("greet_mail").
item_intent_token("grepa_berry").
item_intent_token("grimer_candy").
item_intent_token("grimer_toxin").
item_intent_token("grip_claw").
item_intent_token("griseous_core").
item_intent_token("griseous_orb").
item_intent_token("ground_gem").
item_intent_token("ground_memory").
item_intent_token("ground_tera_shard").
item_intent_token("groundium_z_bag").
item_intent_token("groundium_z_held").
item_intent_token("growlithe_candy").
item_intent_token("growlithe_fur").
item_intent_token("growth_mulch").
item_intent_token("grubbin_thread").
item_intent_token("grubby_hanky").
item_intent_token("guard_spec").
item_intent_token("gulpin_mucus").
item_intent_token("gyaradosite").
item_intent_token("haban_berry").
item_intent_token("ham").
item_intent_token("hamburger").
item_intent_token("happiny_dust").
item_intent_token("harbor_mail").
item_intent_token("hard_stone").
item_intent_token("hasty_mint").
item_intent_token("hatenna_dust").
item_intent_token("hawlucha_down").
item_intent_token("heal_ball").
item_intent_token("heal_powder").
item_intent_token("health_candy").
item_intent_token("health_candy_l").
item_intent_token("health_candy_xl").
item_intent_token("health_mochi").
item_intent_token("health_wing").
item_intent_token("heart_mail").
item_intent_token("heart_scale").
item_intent_token("hearthflame_mask").
item_intent_token("heat_rock").
item_intent_token("heavy_ball").
item_intent_token("heavy_duty_boots").
item_intent_token("helix_fossil").
item_intent_token("heracronite").
item_intent_token("heracross_claw").
item_intent_token("herbed_sausage").
item_intent_token("heroic_sword_pick").
item_intent_token("hi_tech_earbuds").
item_intent_token("hippopotas_sand").
item_intent_token("hitmonchan_candy").
item_intent_token("hitmonlee_candy").
item_intent_token("hm01").
item_intent_token("hm02").
item_intent_token("hm03").
item_intent_token("hm04").
item_intent_token("hm05").
item_intent_token("hm06").
item_intent_token("hm07").
item_intent_token("hm08").
item_intent_token("holo_caster").
item_intent_token("holo_caster_green").
item_intent_token("holo_caster_red").
item_intent_token("hondew_berry").
item_intent_token("honey").
item_intent_token("honor_of_kalos").
item_intent_token("hoothoot_feather").
item_intent_token("hoppip_leaf").
item_intent_token("horsea_candy").
item_intent_token("horseradish").
item_intent_token("houndoominite").
item_intent_token("houndour_fang").
item_intent_token("hp_up").
item_intent_token("hyper_potion").
item_intent_token("iapapa_berry").
item_intent_token("ice_gem").
item_intent_token("ice_heal").
item_intent_token("ice_memory").
item_intent_token("ice_stone").
item_intent_token("ice_tera_shard").
item_intent_token("iceroot_carrot").
item_intent_token("icicle_plate").
item_intent_token("icium_z_bag").
item_intent_token("icium_z_held").
item_intent_token("icy_rock").
item_intent_token("igglybuff_fluff").
item_intent_token("ilimas_normalium_z").
item_intent_token("illumise_fluid").
item_intent_token("impidimp_hair").
item_intent_token("impish_mint").
item_intent_token("incinium_z_bag").
item_intent_token("incinium_z_held").
item_intent_token("indeedee_fur").
item_intent_token("inquiry_mail").
item_intent_token("insect_plate").
item_intent_token("instant_noodles").
item_intent_token("intriguing_stone").
item_intent_token("iron").
item_intent_token("iron_ball").
item_intent_token("iron_plate").
item_intent_token("item_drop").
item_intent_token("item_urge").
item_intent_token("jaboca_berry").
item_intent_token("jade_orb").
item_intent_token("jalapeno").
item_intent_token("jam").
item_intent_token("jangmo_o_scales").
item_intent_token("jaw_fossil").
item_intent_token("jigglypuff_candy").
item_intent_token("jolly_mint").
item_intent_token("journal").
item_intent_token("jynx_candy").
item_intent_token("kabuto_candy").
item_intent_token("kangaskhan_candy").
item_intent_token("kangaskhanite").
item_intent_token("kasib_berry").
item_intent_token("kebia_berry").
item_intent_token("kee_berry").
item_intent_token("kelpsy_berry").
item_intent_token("ketchup").
item_intent_token("key_stone").
item_intent_token("key_to_room_1").
item_intent_token("key_to_room_2").
item_intent_token("key_to_room_4").
item_intent_token("key_to_room_6").
item_intent_token("kings_rock").
item_intent_token("kiwi").
item_intent_token("klawf_claw").
item_intent_token("klawf_stick").
item_intent_token("klefki_key").
item_intent_token("koffing_candy").
item_intent_token("koffing_gas").
item_intent_token("kofus_wallet").
item_intent_token("komala_claw").
item_intent_token("kommonium_z_bag").
item_intent_token("kommonium_z_held").
item_intent_token("koraidons_poke_ball").
item_intent_token("krabby_candy").
item_intent_token("kricketot_shell").
item_intent_token("lafeather_ball").
item_intent_token("lagging_tail").
item_intent_token("lagigaton_ball").
item_intent_token("lagreat_ball").
item_intent_token("laheavy_ball").
item_intent_token("lajet_ball").
item_intent_token("laleaden_ball").
item_intent_token("lansat_berry").
item_intent_token("laorigin_ball").
item_intent_token("lapoke_ball").
item_intent_token("lapras_candy").
item_intent_token("large_leek").
item_intent_token("larvesta_fuzz").
item_intent_token("larvitar_claw").
item_intent_token("lastrange_ball").
item_intent_token("latiasite").
item_intent_token("latiosite").
item_intent_token("laultra_ball").
item_intent_token("lava_cookie").
item_intent_token("lawing_ball").
item_intent_token("lax_incense").
item_intent_token("lax_mint").
item_intent_token("leaders_crest").
item_intent_token("leaf_letter_eevee").
item_intent_token("leaf_letter_pikachu").
item_intent_token("leaf_stone").
item_intent_token("leafy_tablecloth").
item_intent_token("lechonk_hair").
item_intent_token("left_poke_ball").
item_intent_token("leftovers").
item_intent_token("legend_plate").
item_intent_token("legendary_clue_1").
item_intent_token("legendary_clue_2").
item_intent_token("legendary_clue_3").
item_intent_token("legendary_clue_question").
item_intent_token("lemonade").
item_intent_token("lens_case").
item_intent_token("leppa_berry").
item_intent_token("letter").
item_intent_token("lettuce").
item_intent_token("level_ball").
item_intent_token("liberty_pass").
item_intent_token("lickitung_candy").
item_intent_token("liechi_berry").
item_intent_token("life_orb").
item_intent_token("lift_key").
item_intent_token("light_ball").
item_intent_token("light_clay").
item_intent_token("light_stone").
item_intent_token("like_mail").
item_intent_token("lilac_tablecloth").
item_intent_token("linking_cord").
item_intent_token("litleo_tuft").
item_intent_token("litwick_soot").
item_intent_token("loaded_dice").
item_intent_token("lock_capsule").
item_intent_token("lone_earring").
item_intent_token("lonely_mint").
item_intent_token("looker_ticket").
item_intent_token("loot_sack").
item_intent_token("lopunnite").
item_intent_token("lost_item").
item_intent_token("lotad_leaf").
item_intent_token("love_ball").
item_intent_token("love_sweet").
item_intent_token("lucarionite").
item_intent_token("luck_incense").
item_intent_token("lucky_egg").
item_intent_token("lucky_punch").
item_intent_token("lum_berry").
item_intent_token("luminous_moss").
item_intent_token("lumiose_galette").
item_intent_token("lunalium_z_bag").
item_intent_token("lunalium_z_held").
item_intent_token("lunar_wing").
item_intent_token("lure").
item_intent_token("lure_ball").
item_intent_token("lustrous_globe").
item_intent_token("lustrous_orb").
item_intent_token("luvdisc_scales").
item_intent_token("luxury_ball").
item_intent_token("lycanium_z_bag").
item_intent_token("lycanium_z_held").
item_intent_token("mach_bike").
item_intent_token("machine_part").
item_intent_token("macho_brace").
item_intent_token("machop_candy").
item_intent_token("magical_heart_pick").
item_intent_token("magical_star_pick").
item_intent_token("magikarp_candy").
item_intent_token("magikarp_scales").
item_intent_token("magma_emblem").
item_intent_token("magma_stone").
item_intent_token("magma_suit").
item_intent_token("magmar_candy").
item_intent_token("magmarizer").
item_intent_token("magnemite_candy").
item_intent_token("magnemite_screw").
item_intent_token("magnet").
item_intent_token("mago_berry").
item_intent_token("magost_berry").
item_intent_token("makeup_bag").
item_intent_token("makuhita_sweat").
item_intent_token("malicious_armor").
item_intent_token("manectite").
item_intent_token("mankey_candy").
item_intent_token("mankey_fur").
item_intent_token("maranga_berry").
item_intent_token("marble").
item_intent_token("mareanie_spike").
item_intent_token("mareep_wool").
item_intent_token("marill_ball").
item_intent_token("mark_charm").
item_intent_token("marmalade").
item_intent_token("marshadium_z_bag").
item_intent_token("marshadium_z_held").
item_intent_token("maschiff_fang").
item_intent_token("master_ball").
item_intent_token("masterpiece_teacup").
item_intent_token("mawilite").
item_intent_token("max_elixir").
item_intent_token("max_ether").
item_intent_token("max_honey").
item_intent_token("max_lure").
item_intent_token("max_mushrooms").
item_intent_token("max_potion").
item_intent_token("max_repel").
item_intent_token("max_revive").
item_intent_token("mayonnaise").
item_intent_token("meadow_plate").
item_intent_token("mech_mail").
item_intent_token("medal_box").
item_intent_token("medichamite").
item_intent_token("medicine_pocket").
item_intent_token("meditite_sweat").
item_intent_token("mega_anchor").
item_intent_token("mega_anklet").
item_intent_token("mega_bracelet").
item_intent_token("mega_charm").
item_intent_token("mega_cuff").
item_intent_token("mega_glasses").
item_intent_token("mega_glove").
item_intent_token("mega_pendant").
item_intent_token("mega_ring").
item_intent_token("mega_stickpin").
item_intent_token("mega_tiara").
item_intent_token("meltan_candy").
item_intent_token("member_card").
item_intent_token("mental_herb").
item_intent_token("meowth_candy").
item_intent_token("meowth_fur").
item_intent_token("metagrossite").
item_intent_token("metal_coat").
item_intent_token("metal_powder").
item_intent_token("meteorite").
item_intent_token("meteorite_2").
item_intent_token("meteorite_3").
item_intent_token("meteorite_4").
item_intent_token("meteorite_shard").
item_intent_token("metronome").
item_intent_token("mew_candy").
item_intent_token("mewnium_z_bag").
item_intent_token("mewnium_z_held").
item_intent_token("mewtwo_candy").
item_intent_token("mewtwonite_x").
item_intent_token("mewtwonite_y").
item_intent_token("micle_berry").
item_intent_token("mienfoo_claw").
item_intent_token("mighty_candy").
item_intent_token("mighty_candy_l").
item_intent_token("mighty_candy_xl").
item_intent_token("mild_mint").
item_intent_token("mimikium_z_bag").
item_intent_token("mimikium_z_held").
item_intent_token("mimikyu_scrap").
item_intent_token("mind_plate").
item_intent_token("mint_tablecloth").
item_intent_token("miracle_seed").
item_intent_token("miraidons_poke_ball").
item_intent_token("mirror_herb").
item_intent_token("misdreavus_tears").
item_intent_token("misty_seed").
item_intent_token("mixed_mushrooms").
item_intent_token("modest_mint").
item_intent_token("moltres_candy").
item_intent_token("monstrous_tablecloth").
item_intent_token("moomoo_cheese").
item_intent_token("moomoo_milk").
item_intent_token("moon_ball").
item_intent_token("moon_flute").
item_intent_token("moon_stone").
item_intent_token("morpeko_snack").
item_intent_token("mosaic_mail").
item_intent_token("mr_mime_candy").
item_intent_token("mudbray_mud").
item_intent_token("munchlax_fang").
item_intent_token("murkrow_bauble").
item_intent_token("muscle_band").
item_intent_token("muscle_mochi").
item_intent_token("muscle_wing").
item_intent_token("mustard").
item_intent_token("mystery_egg").
item_intent_token("mystic_water").
item_intent_token("mysticticket").
item_intent_token("n_lunarizer_merge").
item_intent_token("n_lunarizer_split").
item_intent_token("n_solarizer_merge").
item_intent_token("n_solarizer_split").
item_intent_token("nacli_salt").
item_intent_token("naive_mint").
item_intent_token("nanab_berry").
item_intent_token("naughty_mint").
item_intent_token("nest_ball").
item_intent_token("net_ball").
item_intent_token("never_melt_ice").
item_intent_token("nidoran_f_candy").
item_intent_token("nidoran_m_candy").
item_intent_token("noibat_fur").
item_intent_token("nomel_berry").
item_intent_token("noodles").
item_intent_token("normal_gem").
item_intent_token("normal_tera_shard").
item_intent_token("normalium_z_bag").
item_intent_token("normalium_z_held").
item_intent_token("nosepass_fragment").
item_intent_token("nugget").
item_intent_token("numel_lava").
item_intent_token("nymble_claw").
item_intent_token("oaks_letter").
item_intent_token("oaks_parcel").
item_intent_token("occa_berry").
item_intent_token("odd_incense").
item_intent_token("odd_keystone").
item_intent_token("oddish_candy").
item_intent_token("old_amber").
item_intent_token("old_charm").
item_intent_token("old_gateau").
item_intent_token("old_letter").
item_intent_token("old_rod").
item_intent_token("old_sea_map").
item_intent_token("olive_oil").
item_intent_token("omanyte_candy").
item_intent_token("onion").
item_intent_token("onix_candy").
item_intent_token("oran_berry").
item_intent_token("orange_dish").
item_intent_token("orange_mail").
item_intent_token("orange_petal").
item_intent_token("oranguru_fur").
item_intent_token("oricorio_feather").
item_intent_token("orthworm_tarnish").
item_intent_token("oval_charm").
item_intent_token("oval_stone").
item_intent_token("pachirisu_fur").
item_intent_token("pack_of_potatoes").
item_intent_token("packaged_curry").
item_intent_token("pair_of_tickets").
item_intent_token("pal_pad").
item_intent_token("pamtre_berry").
item_intent_token("paralyze_heal").
item_intent_token("paras_candy").
item_intent_token("parasol_pick").
item_intent_token("parcel").
item_intent_token("parcel_letsgo").
item_intent_token("park_ball").
item_intent_token("party_sparkler_pick").
item_intent_token("pass").
item_intent_token("pass_orb").
item_intent_token("passho_berry").
item_intent_token("passimian_fur").
item_intent_token("pasta").
item_intent_token("pawmi_fur").
item_intent_token("pawniard_blade").
item_intent_token("payapa_berry").
item_intent_token("peach_tablecloth").
item_intent_token("peanut_butter").
item_intent_token("pearl").
item_intent_token("pearl_string").
item_intent_token("peat_block").
item_intent_token("pecha_berry").
item_intent_token("pepper").
item_intent_token("permit").
item_intent_token("persim_berry").
item_intent_token("petaya_berry").
item_intent_token("petilil_leaf").
item_intent_token("pewter_crunchies").
item_intent_token("phanpy_nail").
item_intent_token("phantump_twig").
item_intent_token("photo_album").
item_intent_token("pichu_fur").
item_intent_token("pickle").
item_intent_token("picnic_set").
item_intent_token("pidgeotite").
item_intent_token("pidgey_candy").
item_intent_token("pika_pika_pick").
item_intent_token("pikachu_candy").
item_intent_token("pikachu_cup").
item_intent_token("pikanium_z_bag").
item_intent_token("pikanium_z_held").
item_intent_token("pikashunium_z_bag").
item_intent_token("pikashunium_z_held").
item_intent_token("pinap_berry").
item_intent_token("pincurchin_spines").
item_intent_token("pineapple").
item_intent_token("pineco_husk").
item_intent_token("pink_apricorn").
item_intent_token("pink_bottle").
item_intent_token("pink_cup").
item_intent_token("pink_nectar").
item_intent_token("pink_petal").
item_intent_token("pink_scarf").
item_intent_token("pink_tablecloth").
item_intent_token("pinsir_candy").
item_intent_token("pinsirite").
item_intent_token("pixie_plate").
item_intent_token("plaid_tablecloth_b").
item_intent_token("plaid_tablecloth_r").
item_intent_token("plaid_tablecloth_y").
item_intent_token("plasma_card").
item_intent_token("plume_fossil").
item_intent_token("poffin_case").
item_intent_token("point_card").
item_intent_token("poison_barb").
item_intent_token("poison_gem").
item_intent_token("poison_memory").
item_intent_token("poison_tera_shard").
item_intent_token("poisonium_z_bag").
item_intent_token("poisonium_z_held").
item_intent_token("poke_ball").
item_intent_token("poke_doll").
item_intent_token("poke_flute").
item_intent_token("poke_radar").
item_intent_token("poke_toy").
item_intent_token("pokeblock_case").
item_intent_token("pokeblock_kit").
item_intent_token("pokemon_box").
item_intent_token("pokemon_box_link").
item_intent_token("polished_mud_ball").
item_intent_token("poliwag_candy").
item_intent_token("poliwag_slime").
item_intent_token("polka_dot_bottle").
item_intent_token("polka_dot_cup").
item_intent_token("polka_dot_tablecloth").
item_intent_token("poltchageist_powder").
item_intent_token("pomeg_berry").
item_intent_token("ponyta_candy").
item_intent_token("poochyena_fang").
item_intent_token("porygon_candy").
item_intent_token("potato_salad").
item_intent_token("potato_tortilla").
item_intent_token("potion").
item_intent_token("powder_jar").
item_intent_token("power_anklet").
item_intent_token("power_band").
item_intent_token("power_belt").
item_intent_token("power_bracer").
item_intent_token("power_herb").
item_intent_token("power_lens").
item_intent_token("power_plant_pass").
item_intent_token("power_up_pocket").
item_intent_token("power_weight").
item_intent_token("pp_max").
item_intent_token("pp_up").
item_intent_token("precooked_burger").
item_intent_token("premier_ball").
item_intent_token("pretty_wing").
item_intent_token("primarium_z_bag").
item_intent_token("primarium_z_held").
item_intent_token("prism_scale").
item_intent_token("prison_bottle").
item_intent_token("professors_mask").
item_intent_token("profs_letter").
item_intent_token("prop_case").
item_intent_token("prosciutto").
item_intent_token("protective_pads").
item_intent_token("protector").
item_intent_token("protein").
item_intent_token("psychic_gem").
item_intent_token("psychic_memory").
item_intent_token("psychic_seed").
item_intent_token("psychic_tera_shard").
item_intent_token("psychium_z_bag").
item_intent_token("psychium_z_held").
item_intent_token("psyduck_candy").
item_intent_token("psyduck_down").
item_intent_token("punching_glove").
item_intent_token("pungent_root").
item_intent_token("pure_incense").
item_intent_token("purple_nectar").
item_intent_token("purple_petal").
item_intent_token("qualot_berry").
item_intent_token("quick_ball").
item_intent_token("quick_candy").
item_intent_token("quick_candy_l").
item_intent_token("quick_candy_xl").
item_intent_token("quick_claw").
item_intent_token("quick_powder").
item_intent_token("quiet_mint").
item_intent_token("qwilfish_spines").
item_intent_token("rabuta_berry").
item_intent_token("radiant_petal").
item_intent_token("rage_candy_bar").
item_intent_token("rainbow_flower").
item_intent_token("rainbow_pass").
item_intent_token("rainbow_wing").
item_intent_token("ralts_dust").
item_intent_token("rare_bone").
item_intent_token("rare_candy").
item_intent_token("rash_mint").
item_intent_token("rattata_candy").
item_intent_token("rawst_berry").
item_intent_token("razor_claw").
item_intent_token("razor_fang").
item_intent_token("razz_berry").
item_intent_token("reaper_cloth").
item_intent_token("red_apricorn").
item_intent_token("red_bell_pepper").
item_intent_token("red_card").
item_intent_token("red_chain").
item_intent_token("red_dish").
item_intent_token("red_flag_pick").
item_intent_token("red_flute").
item_intent_token("red_nectar").
item_intent_token("red_onion").
item_intent_token("red_orb").
item_intent_token("red_petal").
item_intent_token("red_poke_ball_pick").
item_intent_token("red_scale").
item_intent_token("red_scarf").
item_intent_token("red_shard").
item_intent_token("reins_of_unity").
item_intent_token("reins_of_unity_merge").
item_intent_token("reins_of_unity_split").
item_intent_token("relaxed_mint").
item_intent_token("relic_band").
item_intent_token("relic_copper").
item_intent_token("relic_crown").
item_intent_token("relic_gold").
item_intent_token("relic_silver").
item_intent_token("relic_statue").
item_intent_token("relic_vase").
item_intent_token("rellor_mud").
item_intent_token("repeat_ball").
item_intent_token("repel").
item_intent_token("reply_mail").
item_intent_token("reset_urge").
item_intent_token("resist_mochi").
item_intent_token("resist_wing").
item_intent_token("retro_mail").
item_intent_token("reveal_glass").
item_intent_token("revival_herb").
item_intent_token("revive").
item_intent_token("rhyhorn_candy").
item_intent_token("ribbon_sweet").
item_intent_token("rice").
item_intent_token("rich_mulch").
item_intent_token("ride_pager").
item_intent_token("rindo_berry").
item_intent_token("ring_target").
item_intent_token("riolu_fur").
item_intent_token("rm_1_key").
item_intent_token("rm_2_key").
item_intent_token("rm_4_key").
item_intent_token("rm_6_key").
item_intent_token("rock_gem").
item_intent_token("rock_incense").
item_intent_token("rock_memory").
item_intent_token("rock_tera_shard").
item_intent_token("rockium_z_bag").
item_intent_token("rockium_z_held").
item_intent_token("rockruff_rock").
item_intent_token("rocky_helmet").
item_intent_token("roller_skates").
item_intent_token("rolycoly_coal").
item_intent_token("rookidee_feather").
item_intent_token("room_service").
item_intent_token("root_fossil").
item_intent_token("rose_incense").
item_intent_token("roseli_berry").
item_intent_token("roto_bargain").
item_intent_token("roto_boost").
item_intent_token("roto_catch").
item_intent_token("roto_encounter").
item_intent_token("roto_exp_points").
item_intent_token("roto_friendship").
item_intent_token("roto_hatch").
item_intent_token("roto_hp_restore").
item_intent_token("roto_pp_restore").
item_intent_token("roto_prize_money").
item_intent_token("roto_stealth").
item_intent_token("roto_stick").
item_intent_token("rotom_bike").
item_intent_token("rotom_bike_glistening_black").
item_intent_token("rotom_bike_sparkling_white").
item_intent_token("rotom_bike_water_mode").
item_intent_token("rotom_catalog").
item_intent_token("rotom_phone").
item_intent_token("rotom_sparks").
item_intent_token("rowap_berry").
item_intent_token("rsvp_mail").
item_intent_token("ruby").
item_intent_token("rufflet_feather").
item_intent_token("rule_book").
item_intent_token("rusted_shield").
item_intent_token("rusted_sword").
item_intent_token("sablenite").
item_intent_token("sableye_gem").
item_intent_token("sachet").
item_intent_token("sacred_ash").
item_intent_token("safari_ball").
item_intent_token("safety_goggles").
item_intent_token("sail_fossil").
item_intent_token("salac_berry").
item_intent_token("salad_mix").
item_intent_token("salamencite").
item_intent_token("salandit_gas").
item_intent_token("salt").
item_intent_token("salty_herba_mystica").
item_intent_token("sandile_claw").
item_intent_token("sandshrew_candy").
item_intent_token("sandshrew_claw").
item_intent_token("sandwich").
item_intent_token("sandygast_sand").
item_intent_token("sapphire").
item_intent_token("sassy_mint").
item_intent_token("sausages").
item_intent_token("scanner").
item_intent_token("scarlet_book").
item_intent_token("scatterbug_powder").
item_intent_token("sceptilite").
item_intent_token("scizorite").
item_intent_token("scope_lens").
item_intent_token("scroll_of_darkness").
item_intent_token("scroll_of_waters").
item_intent_token("scyther_candy").
item_intent_token("scyther_claw").
item_intent_token("sea_incense").
item_intent_token("seal_bag").
item_intent_token("seal_case").
item_intent_token("secret_key").
item_intent_token("secret_key_letsgo").
item_intent_token("secret_potion").
item_intent_token("seedot_stem").
item_intent_token("seel_candy").
item_intent_token("sentret_fur").
item_intent_token("serious_mint").
item_intent_token("seviper_fang").
item_intent_token("sewaddle_leaf").
item_intent_token("shaderoot_carrot").
item_intent_token("shadow_mail").
item_intent_token("shalour_sable").
item_intent_token("sharp_beak").
item_intent_token("sharpedonite").
item_intent_token("shed_shell").
item_intent_token("shell_bell").
item_intent_token("shellder_candy").
item_intent_token("shellder_pearl").
item_intent_token("shellos_mucus").
item_intent_token("shinx_fang").
item_intent_token("shiny_charm").
item_intent_token("shiny_stone").
item_intent_token("shoal_salt").
item_intent_token("shoal_shell").
item_intent_token("shock_drive").
item_intent_token("shroodle_ink").
item_intent_token("shroomish_spores").
item_intent_token("shuca_berry").
item_intent_token("shuppet_scrap").
item_intent_token("silicobra_sand").
item_intent_token("silk_scarf").
item_intent_token("silph_scope").
item_intent_token("silver_bottle").
item_intent_token("silver_cup").
item_intent_token("silver_leaf").
item_intent_token("silver_nanab_berry").
item_intent_token("silver_pick").
item_intent_token("silver_pinap_berry").
item_intent_token("silver_powder").
item_intent_token("silver_razz_berry").
item_intent_token("silver_wing").
item_intent_token("sinistea_chip").
item_intent_token("sitrus_berry").
item_intent_token("skiddo_leaf").
item_intent_token("skrelp_kelp").
item_intent_token("skull_fossil").
item_intent_token("skwovet_fur").
item_intent_token("sky_plate").
item_intent_token("slakoth_fur").
item_intent_token("slowbronite").
item_intent_token("slowpoke_candy").
item_intent_token("slowpoke_claw").
item_intent_token("slowpoke_cup").
item_intent_token("slowpoke_tail").
item_intent_token("slugma_lava").
item_intent_token("small_bouquet").
item_intent_token("smart_candy").
item_intent_token("smart_candy_l").
item_intent_token("smart_candy_xl").
item_intent_token("smiling_vee_pick").
item_intent_token("smoke_ball").
item_intent_token("smoke_poke_tail").
item_intent_token("smoked_fillet").
item_intent_token("smoliv_oil").
item_intent_token("smooth_rock").
item_intent_token("sneasel_claw").
item_intent_token("snom_thread").
item_intent_token("snorlax_candy").
item_intent_token("snorlium_z_bag").
item_intent_token("snorlium_z_held").
item_intent_token("snorunt_fur").
item_intent_token("snover_berries").
item_intent_token("snow_mail").
item_intent_token("snowball").
item_intent_token("soda_pop").
item_intent_token("soft_sand").
item_intent_token("solganium_z_bag").
item_intent_token("solganium_z_held").
item_intent_token("sonias_book").
item_intent_token("soot_sack").
item_intent_token("soothe_bell").
item_intent_token("soul_dew").
item_intent_token("sour_herba_mystica").
item_intent_token("space_mail").
item_intent_token("sparkling_stone").
item_intent_token("spearow_candy").
item_intent_token("spell_tag").
item_intent_token("spelon_berry").
item_intent_token("spice_mix").
item_intent_token("spicy_herba_mystica").
item_intent_token("spinarak_thread").
item_intent_token("spiritomb_fragment").
item_intent_token("splash_plate").
item_intent_token("spoink_pearl").
item_intent_token("spooky_plate").
item_intent_token("spooky_tablecloth").
item_intent_token("sport_ball").
item_intent_token("sprayduck").
item_intent_token("sprinklotad").
item_intent_token("squawkabilly_feather").
item_intent_token("squirt_bottle").
item_intent_token("squirtle_candy").
item_intent_token("ss_ticket").
item_intent_token("ss_ticket_hoenn").
item_intent_token("ss_ticket_letsgo").
item_intent_token("stable_mulch").
item_intent_token("stantler_hair").
item_intent_token("star_piece").
item_intent_token("star_sweet").
item_intent_token("stardust").
item_intent_token("starf_berry").
item_intent_token("starly_feather").
item_intent_token("staryu_candy").
item_intent_token("steel_bottle_b").
item_intent_token("steel_bottle_r").
item_intent_token("steel_bottle_y").
item_intent_token("steel_gem").
item_intent_token("steel_mail").
item_intent_token("steel_memory").
item_intent_token("steel_tera_shard").
item_intent_token("steelium_z_bag").
item_intent_token("steelium_z_held").
item_intent_token("steelixite").
item_intent_token("stick").
item_intent_token("sticky_barb").
item_intent_token("stone_plate").
item_intent_token("stonjourner_stone").
item_intent_token("storage_key").
item_intent_token("storage_key_galactic_warehouse").
item_intent_token("storage_key_sea_mauville").
item_intent_token("strange_ball").
item_intent_token("strange_souvenir").
item_intent_token("strawberry").
item_intent_token("strawberry_sweet").
item_intent_token("stretchy_spring").
item_intent_token("striped_bottle").
item_intent_token("striped_cup").
item_intent_token("striped_tablecloth").
item_intent_token("stunky_fur").
item_intent_token("style_card").
item_intent_token("suite_key").
item_intent_token("sun_flute").
item_intent_token("sun_stone").
item_intent_token("sunkern_leaf").
item_intent_token("sunrise_flower_pick").
item_intent_token("sunset_flower_pick").
item_intent_token("super_lure").
item_intent_token("super_potion").
item_intent_token("super_repel").
item_intent_token("super_rod").
item_intent_token("surge_badge").
item_intent_token("surprise_mulch").
item_intent_token("surskit_syrup").
item_intent_token("swablu_fluff").
item_intent_token("swampertite").
item_intent_token("sweet_apple").
item_intent_token("sweet_heart").
item_intent_token("sweet_herba_mystica").
item_intent_token("swift_mochi").
item_intent_token("swift_wing").
item_intent_token("swinub_hair").
item_intent_token("syrupy_apple").
item_intent_token("tadbulb_mucus").
item_intent_token("tamato_berry").
item_intent_token("tandemaus_fur").
item_intent_token("tanga_berry").
item_intent_token("tangela_candy").
item_intent_token("tapunium_z_bag").
item_intent_token("tapunium_z_held").
item_intent_token("tarountula_thread").
item_intent_token("tart_apple").
item_intent_token("tatsugiri_scales").
item_intent_token("tauros_candy").
item_intent_token("tauros_hair").
item_intent_token("tea").
item_intent_token("teachy_tv").
item_intent_token("teal_mask").
item_intent_token("teal_style_card").
item_intent_token("teddiursa_claw").
item_intent_token("tentacool_candy").
item_intent_token("tera_orb").
item_intent_token("terrain_extender").
item_intent_token("thanks_mail").
item_intent_token("thick_club").
item_intent_token("throat_spray").
item_intent_token("thunder_stone").
item_intent_token("tidal_bell").
item_intent_token("timburr_sweat").
item_intent_token("timer_ball").
item_intent_token("timid_mint").
item_intent_token("tin_of_beans").
item_intent_token("tinkatink_hair").
item_intent_token("tiny_bamboo_shoot").
item_intent_token("tiny_mushroom").
item_intent_token("tm_case").
item_intent_token("tm00").
item_intent_token("tm01").
item_intent_token("tm02").
item_intent_token("tm03").
item_intent_token("tm04").
item_intent_token("tm05").
item_intent_token("tm06").
item_intent_token("tm07").
item_intent_token("tm08").
item_intent_token("tm09").
item_intent_token("tm10").
item_intent_token("tm100").
item_intent_token("tm101").
item_intent_token("tm102").
item_intent_token("tm103").
item_intent_token("tm104").
item_intent_token("tm105").
item_intent_token("tm106").
item_intent_token("tm107").
item_intent_token("tm108").
item_intent_token("tm109").
item_intent_token("tm11").
item_intent_token("tm110").
item_intent_token("tm111").
item_intent_token("tm112").
item_intent_token("tm113").
item_intent_token("tm114").
item_intent_token("tm115").
item_intent_token("tm116").
item_intent_token("tm117").
item_intent_token("tm118").
item_intent_token("tm119").
item_intent_token("tm12").
item_intent_token("tm120").
item_intent_token("tm121").
item_intent_token("tm122").
item_intent_token("tm123").
item_intent_token("tm124").
item_intent_token("tm125").
item_intent_token("tm126").
item_intent_token("tm127").
item_intent_token("tm128").
item_intent_token("tm129").
item_intent_token("tm13").
item_intent_token("tm130").
item_intent_token("tm131").
item_intent_token("tm132").
item_intent_token("tm133").
item_intent_token("tm134").
item_intent_token("tm135").
item_intent_token("tm136").
item_intent_token("tm137").
item_intent_token("tm138").
item_intent_token("tm139").
item_intent_token("tm14").
item_intent_token("tm140").
item_intent_token("tm141").
item_intent_token("tm142").
item_intent_token("tm143").
item_intent_token("tm144").
item_intent_token("tm145").
item_intent_token("tm146").
item_intent_token("tm147").
item_intent_token("tm148").
item_intent_token("tm149").
item_intent_token("tm15").
item_intent_token("tm150").
item_intent_token("tm151").
item_intent_token("tm152").
item_intent_token("tm153").
item_intent_token("tm154").
item_intent_token("tm155").
item_intent_token("tm156").
item_intent_token("tm157").
item_intent_token("tm158").
item_intent_token("tm159").
item_intent_token("tm16").
item_intent_token("tm160").
item_intent_token("tm161").
item_intent_token("tm162").
item_intent_token("tm163").
item_intent_token("tm164").
item_intent_token("tm165").
item_intent_token("tm166").
item_intent_token("tm167").
item_intent_token("tm168").
item_intent_token("tm169").
item_intent_token("tm17").
item_intent_token("tm170").
item_intent_token("tm171").
item_intent_token("tm172").
item_intent_token("tm173").
item_intent_token("tm174").
item_intent_token("tm175").
item_intent_token("tm176").
item_intent_token("tm177").
item_intent_token("tm178").
item_intent_token("tm179").
item_intent_token("tm18").
item_intent_token("tm180").
item_intent_token("tm181").
item_intent_token("tm182").
item_intent_token("tm183").
item_intent_token("tm184").
item_intent_token("tm185").
item_intent_token("tm186").
item_intent_token("tm187").
item_intent_token("tm188").
item_intent_token("tm189").
item_intent_token("tm19").
item_intent_token("tm190").
item_intent_token("tm191").
item_intent_token("tm192").
item_intent_token("tm193").
item_intent_token("tm194").
item_intent_token("tm195").
item_intent_token("tm196").
item_intent_token("tm197").
item_intent_token("tm198").
item_intent_token("tm199").
item_intent_token("tm20").
item_intent_token("tm200").
item_intent_token("tm201").
item_intent_token("tm202").
item_intent_token("tm203").
item_intent_token("tm204").
item_intent_token("tm205").
item_intent_token("tm206").
item_intent_token("tm207").
item_intent_token("tm208").
item_intent_token("tm209").
item_intent_token("tm21").
item_intent_token("tm210").
item_intent_token("tm211").
item_intent_token("tm212").
item_intent_token("tm213").
item_intent_token("tm214").
item_intent_token("tm215").
item_intent_token("tm216").
item_intent_token("tm217").
item_intent_token("tm218").
item_intent_token("tm219").
item_intent_token("tm22").
item_intent_token("tm220").
item_intent_token("tm221").
item_intent_token("tm222").
item_intent_token("tm223").
item_intent_token("tm224").
item_intent_token("tm225").
item_intent_token("tm226").
item_intent_token("tm227").
item_intent_token("tm228").
item_intent_token("tm229").
item_intent_token("tm23").
item_intent_token("tm24").
item_intent_token("tm25").
item_intent_token("tm26").
item_intent_token("tm27").
item_intent_token("tm28").
item_intent_token("tm29").
item_intent_token("tm30").
item_intent_token("tm31").
item_intent_token("tm32").
item_intent_token("tm33").
item_intent_token("tm34").
item_intent_token("tm35").
item_intent_token("tm36").
item_intent_token("tm37").
item_intent_token("tm38").
item_intent_token("tm39").
item_intent_token("tm40").
item_intent_token("tm41").
item_intent_token("tm42").
item_intent_token("tm43").
item_intent_token("tm44").
item_intent_token("tm45").
item_intent_token("tm46").
item_intent_token("tm47").
item_intent_token("tm48").
item_intent_token("tm49").
item_intent_token("tm50").
item_intent_token("tm51").
item_intent_token("tm52").
item_intent_token("tm53").
item_intent_token("tm54").
item_intent_token("tm55").
item_intent_token("tm56").
item_intent_token("tm57").
item_intent_token("tm58").
item_intent_token("tm59").
item_intent_token("tm60").
item_intent_token("tm61").
item_intent_token("tm62").
item_intent_token("tm63").
item_intent_token("tm64").
item_intent_token("tm65").
item_intent_token("tm66").
item_intent_token("tm67").
item_intent_token("tm68").
item_intent_token("tm69").
item_intent_token("tm70").
item_intent_token("tm71").
item_intent_token("tm72").
item_intent_token("tm73").
item_intent_token("tm74").
item_intent_token("tm75").
item_intent_token("tm76").
item_intent_token("tm77").
item_intent_token("tm78").
item_intent_token("tm79").
item_intent_token("tm80").
item_intent_token("tm81").
item_intent_token("tm82").
item_intent_token("tm83").
item_intent_token("tm84").
item_intent_token("tm85").
item_intent_token("tm86").
item_intent_token("tm87").
item_intent_token("tm88").
item_intent_token("tm89").
item_intent_token("tm90").
item_intent_token("tm91").
item_intent_token("tm92").
item_intent_token("tm93").
item_intent_token("tm94").
item_intent_token("tm95").
item_intent_token("tm96").
item_intent_token("tm97").
item_intent_token("tm98").
item_intent_token("tm99").
item_intent_token("tmv_pass").
item_intent_token("toedscool_flaps").
item_intent_token("tofu").
item_intent_token("tomato").
item_intent_token("torkoal_coal").
item_intent_token("tough_candy").
item_intent_token("tough_candy_l").
item_intent_token("tough_candy_xl").
item_intent_token("town_map").
item_intent_token("toxel_sparks").
item_intent_token("toxic_orb").
item_intent_token("toxic_plate").
item_intent_token("tr00").
item_intent_token("tr01").
item_intent_token("tr02").
item_intent_token("tr03").
item_intent_token("tr04").
item_intent_token("tr05").
item_intent_token("tr06").
item_intent_token("tr07").
item_intent_token("tr08").
item_intent_token("tr09").
item_intent_token("tr10").
item_intent_token("tr11").
item_intent_token("tr12").
item_intent_token("tr13").
item_intent_token("tr14").
item_intent_token("tr15").
item_intent_token("tr16").
item_intent_token("tr17").
item_intent_token("tr18").
item_intent_token("tr19").
item_intent_token("tr20").
item_intent_token("tr21").
item_intent_token("tr22").
item_intent_token("tr23").
item_intent_token("tr24").
item_intent_token("tr25").
item_intent_token("tr26").
item_intent_token("tr27").
item_intent_token("tr28").
item_intent_token("tr29").
item_intent_token("tr30").
item_intent_token("tr31").
item_intent_token("tr32").
item_intent_token("tr33").
item_intent_token("tr34").
item_intent_token("tr35").
item_intent_token("tr36").
item_intent_token("tr37").
item_intent_token("tr38").
item_intent_token("tr39").
item_intent_token("tr40").
item_intent_token("tr41").
item_intent_token("tr42").
item_intent_token("tr43").
item_intent_token("tr44").
item_intent_token("tr45").
item_intent_token("tr46").
item_intent_token("tr47").
item_intent_token("tr48").
item_intent_token("tr49").
item_intent_token("tr50").
item_intent_token("tr51").
item_intent_token("tr52").
item_intent_token("tr53").
item_intent_token("tr54").
item_intent_token("tr55").
item_intent_token("tr56").
item_intent_token("tr57").
item_intent_token("tr58").
item_intent_token("tr59").
item_intent_token("tr60").
item_intent_token("tr61").
item_intent_token("tr62").
item_intent_token("tr63").
item_intent_token("tr64").
item_intent_token("tr65").
item_intent_token("tr66").
item_intent_token("tr67").
item_intent_token("tr68").
item_intent_token("tr69").
item_intent_token("tr70").
item_intent_token("tr71").
item_intent_token("tr72").
item_intent_token("tr73").
item_intent_token("tr74").
item_intent_token("tr75").
item_intent_token("tr76").
item_intent_token("tr77").
item_intent_token("tr78").
item_intent_token("tr79").
item_intent_token("tr80").
item_intent_token("tr81").
item_intent_token("tr82").
item_intent_token("tr83").
item_intent_token("tr84").
item_intent_token("tr85").
item_intent_token("tr86").
item_intent_token("tr87").
item_intent_token("tr88").
item_intent_token("tr89").
item_intent_token("tr90").
item_intent_token("tr91").
item_intent_token("tr92").
item_intent_token("tr93").
item_intent_token("tr94").
item_intent_token("tr95").
item_intent_token("tr96").
item_intent_token("tr97").
item_intent_token("tr98").
item_intent_token("tr99").
item_intent_token("travel_trunk").
item_intent_token("tri_pass").
item_intent_token("tropic_mail").
item_intent_token("tropical_shell").
item_intent_token("tropius_leaf").
item_intent_token("tunnel_mail").
item_intent_token("twisted_spoon").
item_intent_token("tynamo_slime").
item_intent_token("tyranitarite").
item_intent_token("ultra_ball").
item_intent_token("ultranecrozium_z_bag").
item_intent_token("ultranecrozium_z_held").
item_intent_token("unown_report").
item_intent_token("unremarkable_teacup").
item_intent_token("up_grade").
item_intent_token("utility_umbrella").
item_intent_token("varoom_fume").
item_intent_token("vee_vee_pick").
item_intent_token("veluza_fillet").
item_intent_token("venonat_candy").
item_intent_token("venonat_fang").
item_intent_token("venusaurite").
item_intent_token("vinegar").
item_intent_token("violet_book").
item_intent_token("volbeat_fluid").
item_intent_token("voltorb_candy").
item_intent_token("voltorb_sparks").
item_intent_token("vs_recorder").
item_intent_token("vs_seeker").
item_intent_token("vullaby_feather").
item_intent_token("vulpix_candy").
item_intent_token("vulpix_fur").
item_intent_token("wacan_berry").
item_intent_token("wailmer_pail").
item_intent_token("wasabi").
item_intent_token("water_gem").
item_intent_token("water_memory").
item_intent_token("water_stone").
item_intent_token("water_tera_shard").
item_intent_token("watercress").
item_intent_token("waterium_z_bag").
item_intent_token("waterium_z_held").
item_intent_token("watmel_berry").
item_intent_token("wattrel_feather").
item_intent_token("wave_incense").
item_intent_token("wave_mail").
item_intent_token("weakness_policy").
item_intent_token("weedle_candy").
item_intent_token("wellspring_mask").
item_intent_token("wepear_berry").
item_intent_token("whimsical_tablecloth").
item_intent_token("whipped_cream").
item_intent_token("whipped_dream").
item_intent_token("white_apricorn").
item_intent_token("white_dish").
item_intent_token("white_flute").
item_intent_token("white_herb").
item_intent_token("white_mane_hair").
item_intent_token("wide_lens").
item_intent_token("wiglett_sand").
item_intent_token("wiki_berry").
item_intent_token("wingull_feather").
item_intent_token("winking_pika_pick").
item_intent_token("wise_glasses").
item_intent_token("wishing_chip").
item_intent_token("wishing_piece").
item_intent_token("wishing_star").
item_intent_token("wood_mail").
item_intent_token("wooden_crown").
item_intent_token("wooper_slime").
item_intent_token("works_key").
item_intent_token("x_accuracy").
item_intent_token("x_accuracy_2").
item_intent_token("x_accuracy_3").
item_intent_token("x_accuracy_6").
item_intent_token("x_attack").
item_intent_token("x_attack_2").
item_intent_token("x_attack_3").
item_intent_token("x_attack_6").
item_intent_token("x_defense").
item_intent_token("x_defense_2").
item_intent_token("x_defense_3").
item_intent_token("x_defense_6").
item_intent_token("x_sp_atk").
item_intent_token("x_sp_atk_2").
item_intent_token("x_sp_atk_3").
item_intent_token("x_sp_atk_6").
item_intent_token("x_sp_def").
item_intent_token("x_sp_def_2").
item_intent_token("x_sp_def_3").
item_intent_token("x_sp_def_6").
item_intent_token("x_speed").
item_intent_token("x_speed_2").
item_intent_token("x_speed_3").
item_intent_token("x_speed_6").
item_intent_token("xtransceiver").
item_intent_token("xtransceiver_red").
item_intent_token("xtransceiver_yellow").
item_intent_token("yache_berry").
item_intent_token("yanma_spike").
item_intent_token("yarn_ball").
item_intent_token("yellow_apricorn").
item_intent_token("yellow_bell_pepper").
item_intent_token("yellow_bottle").
item_intent_token("yellow_cup").
item_intent_token("yellow_dish").
item_intent_token("yellow_flute").
item_intent_token("yellow_nectar").
item_intent_token("yellow_petal").
item_intent_token("yellow_scarf").
item_intent_token("yellow_shard").
item_intent_token("yellow_tablecloth").
item_intent_token("yogurt").
item_intent_token("yungoos_fur").
item_intent_token("z_power_ring").
item_intent_token("z_ring").
item_intent_token("zangoose_claw").
item_intent_token("zap_plate").
item_intent_token("zapdos_candy").
item_intent_token("zinc").
item_intent_token("zoom_lens").
item_intent_token("zorua_fur").
item_intent_token("zubat_candy").
item_intent_token("zygarde_cube").

item_intent_phrase(["ability", "shield"]).
item_intent_phrase(["absorb", "bulb"]).
item_intent_phrase(["adamant", "orb"]).
item_intent_phrase(["adrenaline", "orb"]).
item_intent_phrase(["air", "balloon"]).
item_intent_phrase(["aloraichium", "held"]).
item_intent_phrase(["apicot", "berry"]).
item_intent_phrase(["assault", "vest"]).
item_intent_phrase(["babiri", "berry"]).
item_intent_phrase(["big", "root"]).
item_intent_phrase(["binding", "band"]).
item_intent_phrase(["black", "belt"]).
item_intent_phrase(["black", "glasses"]).
item_intent_phrase(["black", "sludge"]).
item_intent_phrase(["blank", "plate"]).
item_intent_phrase(["blunder", "policy"]).
item_intent_phrase(["booster", "energy"]).
item_intent_phrase(["bright", "powder"]).
item_intent_phrase(["bug", "memory"]).
item_intent_phrase(["buginium", "held"]).
item_intent_phrase(["burn", "drive"]).
item_intent_phrase(["cell", "battery"]).
item_intent_phrase(["charti", "berry"]).
item_intent_phrase(["chilan", "berry"]).
item_intent_phrase(["chill", "drive"]).
item_intent_phrase(["chople", "berry"]).
item_intent_phrase(["clear", "amulet"]).
item_intent_phrase(["coba", "berry"]).
item_intent_phrase(["colbur", "berry"]).
item_intent_phrase(["cornerstone", "mask"]).
item_intent_phrase(["covert", "cloak"]).
item_intent_phrase(["custap", "berry"]).
item_intent_phrase(["damp", "rock"]).
item_intent_phrase(["dark", "memory"]).
item_intent_phrase(["darkinium", "held"]).
item_intent_phrase(["decidium", "held"]).
item_intent_phrase(["deep", "sea", "scale"]).
item_intent_phrase(["deep", "sea", "tooth"]).
item_intent_phrase(["destiny", "knot"]).
item_intent_phrase(["douse", "drive"]).
item_intent_phrase(["draco", "plate"]).
item_intent_phrase(["dragon", "fang"]).
item_intent_phrase(["dragon", "memory"]).
item_intent_phrase(["dragonium", "held"]).
item_intent_phrase(["dread", "plate"]).
item_intent_phrase(["earth", "plate"]).
item_intent_phrase(["eevium", "held"]).
item_intent_phrase(["eject", "button"]).
item_intent_phrase(["eject", "pack"]).
item_intent_phrase(["electric", "memory"]).
item_intent_phrase(["electric", "seed"]).
item_intent_phrase(["electrium", "held"]).
item_intent_phrase(["expert", "belt"]).
item_intent_phrase(["fairium", "held"]).
item_intent_phrase(["fairy", "feather"]).
item_intent_phrase(["fairy", "memory"]).
item_intent_phrase(["fighting", "memory"]).
item_intent_phrase(["fightinium", "held"]).
item_intent_phrase(["fire", "memory"]).
item_intent_phrase(["firium", "held"]).
item_intent_phrase(["fist", "plate"]).
item_intent_phrase(["flame", "plate"]).
item_intent_phrase(["float", "stone"]).
item_intent_phrase(["flying", "memory"]).
item_intent_phrase(["flyinium", "held"]).
item_intent_phrase(["focus", "band"]).
item_intent_phrase(["focus", "sash"]).
item_intent_phrase(["ganlon", "berry"]).
item_intent_phrase(["ghost", "memory"]).
item_intent_phrase(["ghostium", "held"]).
item_intent_phrase(["grass", "memory"]).
item_intent_phrase(["grassium", "held"]).
item_intent_phrase(["grassy", "seed"]).
item_intent_phrase(["grip", "claw"]).
item_intent_phrase(["griseous", "orb"]).
item_intent_phrase(["ground", "memory"]).
item_intent_phrase(["groundium", "held"]).
item_intent_phrase(["haban", "berry"]).
item_intent_phrase(["hard", "stone"]).
item_intent_phrase(["hearthflame", "mask"]).
item_intent_phrase(["heat", "rock"]).
item_intent_phrase(["heavy", "duty", "boots"]).
item_intent_phrase(["ice", "memory"]).
item_intent_phrase(["icicle", "plate"]).
item_intent_phrase(["icium", "held"]).
item_intent_phrase(["icy", "rock"]).
item_intent_phrase(["incinium", "held"]).
item_intent_phrase(["insect", "plate"]).
item_intent_phrase(["iron", "plate"]).
item_intent_phrase(["kasib", "berry"]).
item_intent_phrase(["kebia", "berry"]).
item_intent_phrase(["kings", "rock"]).
item_intent_phrase(["lansat", "berry"]).
item_intent_phrase(["lax", "incense"]).
item_intent_phrase(["legend", "plate"]).
item_intent_phrase(["liechi", "berry"]).
item_intent_phrase(["life", "orb"]).
item_intent_phrase(["light", "ball"]).
item_intent_phrase(["light", "clay"]).
item_intent_phrase(["loaded", "dice"]).
item_intent_phrase(["lucky", "punch"]).
item_intent_phrase(["luminous", "moss"]).
item_intent_phrase(["lustrous", "orb"]).
item_intent_phrase(["marshadium", "held"]).
item_intent_phrase(["meadow", "plate"]).
item_intent_phrase(["mental", "herb"]).
item_intent_phrase(["metal", "coat"]).
item_intent_phrase(["metal", "powder"]).
item_intent_phrase(["mewnium", "held"]).
item_intent_phrase(["micle", "berry"]).
item_intent_phrase(["mind", "plate"]).
item_intent_phrase(["miracle", "seed"]).
item_intent_phrase(["mirror", "herb"]).
item_intent_phrase(["misty", "seed"]).
item_intent_phrase(["muscle", "band"]).
item_intent_phrase(["mystic", "water"]).
item_intent_phrase(["never", "melt", "ice"]).
item_intent_phrase(["normalium", "held"]).
item_intent_phrase(["occa", "berry"]).
item_intent_phrase(["odd", "incense"]).
item_intent_phrase(["pass", "orb"]).
item_intent_phrase(["passho", "berry"]).
item_intent_phrase(["payapa", "berry"]).
item_intent_phrase(["petaya", "berry"]).
item_intent_phrase(["pikanium", "held"]).
item_intent_phrase(["pikashunium", "held"]).
item_intent_phrase(["pink", "nectar"]).
item_intent_phrase(["pixie", "plate"]).
item_intent_phrase(["poison", "barb"]).
item_intent_phrase(["poison", "memory"]).
item_intent_phrase(["poisonium", "held"]).
item_intent_phrase(["power", "herb"]).
item_intent_phrase(["primarium", "held"]).
item_intent_phrase(["protective", "pads"]).
item_intent_phrase(["psychic", "memory"]).
item_intent_phrase(["psychic", "seed"]).
item_intent_phrase(["psychium", "held"]).
item_intent_phrase(["punching", "glove"]).
item_intent_phrase(["purple", "nectar"]).
item_intent_phrase(["quick", "claw"]).
item_intent_phrase(["quick", "powder"]).
item_intent_phrase(["razor", "claw"]).
item_intent_phrase(["razor", "fang"]).
item_intent_phrase(["red", "card"]).
item_intent_phrase(["red", "nectar"]).
item_intent_phrase(["rindo", "berry"]).
item_intent_phrase(["ring", "target"]).
item_intent_phrase(["rock", "incense"]).
item_intent_phrase(["rock", "memory"]).
item_intent_phrase(["rockium", "held"]).
item_intent_phrase(["rocky", "helmet"]).
item_intent_phrase(["room", "service"]).
item_intent_phrase(["rose", "incense"]).
item_intent_phrase(["roseli", "berry"]).
item_intent_phrase(["rusted", "shield"]).
item_intent_phrase(["rusted", "sword"]).
item_intent_phrase(["safety", "goggles"]).
item_intent_phrase(["salac", "berry"]).
item_intent_phrase(["scope", "lens"]).
item_intent_phrase(["sea", "incense"]).
item_intent_phrase(["sharp", "beak"]).
item_intent_phrase(["shed", "shell"]).
item_intent_phrase(["shell", "bell"]).
item_intent_phrase(["shock", "drive"]).
item_intent_phrase(["shuca", "berry"]).
item_intent_phrase(["silk", "scarf"]).
item_intent_phrase(["silver", "powder"]).
item_intent_phrase(["sky", "plate"]).
item_intent_phrase(["smoke", "ball"]).
item_intent_phrase(["smooth", "rock"]).
item_intent_phrase(["snorlium", "held"]).
item_intent_phrase(["soft", "sand"]).
item_intent_phrase(["soul", "dew"]).
item_intent_phrase(["spell", "tag"]).
item_intent_phrase(["splash", "plate"]).
item_intent_phrase(["spooky", "plate"]).
item_intent_phrase(["starf", "berry"]).
item_intent_phrase(["steel", "memory"]).
item_intent_phrase(["steelium", "held"]).
item_intent_phrase(["stone", "plate"]).
item_intent_phrase(["tanga", "berry"]).
item_intent_phrase(["tapunium", "held"]).
item_intent_phrase(["terrain", "extender"]).
item_intent_phrase(["thick", "club"]).
item_intent_phrase(["throat", "spray"]).
item_intent_phrase(["toxic", "plate"]).
item_intent_phrase(["twisted", "spoon"]).
item_intent_phrase(["utility", "umbrella"]).
item_intent_phrase(["wacan", "berry"]).
item_intent_phrase(["water", "memory"]).
item_intent_phrase(["waterium", "held"]).
item_intent_phrase(["wave", "incense"]).
item_intent_phrase(["weakness", "policy"]).
item_intent_phrase(["wellspring", "mask"]).
item_intent_phrase(["white", "herb"]).
item_intent_phrase(["wide", "lens"]).
item_intent_phrase(["wise", "glasses"]).
item_intent_phrase(["yache", "berry"]).
item_intent_phrase(["yellow", "nectar"]).
item_intent_phrase(["zap", "plate"]).
item_intent_phrase(["zoom", "lens"]).
